### ISSUE TITLE
seer 0.6.0 插件问题反馈

### ISSUE THREAD

**Issue by black0king** [ccseer/Seer#10]
seer 0.6.0
win10  X64       0ffice  2013
在刚刚安装后第一次运行时插件运行正常，但关闭后再次开启时就会找不到插件，并提示“权限失败，配置插件配置无法保存”。如图：
![1](https://cloud.githubusercontent.com/assets/17475061/13337202/09b543f8-dc55-11e5-8e6a-8e3efaf48902.PNG)
若以管理员身份运行时同样找不到插件，但不会提示“权限失败……”
而根据作者提供的路径添加插件时会找不到插件：
![2](https://cloud.githubusercontent.com/assets/17475061/13337366/e4c9daa8-dc55-11e5-91a0-bffe6bbbf541.PNG)
但通过文件管理器查看发现插件数据存在：
![3](https://cloud.githubusercontent.com/assets/17475061/13337447/5d2f75c0-dc56-11e5-8a53-0606b247bc89.PNG)
作者应该是中国人或者会中文吧？我就不用英文了。
目前没发现其他问题，软件很便利，谢谢作者的开发和分享。
@ccseer

**Comment by ccseer** [comment]
无法添加是因为中文的原因，国际化的时候出了错，切换到英文应该就可以了。

关于这部分的问题下个版本会全部改掉。 

谢谢反馈

**Comment by black0king** [comment]
确实，我的问题解决了，谢谢。
