### ISSUE TITLE
win7无效

### ISSUE THREAD

**Issue by lizhanqi** [ccseer/Seer#100]
我在使用win7的时候无法预览文件,space键无法生效.即便设置ctrl+space也同样无法预览

**Comment by ccseer** [comment]
版本？

**Comment by ccseer** [comment]
你使用了 最新版  1.4.0. 然后过了3天了.  就会需要授权.  http://1218.io/seer/Alipay.html

或者你可以使用免费版 sourceforge.net/projects/ccseer/files/stats/timeline

**Comment by lizhanqi** [comment]
当前使用的是0.81版本(应该是免费版,因为也没找到注册ID之类设置)在360软件中心下载的,使用刚才连接中的都是一样无法使用(没有快捷键冲突问题,也没做没弹窗拦截)

**Comment by ccseer** [comment]
0.8.1 应该是没问题的。

是 资源管理器 无法响应 还是 桌面 没反应， 还是全部？

要不 你看看把其他的软件关了试试？
