### ISSUE TITLE
按空格键时仅在搜索栏出现一个空格 seer完全无反应

### ISSUE THREAD

**Issue by swos0000** [ccseer/Seer#101]
设置ctrl之类均无效 必须用三个键才能调用= =
系统win10 rs2
另外希望预览的时候可以直接用左右方向键预览上下一个文件

**Comment by ccseer** [comment]
快捷键应该被别的软件占用了

你是用的0.8.1么，里面有个配置跟踪选中文件，选上就可以用方向键了

**Comment by ccseer** [comment]
方向键预览其他文件有个问题是， 你点击预览窗口之后，焦点就到了 Seer 上，用于一些复制和程序内的快捷键。这个时候你再使用上下左右就没用了，需要点一下 资源管理器 或者桌面才行。

1.4.0 是可以用全局快捷键在触发焦点和 预览窗口间切换的， 0.8.1 目前只能让预览窗口获取焦点。

**Comment by ccseer** [comment]
啊～～

抱歉啊。
今天在过 bug 列表才发现
你这个应该不是快捷键被占用了


是 explorer 里面有个设置。有些机器的默认配置就是会在空格时移到 搜索
看这个可以解决
http://windowsclan.com/get-mac-like-file-preview-seer-windows-10/


![ec479ea5f926f5cff71ecdd2ced12da6](https://user-images.githubusercontent.com/15963166/27991633-5a9933e4-64b0-11e7-949d-79758ac13a00.png)

**Comment by swos0000** [comment]
哇擦还有这么回事 建议你们直接写个reg 安装的时候给默认调了

-------- 原始邮件 --------
主题：Re: [ccseer/Seer] 按空格键时仅在搜索栏出现一个空格 seer完全无反应 (#101)
发件人：Seer
收件人：ccseer/Seer
抄送：swos0000 ,Manual


啊～～

抱歉啊。
今天在过 bug 列表才发现
你这个应该不是快捷键被占用了

是 explorer 里面有个设置。有些机器的默认配置就是会在空格时移到 搜索
看这个可以解决
http://windowsclan.com/get-mac-like-file-preview-seer-windows-10/

[ec479ea5f926f5cff71ecdd2ced12da6]<https://user-images.githubusercontent.com/15963166/27991633-5a9933e4-64b0-11e7-949d-79758ac13a00.png>

―

**Comment by ccseer** [comment]
不行啊

程序连  开机启动  都是默认关闭的
就是不想擅自改系统配置

**Comment by swos0000** [comment]
真良心 可以的

-------- 原始邮件 --------
主题：Re: [ccseer/Seer] 按空格键时仅在搜索栏出现一个空格 seer完全无反应 (#101)
发件人：Seer
收件人：ccseer/Seer
抄送：swos0000 ,Manual


不行啊

程序连 开机启动 都是默认关闭的
就是不想擅自改系统配置

―
