### ISSUE TITLE
Black frames for about 1 second during video playback

### ISSUE THREAD

**Issue by howdydewdy** [ccseer/Seer#103]
When I initially hit spacebar, seer pops up immediately and timeline slider starts moving but video playback does not appear until a second in. Initially it displays thumbnail for 1/3 of a second. Then it goes black for 2/3 of a second. Then it starts displaying video playback.

In order to playback the entire video I need to manually move back the slider to the beginning of the clip.

**Comment by ccseer** [comment]
You want a option to turn the record off, so every time it can start from the beginning?

**Comment by ccseer** [comment]
I add a shortcut for media type, pressing "Home" can make the video to the beginning
