### ISSUE TITLE
Orientation of Images/Video

### ISSUE THREAD

**Issue by cofuzed** [ccseer/Seer#105]
When viewing videos or images, it appears they do not take into account the orientation.  Sometimes the images or videos will appear sideways or upside down.  Modern cameras will write an orientation flag to allow applications to know how to orient the image/video on screen.

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer/issues/34

**Comment by ccseer** [comment]
it has fixed in 1.0.0
