### ISSUE TITLE
Targa (.tga) support

### ISSUE THREAD

**Issue by djcurley89** [ccseer/Seer#106]
Can you add support for Targa image files (.tga)? Right now it just pops up with the file info and no image preview.

**Comment by ccseer** [comment]
setup AutoCAD plugin

![image](https://user-images.githubusercontent.com/15963166/28047781-26e432a4-661f-11e7-95ba-bbda634aca17.png)


![image](https://user-images.githubusercontent.com/15963166/28047784-311dd414-661f-11e7-97ef-11829fdf2a1c.png)

**Comment by ccseer** [comment]
??

but Seer support it by default.

![image](https://user-images.githubusercontent.com/15963166/28047860-b1bb31f2-661f-11e7-8b6c-0f4c5a788213.png)

**Comment by djcurley89** [comment]
I had the AutoCAD Jpg2png plugin installed but tga wasn't in the list, I added it manually and now it opens the targa files just fine. It definitely wasn't supporting these tga files by default. I'd attach it here as an example but git won't support me uploading that file.

**Comment by ccseer** [comment]
It's ok if it works.

All you need to fill in that extension field is tga. Please remove other extensions.
