### ISSUE TITLE
Images oddly cropped, no controls over window size 

### ISSUE THREAD

**Issue by heyyasly** [ccseer/Seer#107]
Images oddly cropped
no controls over window size
videos do not display

Running Windows 10 Pro / 4k Monitor 
![seer_bug](https://user-images.githubusercontent.com/11148542/28479669-5cea854c-6e12-11e7-8d38-2c37becd543d.jpg)

**Comment by heyyasly** [comment]
I'm a paid user and v 1.4.0 has issues
just installed the free version (0.8.1) and no issues


![seer_free](https://user-images.githubusercontent.com/11148542/28479786-d291085c-6e12-11e7-81b3-4adb7b71a64f.jpg)

**Comment by ccseer** [comment]
HI~~
sorry for this bug.
I am working on per-monitor DPI support now. This issue might be a DPI issue.

Please wait for next updates.
It's coming soon.

**Comment by ccseer** [comment]
Hi~

I am working on the HDPI thing recently. But I don't have a HDPI monitor, would you please help me to test  it? Just check out if it works fine on 4K monitor.

**Comment by ccseer** [comment]
If you do, please email me.

**Comment by ccseer** [comment]
#61
