### ISSUE TITLE
能否隐藏任务栏右下角图标

### ISSUE THREAD

**Issue by Virace** [ccseer/Seer#108]
能否隐藏任务栏右下角图标

**Comment by ccseer** [comment]
能啊. 
下个版本就可以, 已经写完了.

**Comment by ccseer** [comment]
这周末发布.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/28700631-9074be70-7383-11e7-9a16-4ff13a5c00c1.png)

**Comment by Virace** [comment]
屌炸天  赞一个
