### ISSUE TITLE
Better way to determine a valid Spacebar key

### ISSUE THREAD

**Issue by xupefei** [ccseer/Seer#109]
The [GetGUIThreadInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633506(v=vs.85).aspx) API returns `lpgui.flags` and `lpgui.hwndCaret` values, which can be used for determining whether a Spacebar key is being pressed when a cursor is blinking in the target window.
It is more clean and reliable than [these scary `if`s](https://github.com/ccseer/Seer/blob/51b12e9936345afcc11ff48399f9cfc8a45e885c/1.5.0/src/ckeyboardhookcontroler.cpp#L135-L171). This may solve #69, although I haven't tested.

**Comment by ccseer** [comment]
好
晚点试试。

**Comment by ccseer** [comment]
今天试了下，很好使。
谢谢。

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/28903081-8bd41828-7835-11e7-8aa3-57778f1c3a5f.png)


看到你的程序里有一个  Pin 按钮，我还不知道具体是干嘛的。
但我在很早前就打算做一个可能类似的功能，git 上时间是 4/11。 

为了避免误会所以提前告知。
另外你也看了代码，很多人也 fork 了。我可能会在 1.6.0 发布的时候就删掉了。如果你还需要你可以给我发邮件，我再把那一份代码发给你。

**Comment by ccseer** [comment]
有什么问题的话可以邮件直接及时沟通。 如果你愿意的话。

**Comment by xupefei** [comment]
我那个 Pin 和你这功能是一样的 :)
