### ISSUE TITLE
Way to add color management support to photos?

### ISSUE THREAD

**Issue by DantesanR** [ccseer/Seer#110]
I use Seer primarily to sort between images but my images are extremely oversaturated when viewing in Seer. Is it possible to either add color management to Seer or maybe... just use the pre-existing app "Color Managed Photo Viewer" as a plug-in for Seer?

**Comment by ccseer** [comment]
#31

**Comment by ccseer** [comment]
Hi~

thanks for your information. I will take a look at Color Managed Photo Viewer
