### ISSUE TITLE
安装1.4.0后会对游戏造成卡顿

### ISSUE THREAD

**Issue by Kajiura** [ccseer/Seer#111]
之前使用0.8.1免费版，玩overwatch的时候没有问题。
昨天购买了1.4.0版，最小化在system tray，但是玩overwatch画面会经常出现卡顿
退出后游戏恢复正常。。
不知算不算一个bug。。。希望您能看看
谢谢

**Comment by ccseer** [comment]
具体卡顿是指的 网络 ?

**Comment by ccseer** [comment]
还是程序? 

程序在不使用的时候内存占用还好啊..

可能刚用完内容占用还很大，一般等一会内存就会自己掉下去

**Comment by Kajiura** [comment]
内存占用不大，网络也基本没有程序有大的上下行
就是莫明会卡一下，有点像掉帧。。。但是游戏的帧数显示一直稳定在70fps左右
放在后台一个小时左右没使用。进入游戏还是会出现这种掉帧
很奇怪。。
录了一段视频，大概就中间那个机器人的效果。。https://youtu.be/PgsvNJD_970

**Comment by ccseer** [comment]
确实是个 bug. 
我仔细查一下了尽可能在下个版本解决.

5周内应该能发布.

**Comment by Kajiura** [comment]
好的，谢谢啦！
您辛苦。。从mac换过来感觉有这个seer真是太棒啦www

**Comment by ccseer** [comment]
: )

重大改进在 1.6.0

**Comment by ccseer** [comment]
发布了.. 你试试了再告诉我 吧?

**Comment by Kajiura** [comment]
啊好的。。。之前由于工作原因一直在外没及时查看，我过几日闲下来就试试。谢谢谢谢

**Comment by ccseer** [comment]
已经更到 1.7.1 了...

Kajiura <notifications@github.com>于2017年10月12日周四 下午2:22写道：

**Comment by Kajiura** [comment]
😂😂😂抱歉抱歉....昨天晚上试了一下还是...额...卡卡的，虽然现在在国外延迟很高，但是这个卡和网络是一样...唉....等有机会我用朋友电脑试一下，辛苦开发者大大

**Comment by ccseer** [comment]
你用的 1.7.1？

呃。。。。这是个大问题啊
头疼

Kajiura <notifications@github.com>于2017年10月12日周四 下午11:33写道：

**Comment by Kajiura** [comment]
emmm....似乎也没有别人反馈类似的问题...在想是不是个例...等我回国有机会拿朋友电脑试试吧w...反正现在也几乎玩上不上游戏了wwww...

也还请大大抽空琢磨琢磨，辛苦辛苦www

**Comment by Kajiura** [comment]
装了1.8.1问题修复了哈哈哈，辛苦了。话说fix fatal bug不会就是这个吧66666

**Comment by ccseer** [comment]
啊?
不是啊

是 我发布 1.8.0 的时候 忘记替换最后的 exe 文件了, 导致 1.8.0 的安装包文件里面还是 1.7.1 .
蠢死了


如果没问题了 我就关了这个 issue 了, 谢谢谢谢
我要发布 1.9.0 了

**Comment by ccseer** [comment]
你是不是有什么系统变化 ?

**Comment by Kajiura** [comment]
哈哈哈哈哈。。。
系统变化....没有吧....Windows升级到1709？不过12月那会也升级了但还是有问题...显卡驱动？emmmm没

反正目前是解决了，也可能是Windows修复了什么bug吧....

坐等1.9.0哈哈哈哈
要是再出现我再反馈好了www
辛苦辛苦

**Comment by ccseer** [comment]
找到原因了.
已经修复.
三天内发布

抱歉
