### ISSUE TITLE
Problem with ISO file format

### ISSUE THREAD

**Issue by April-BOY** [ccseer/Seer#112]
Seer can not preview files in the ISO file format.The Seer version is 0.8.1

**Comment by ccseer** [comment]
iso 就是 光盘 的那个么?  rar 格式吧

**Comment by April-BOY** [comment]
![snipaste_20170823_161639](https://user-images.githubusercontent.com/19245482/29605719-876aaa10-881e-11e7-81c8-2d69058e66b5.png)
嗯嗯，是光盘的那个格式。按空格预览的时候直接显示的是文件的相关信息。
![snipaste_20170823_161612](https://user-images.githubusercontent.com/19245482/29605712-838aa530-881e-11e7-80da-e364ea5095a2.png)

**Comment by ccseer** [comment]
应该会通过插件实现吧..

但是目前正式版更新到 1.6.0 了... 没法保证插件在老版本上能兼容

**Comment by April-BOY** [comment]
![snipaste_20170823_162230](https://user-images.githubusercontent.com/19245482/29606175-0a5f790e-8820-11e7-8c7f-b556ec57701d.png)



 我以为设置里写的支持相关的格式都已经支持了，原来还不是都实现了。
还有，我想问下，付费版和免费版有什么区别？

**Comment by ccseer** [comment]
设置里有的都支持了啊...   那个 iso 是多媒体格式... 你的 iso 是 压缩包 不一样


更新了好多版了... 你可以下载一个 1.6.0 试试看啊

April_BOY <notifications@github.com>于2017年8月23日周三 下午4:29写道：

**Comment by April-BOY** [comment]
嗯嗯，确实是我理解错了。我那个是压缩包。

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/57563584-22761080-73d2-11e9-9b82-12985bbeb44c.png)


以支持了
Seer - 2.2.0
