### ISSUE TITLE
Seer opening and closing images multiple times on Photoshop startup (v1.6)

### ISSUE THREAD

**Issue by JoachimBarrum** [ccseer/Seer#115]
I'm still experiencing Seer flashing/open closing of an image under Photoshop startup in Seer v.1.6. Just thought I'd mention it since the bug was closed a while back.

**Comment by ccseer** [comment]
Got it.

I will do more tests.

**Comment by ccseer** [comment]
btw, I just released 1.6.1 with a few bugfixes.

**Comment by JoachimBarrum** [comment]
thanks :+1:

**Comment by ccseer** [comment]
fixed in 1.9.0
