### ISSUE TITLE
in app update not working 1.4.0 > 1.6.1

### ISSUE THREAD

**Issue by pafontai** [ccseer/Seer#116]
Hi,
I was in version 1.4.0 (activated licence). I launched an "in app" update to version 1.6.1.
The process run smoothly, without an error.
Finally, the seer.exe file into "C:\Program Files (x86)\Seer" is not updated. When seer relaunches, the version remains "1.4.0".

To bypass this unexpected behaviour, I installed the updated version into "C:\Program Files (x86)\Seer1.6.1"

my OS : windows 7 pro 64bits SP1
language : french

can I uninstall the 1.4.0 version without loosing my licence ?

Thank you
Patrice

**Comment by ccseer** [comment]
anytime you lost your license you can just email me to get a new one

**Comment by ccseer** [comment]
You clicked the menu item  --  "check for updates" ?

**Comment by ccseer** [comment]
what next?

it should show a window to check if there is an updates
if it does have a new version, it will download it and requires you to click to install the updates

**Comment by pafontai** [comment]
Seer checks for updates automatically. I accepted the update. The download and installation ran well... but at the end, the binary image on disk is not updated ! It's weird.

**Comment by ccseer** [comment]
That might be a setup file issue.

**Comment by ccseer** [comment]
fixed in 1.7.0
