### ISSUE TITLE
疑似有木马

### ISSUE THREAD

**Issue by VeryLazyBoy** [ccseer/Seer#118]
![image](https://user-images.githubusercontent.com/18899212/30050684-e7130880-9251-11e7-8e60-193f3719952d.png)

**Comment by ccseer** [comment]
误报吧...

**Comment by ccseer** [comment]
![_20170905155740](https://user-images.githubusercontent.com/15963166/30050990-f83ae654-9252-11e7-9c50-0a89c0377f0f.jpg)

**Comment by ccseer** [comment]
这里是 国外网站的 检测

http://www.softpedia.com/get/Multimedia/Graphic/Graphic-Viewers/Seer-Chan.shtml

**Comment by ccseer** [comment]
你用的哪个版本?

**Comment by ccseer** [comment]
能否帮忙点一个   *误报反馈*   啊~~




![image](https://user-images.githubusercontent.com/15963166/30056782-a677d426-9266-11e7-81f4-67fc6318de18.png)

**Comment by ccseer** [comment]
之前还被它的 360软件管家 放首页推荐了 好久....

不知道现在啥情况...

**Comment by ccseer** [comment]
查了下

![image](https://user-images.githubusercontent.com/15963166/30056857-f8d9d11a-9266-11e7-88f3-db0fd01e63ea.png)


程序要创建 键盘钩子 监控 空格按键... 连接网络也是程序检查更新必须的.. settings 也是写的注册表....

应该是误报了...

**Comment by VeryLazyBoy** [comment]
原来是这样。之前的版本没有问题，只是最新版有问题。。。
