### ISSUE TITLE
Incompatible with SavePictureAs AHK

### ISSUE THREAD

**Issue by TacosAreYum** [ccseer/Seer#12]
SavePictureAs is an AutoHotKey script that allows one to save an image with hotkeys. When Seer is open, SavePictureAs will save the wrong filename, using `;` in the save path instead of `:`

Tested for 30 minutes and can replicate easily. 

Video demonstration performing the hotkey (which was ALT+O): https://vid.me/1wR8
SavePictureAs SourceForge: https://sourceforge.net/projects/savepictureas/?source=navbar

**Comment by ccseer** [comment]
Hello~

I'm not sure why would that happened.
Seer has "ALT+O" shortcut, but it only works when it opened. So I don't think it will be fixed by change that shortcut in Settings.

I would take a look into this.
Thanks

**Comment by TacosAreYum** [comment]
Ah, thank you for looking into it. I just want to clarify that ALT+O isn't the only hotkey causing this problem.

**Comment by ccseer** [comment]
#23
