### ISSUE TITLE
Issues with Photoshop CC 2017

### ISSUE THREAD

**Issue by KLOFER** [ccseer/Seer#120]
I have noticed that i can't use my cursor on some tools in photoshop, like adjusting crop and moving the photo. Seems like there is a problem with click-holding and draging in Photoshop when using Seer.
I have the 0.8.0.0 version of Seer. I am not sure if this version is the latest one(?) Downloaded it from https://sourceforge.net/projects/ccseer/

**Comment by ccseer** [comment]
Hi~
0.8.1 is the last free version.

the last version is 1.6.1.
www.1218.io
