### ISSUE TITLE
Update 1.61 doesn't seem to play with Directory Opus

### ISSUE THREAD

**Issue by vze26m98** [ccseer/Seer#121]
Up to date Windows 10 on both my machines, Asus Strix laptop and P10WS desktop. Latest Directory Pro 12, Licensed Seer 1,61. Can't seem to "quicklook" PDFs, JPGs, PNGs, WAVs or MP3s. Updating the location setting for Dopus does nothing. Reverting to Seer 1.4.0 restores Seer's quicklook features.

**Comment by ccseer** [comment]
would you please show me your "Settings - Advanced" page screenshot ?

**Comment by ccseer** [comment]
Hi~

a restart for Windows  should solve this.

**Comment by vze26m98** [comment]
It remains to be seen. The desktop I have 1.61. installed on is used for audio work only, and gets shut down and restarted every day. (This because the inboard and outboard audio equipment and drivers don’t like sleep mode.) Surely over the couple of weeks since 1.61 was installed, the many restarts would have cured the trouble if it was that simple?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by vze26m98** [comment]
Turns out I was still on Seer 1.6.0. Upgrade to 1.6.1 fixed the issue.

Thanks, Charles

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
