### ISSUE TITLE
Seer update gets confused about downloads

### ISSUE THREAD

**Issue by vze26m98** [ccseer/Seer#122]
Latest Win10 Pro on Asus Strix laptop. Update from 1.4.0 to 1.6.1.

Update stalled.
Quit Seer.
Launched Seer
Activated update through Seer menu, download started.
Seer alerts me that an update is available.
Download in progress disappears.
Entire Seer process stalls whether I select Update or Cancel.
If I wait for Seer to alert me to the update, it catches up to previous progress, and then stalls, both download and process.
Had to download Seer 1.6.1 from Github and manually install, which was successful, although quicklook seems not to work with Directory Opus in 1.6.1.

**Comment by ccseer** [comment]
#116
