### ISSUE TITLE
Seer installed files disappears when installed on Windows 10

### ISSUE THREAD

**Issue by stumblesally** [ccseer/Seer#123]
I've downloaded and tried to install Seer (Seer-0.8.1.exe) three times on Windows 10 and each time the program creates a shortcut on the desktop, but it's not linked to anything when I click on it.  I've set it to launch upon install and I've also tried rebooting after installs.  When I search for the Seer folder that was supposed to install on C:\Program Files (x86)\ there is nothing there.  I can find it under: C:\Users\NAME\AppData\Local\VirtualStore\Program Fiels (x86)\ but there is no application to run in the Seer folder.  I'd love to be able to use the functionality of Seer, but I'm not having any luck.

**Comment by ccseer** [comment]
Can you try to install Seer to a place without Administrator permission?

stumblesally <notifications@github.com>于2017年9月19日周二 下午11:07写道：

**Comment by stumblesally** [comment]
That seemed to fix it.  Thanks!  I've not had that problem with other installs, but it's something I'll keep in mind.

**Comment by ccseer** [comment]
Cheers.
