### ISSUE TITLE
preview when attaching

### ISSUE THREAD

**Issue by momoche** [ccseer/Seer#124]
hi seer doesn't seem to work when attaching files to emails (on gmail)- such handy feature on mac when you want to make sure to send the right file!

**Comment by ccseer** [comment]
what is the suffix  for this type? can you send me a sample file?

**Comment by momoche** [comment]
It was a PDF or JPEG
Is it supposed to work while attaching?
Thanks

**Comment by ccseer** [comment]
would you please send me a sample file?

**Comment by ccseer** [comment]
Do you mean preview when you are trying to select a file from "open file dialog"?

**Comment by momoche** [comment]
I mean attach document on gmail- opens a file explorer- then the preview
doesn't work there

**Comment by ccseer** [comment]
Yes. I got you.

It will be supported in next version. 1.7.0.

**Comment by ccseer** [comment]
#90

**Comment by ccseer** [comment]
please update to 1.7.0
