### ISSUE TITLE
PDF previews don't show images

### ISSUE THREAD

**Issue by temujinghis** [ccseer/Seer#125]
Upgraded to 1.61 and now when I preview PDFs with Seer, I can't any images in the PDF. Text seems to be fine.

**Comment by ccseer** [comment]
#114

**Comment by ccseer** [comment]
Hi I am working on a new pdf module.
It's about to be done.

**Comment by temujinghis** [comment]
Thanks for the update!

**Comment by ccseer** [comment]
please update to 1.7.0
