### ISSUE TITLE
PDF created through AutoCAD shows up blank

### ISSUE THREAD

**Issue by zbhoy** [ccseer/Seer#126]
Any PDF i have created through AutoCAD shows up blank in SEER

**Comment by ccseer** [comment]
#114

**Comment by ccseer** [comment]
New PDF module has done.

Will be released in next version.

**Comment by zbhoy** [comment]
Thanks! I didn't know if that was same cause or not. Sorry.

**Comment by ccseer** [comment]
please update to 1.7.0
