### ISSUE TITLE
.mp4 files stop playing after one sec

### ISSUE THREAD

**Issue by dannyolsen** [ccseer/Seer#127]
Hi! Great job with this seer :)

When i preview video files, for sure i have a problem with .mp4 files. They stop playing after 1 sec. I can how ever make it play again, by moving the slider with the mouse.. I hope this can be fixed - great job however!

**Comment by ccseer** [comment]
what version?

**Comment by dannyolsen** [comment]
v0.8.1 :)

Med venlig hilsen

Danny Chris Olsen

**Comment by ccseer** [comment]
Hi~
I just tested on v1.6.1, it works fine.
I'm not working on the free version any more.

I'm sorry.

Best wishes.

**Comment by dannyolsen** [comment]
ok - good to know :) thanks..


Med venlig hilsen

Danny Chris Olsen
