### ISSUE TITLE
The procedure entry point error in 1.7.0

### ISSUE THREAD

**Issue by esidav** [ccseer/Seer#129]
In version 1.7.0, I saw The procedure entry point error for KERNEL32.DLL, GetPackageFamilyName.
In version 1.6.1, there is no error.
OS: Windows7 x64 SP1.

**Comment by ccseer** [comment]
GetPackageFamilyName is for  UWP version。

I was trying to submit it to the Windows Store.

this is Seer-1.6.1.
https://1drv.ms/u/s!AgtA1EcmfJYVjrk5bmK8VgOj2R9vhQ

I will release a new version tomorrow

**Comment by ccseer** [comment]
Sorry.

**Comment by ccseer** [comment]
uninstall your old version. Download from 1218.io

**Comment by ccseer** [comment]
I have released Seer-1.7.1.

**Comment by ccseer** [comment]
Thx for your report, again.

**Comment by esidav** [comment]
Thank you for quick fix!

**Comment by ccseer** [comment]
Did you install it?

Is it working well?

esidav <notifications@github.com>于2017年10月11日周三 下午10:34写道：

**Comment by esidav** [comment]
Yes, totally works well :)
