### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by yogiee** [ccseer/Seer#13]
I tried everything to get it to work on my Windows 10 PC and so far no luck. Tried re-installing, rebooting and tweaking the settings, but it just doesn't seem to work. Worked on different machine without hitch though. Both machines are running Windows 10 Pro with all latest updates installed, both machines are running dual monitors.

**Comment by ccseer** [comment]
it doesn't work in Desktop or Explore or both?

**Comment by yogiee** [comment]
Both, tried in explorer, as well as putting few files on desktop. Neither worked.

**Comment by ccseer** [comment]
use cmd  to start Seer.
command line:
Seer.exe log

it will generate a txt file named seer.log

send it to me.

btw, what version of Seer do you have?

**Comment by yogiee** [comment]
I'm using Seer 0.7.2

Please find attached log file

[seer.log.txt](https://github.com/ccseer/Seer/files/204383/seer.log.txt)

**Comment by ccseer** [comment]
You need to try to trigger a file ( I know it will fail, and nothing happen ), then I can see where goes wrong.

Would you please do it again?
Oh, delete the Seer.log file first.

**Comment by yogiee** [comment]
I'm not sure if it's even triggering, cause I check the below file and it doesn't seem to logging any interaction.

[seer.log.txt](https://github.com/ccseer/Seer/files/204851/seer.log.txt)

**Comment by ccseer** [comment]
How about you install it in a folder where doesn't required administrator permission?

**Comment by yogiee** [comment]
Will try doing that.

**Comment by yogiee** [comment]
So I completely uninstalled it. Even removed the registry entries from Windows registry. Installed in a different folder than C drive. But the same thing. I ran the log, and it seems it's not triggering the app still. I tried opening an image manually with the app (via context menu "open with..." command) and it works just fine, but the keyboard trigger (space key) for some reason is not being captured at all.

Adding latest log below.

[seer.log.txt](https://github.com/ccseer/Seer/files/205991/seer.log.txt)

**Comment by ccseer** [comment]
when seer opened, it can work like:  Seer.exe filepath

> loading cost  79 "Z:/Wallpapers/Wallpapers 2014/Abstract/wallpaper-428301.png" 2 5

According to this msg, it seems work fine.  Loading time cost is 79ms.

---

Do you have any security software?

**Comment by yogiee** [comment]
Nevermind figured it out.

Synergy (keyboard/mouse sharing app) was causing the missed keyboard triggers for Seer. Exited that it worked beautifully as it should. I'm so sorry about the trouble, I should've tried that first before bugging you. Now I feel stupid. -_-

**Comment by ccseer** [comment]
It's ok..

Hope you like Seer. 

: )
