### ISSUE TITLE
Preview needs space key to be pressed and hold

### ISSUE THREAD

**Issue by corazzam** [ccseer/Seer#130]
Dear developer, I am experiencing an issue that, for what I was able to find online, has not happened before. I am using Windows 10 (let me know if you need more details - I have a high specs system). Basically the issue is that, when I press space to trigger the preview of e.g. an image, I see the image appearing and, unless I keep the space key pressed, disappear immediately. Moreover, when I keep space pressed, the image fades out with time (2-3 seconds). The same happens with videos and documents. At first I thought  it was actually a feature, but then from reading the description of Seer, it seems more like a bug (and it is indeed an annoying one). Let me know your thoughts. Great job with this software!
I took a video of the bug: https://youtu.be/V9H24D4IoFI

**Comment by ccseer** [comment]
What version are you using?

**Comment by ccseer** [comment]
Is it same when you triggering from the desktop?

Would you please close other apps and try again

**Comment by corazzam** [comment]
I had already tried to close most of the programs (I am using version 0.8.1) although I didn't close Holdkey ( http://www.holdkey.eu/ ). It turns out that it was Holdkey to create the conflict. However, I need to be able to use Holdkey as well. Any idea of why there is this conflict?

**Comment by corazzam** [comment]
Thanks for the quick reply!

**Comment by ccseer** [comment]
I'm not sure. But I think there is a settings in "Keyboard" you can use

corazzam <notifications@github.com>于2017年10月15日周日 下午10:20写道：

**Comment by corazzam** [comment]
Yes, if I choose for example shift+space they both work. Not 100 % what I want, but it's a fair workaround. Thank you!

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/31592482-37ec266e-b25b-11e7-8de7-02943d915ddf.png)
