### ISSUE TITLE
Seer Pro 1.7.1 doesn't work through network

### ISSUE THREAD

**Issue by adrian3d** [ccseer/Seer#131]
Hey,

I can't open files with Seer Pro 1.7.1 in a network drive like a NAS. It's works with the free version, though.

Thanks.

**Comment by ccseer** [comment]
did you try to reboot your PC?

**Comment by adrian3d** [comment]
No. I'm going to try now and tell you.

**Comment by ccseer** [comment]
#78

**Comment by adrian3d** [comment]
Great ! It's works ! Thanks !
