### ISSUE TITLE
Something unexpected happened. Seer will start again

### ISSUE THREAD

**Issue by chibuhu** [ccseer/Seer#132]
视频时没图像有声音弹出Something unexpected happened.
Seer will start again.提示。win7x64
同一系统，用免费0.81是好的

**Comment by ccseer** [comment]
0.8.1 到 1.0.0 的时候视频模块升级了很多，速度和内容占用都有很大的改进

如果是单个视频文件的话，可以把那个文件发给我测试一下

**Comment by ccseer** [comment]
你用的是 1.7.1？？

**Comment by chibuhu** [comment]
一直在用0.81，用的挺好，昨天无意中看到有收费的1.71，下载安装试了下，结果只要是视频就会这样提示，有声音没图像，而且点了错误提示软件就自动退出了

**Comment by ccseer** [comment]
把那个文件发给我测试一下吧....

**Comment by ccseer** [comment]
免费版 还是  cpu 渲染的方式...  非常慢 和 耗cpu

后来换了 gpu 渲染后要用到 opengl。。 可能就和显卡啥的有关了

**Comment by ccseer** [comment]
你是说 只要是 视频 都会这样???

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/31812815-cf395330-b5b6-11e7-809f-cf0f7b89911c.png)

**Comment by chibuhu** [comment]
显卡驱动整个卸载了重新装了还是一样，应该不是显卡问题

**Comment by ccseer** [comment]
你所有的 视频文件都这样??? 不会吧~!?

**Comment by chibuhu** [comment]
是的，都一样

**Comment by chibuhu** [comment]
其他都可以包括word，execl、图片。就视频不行

**Comment by ccseer** [comment]
: (

好吧...还没有人报过这样的 bug 
我晚点查一下

你试一下 老版本 看看 ?
https://bitbucket.org/coooorey/seer-download/downloads/Seer-1.4.0.exe

**Comment by chibuhu** [comment]
一样，就0.81是好的，打开速度非常快

**Comment by ccseer** [comment]
😂😂没招了

估计你连1.0.0也是这样

**Comment by chibuhu** [comment]
应该是，估计系统里那里有问题，但又不想重装，只好用免费的了，谢谢

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/1416893/Seer.zip)

**Comment by ccseer** [comment]
这个使用CPU 渲染。和 免费版的一样，不确定你那能不能使。

如果有机器不能使用 GPU 的话，我会在下个版本加个 option 提供选择。

**Comment by ccseer** [comment]
#138 
解决了
谢谢
🙏
