### ISSUE TITLE
在文件夹的预览窗口里展开好几级子文件夹，但是实际上只能打开第二级

### ISSUE THREAD

**Issue by iamfun** [ccseer/Seer#133]
另外一点不知道是否可行！
如果在文件夹的预览窗口使用文件夹级联展开子文件夹（不用单击，鼠标悬停就可展开），迅速找到深层的文件夹或文件，那效率就非常高了

**Comment by ccseer** [comment]
标题说的啥意思

打开第二级 是什么意思啊？？

为了速度，程序都是在点击后才开始加载 子文件夹 的内容的，鼠标悬停操作太快了吧

**Comment by iamfun** [comment]
就是在文件夹的预览窗口展开多级目录，无论鼠标双击哪一级目录，实际上打开的都是第二级目录。当然，按Alt+O快捷键是可以打开选中文件的！

**Comment by ccseer** [comment]
双击的逻辑是  使用默认程序打开当前文件，不同的文件不同的默认程序。
这里的当前文件是文件夹，所以用 explorer 打开就是第二级了。
这个是程序主要逻辑之一，没法改。

我一般都是把这个“双击使用默认程序打开”的选项关了使用的。





iamfun <notifications@github.com>于2017年10月28日周六 下午10:57写道：

**Comment by ccseer** [comment]
谢谢反馈
: )

**Comment by ccseer** [comment]
仔细想了一下，我再考虑考虑啊。
确实是个问题
