### ISSUE TITLE
APPCRASH: Seer.exe

### ISSUE THREAD

**Issue by onfuryhs** [ccseer/Seer#134]
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Seer.exe
  应用程序版本:	1.7.1.0
  应用程序时间戳:	59ddf10a
  故障模块名称:	ucrtbase.DLL
  故障模块版本:	10.0.15063.137
  故障模块时间戳:	e880f7dc
  异常代码:	40000015
  异常偏移:	000a544a
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	536d
  其他信息 2:	536d0d0d7a87812c9fb38abc6af99323
  其他信息 3:	995a
  其他信息 4:	995ab4253c7bd1942fd113051b12c2ad

查看任何格式、码率的视频及音频文件后发生。

**Comment by ccseer** [comment]
部分机器会出现这个情况.   第三方库的原因.

**Comment by ccseer** [comment]
你那边方便测试吗.. 可能需要替换 dll 再看看能否成功

**Comment by onfuryhs** [comment]
方便

**Comment by ccseer** [comment]
好
谢谢

我这边播放正常
我先问下库作者怎么解决，搞定了再回来

**Comment by ccseer** [comment]
你是刚开始用 Seer 还是老用户？

如果是以付费用户，你前面使用的版本是哪个，运行正常吗？ 正常的话我把旧版本的 Exe 发给你先用着

**Comment by onfuryhs** [comment]
刚开始用 Seer

**Comment by ccseer** [comment]
好吧
那要用的话只能 先用免费版了。0.8.1

新版本在一部分win7上确实有问题

**Comment by ccseer** [comment]
#138   解决了

🙏
