### ISSUE TITLE
seer与listary pro冲突

### ISSUE THREAD

**Issue by yebyte** [ccseer/Seer#136]
listary pro和seer的功能没办法同时满足

**Comment by yebyte** [comment]
totalcommander里也类似，能不能设置一个新的调用方式，或者让seer的优先级高一些，快捷键不要被占用

**Comment by ccseer** [comment]
怎么冲突了

用管理员运行 Seer ？
你用的什么 Seer 版本

**Comment by yebyte** [comment]
1.7.1的付费用户用管理员运行，不能解决，不知道作者你是不是listary的用户，文件打开对话框里listary即时搜索会占用空格，ctrl

**Comment by ccseer** [comment]
以前有人遇到过说在  listary 里搜索输入的时候也会触发，后来我装了一个解决了这个问题。至于冲突的问题可能需要切换快捷键。要么切换 对方软件的，要么去 配置-键盘 里加修辞按键

**Comment by ccseer** [comment]
如果解决了我就 close 啦？

**Comment by yebyte** [comment]
我保证了两者的快捷键没有冲突（listary里没有ctrl seer里设置ctrl+space）但还是不行，退出listary后 seer功能就正常了，是不是listary更新后

**Comment by ccseer** [comment]
冲突时指的什么冲突？

**Comment by yebyte** [comment]
打开listary 我文件打开对话框里选个对象 space 调用不了seer

**Comment by ccseer** [comment]
呃。。。
没错，这就是我说上次解决的问题。

因为你在 listary 里输入的时候有时候输入中文要按空格，就会触发 Seer。 这不是预期结果。

所以现在的处理方式就是，只要 listary 时显示状态就不处理触发。

**Comment by yebyte** [comment]
但ctrl+space也不行 这有点伤及无辜了把

**Comment by yebyte** [comment]
space不判定触发，加了ctrl不就避免了时中文输入的情况了吗，单纯显示就不处理 使用起来很不方便，因为listary没法隐藏，只能禁用，就这种情况下。

**Comment by ccseer** [comment]
ok。了解了。 
我过段时间试下。

最近在改 PinStack

**Comment by yebyte** [comment]
我想应该是作者你这个处理逻辑有点粗暴了，应该很好解决，第三方文件管理器的支持希望也能跟上，很期待pinstack有更好的表现。

**Comment by ccseer** [comment]
要不要试下?

**Comment by ccseer** [comment]
fixed in 1.8.0

**Comment by ccseer** [comment]
https://1drv.ms/u/s!AgtA1EcmfJYVkIA5dvJJw5uGrgwZ0Q

**Comment by ccseer** [comment]
这个是修复了的. 备份下你原来的 Seer.exe  , 把这个 文件放到执行目录下运行就可以了.

应该解决了

**Comment by ccseer** [comment]
好了。

我发布了 1.8.0

可以直接更新了
