### ISSUE TITLE
Remember the size of the preview window (Win 10)

### ISSUE THREAD

**Issue by mrbon1** [ccseer/Seer#137]
Please add the ability to remember the size of the window for the duration of the program. Very good program. But this function is very lacking. Thanks!

**Comment by ccseer** [comment]
Settings - advancwd - remember the size of the window

mrbon1 <notifications@github.com>于2017年11月12日周日 下午2:07写道：

**Comment by ccseer** [comment]
![361cf8e8abea6a8a72cbcb05f2c3aaab](https://user-images.githubusercontent.com/15963166/32716167-f3500e30-c88f-11e7-9bd6-85cb66a0ec60.png)
