### ISSUE TITLE
seer play audio files in slow motion and stops working

### ISSUE THREAD

**Issue by bassemkamal** [ccseer/Seer#138]

**Comment by bassemkamal** [comment]
seer play audio files in slow motion and stops working once i switch to another audio file
these errors appears after i entered my license for version 1.7.1

**Comment by ccseer** [comment]
For a few win 7 system, it happens when previewing the media file.

It will be fixed in next version.
Do you mind if I contact you to check if it works when I'm working on it?

**Comment by bassemkamal** [comment]
no problem,,,you are so welcome,,contact me any time and i will tell you the result

**Comment by bassemkamal** [comment]
by the way,,,i uninstalled the 1.7.1 version and i reinstall the free 0.8 version and it works great in fast audio media preview and fast audio files switching

**Comment by ccseer** [comment]
..... I am so sorry.

**Comment by bassemkamal** [comment]
no problem,,,,sure you gonna fix it in the coming versions,,,i trust you :)

**Comment by ccseer** [comment]
https://1drv.ms/u/s!AgtA1EcmfJYVj7hrvZ1BhMs13g5iow   would you please download this and try to check if it works?

**Comment by ccseer** [comment]
if the last one doesn't work, try this.

https://1drv.ms/u/s!AgtA1EcmfJYVj7hszex9Soq7guC9iQ  


Thank you very much

**Comment by bassemkamal** [comment]
"Seer_media_crash" versions have the same problem of slow motion audio and stopped
![capture](https://user-images.githubusercontent.com/33782702/33034910-02fc450e-ce32-11e7-9585-f576c15b6697.JPG)

and the "Seer_media_crash_approach_2" version give me that error
![capture 2](https://user-images.githubusercontent.com/33782702/33034949-202caf24-ce32-11e7-85e1-407a997f98cf.JPG)

**Comment by ccseer** [comment]
https://1drv.ms/u/s!AgtA1EcmfJYVj7hwIZQY0BgggTukFQ

My bad.
I copied the wrong openAL32.dll.

this time it should work.

**Comment by bassemkamal** [comment]
"Seer_media_fix_openal32" version have the same problem of slow motion audio and stopped
![capture 3](https://user-images.githubusercontent.com/33782702/33089118-5ee1c04e-cef8-11e7-8f33-16a319f47acd.JPG)

**Comment by ccseer** [comment]
OK

I think it might be a driver problem.
I will do more review about it.

**Comment by ccseer** [comment]
https://1drv.ms/u/s!AgtA1EcmfJYVj913SkqJN7xlH71HOQ

run **Seer.exe** to check if it works this time 
If it doesn't, run **Player.exe**. open the file which makes Seer crash. It will generate a **log-Player.txt** whether the Player crashes, please send this log file back.

**Comment by bassemkamal** [comment]
this time seer plays the file in "slow motion only" and it didn't crash,,,and once i run "Player.exe" it shows this error 
![player error](https://user-images.githubusercontent.com/33782702/33486094-7c3332ca-d6b1-11e7-8734-932437851f42.JPG)

and here is a sample of audio files libraries that seer plays it wrong
http://ge.tt/6GypUYn2

**Comment by ccseer** [comment]
Great.
Thank you very much.

Do you accept the result?

I can only test the files next week.
I will let you know the result.

**Comment by bassemkamal** [comment]
waiting a normal result from you next week

**Comment by ccseer** [comment]
https://1drv.ms/u/s!AgtA1EcmfJYVkIBNB4-TSuiUF-zbBA  

hi

this is Seer-1.8.0

please check if it works

**Comment by bassemkamal** [comment]
its working great,,,,great job bro,,,you made it,,,thanks

**Comment by ccseer** [comment]
great

thanks for your patience

**Comment by ccseer** [comment]
I just released 1.8.0

: )

Thanks again

**Comment by ccseer** [comment]
Hi～

have you updated to Seer-1.8.1?

Would you please tell me if this version works fine?

**Comment by bassemkamal** [comment]
yes i did the update of version 1.8.1 and it works fine,,but still in the about page its written 1.7.1 version

**Comment by ccseer** [comment]
Would you please install it again?
1218.io/seer/dl

I just released 1.8.1 yesterday to fix the “1.7.1” issue.

bassemkamal <notifications@github.com>于2017年12月19日周二 下午8:17写道：

**Comment by bassemkamal** [comment]
i just installed it again,,,its working great,,,,
great job bro,,,keep it up
thanks

**Comment by bassemkamal** [comment]
after restarting my PC the v1.8.1 ask me to buy a license and after i entered my license number,,,it says Invalid License,,what can i do ?

**Comment by bassemkamal** [comment]
i restart it again and i try again,,and it accept my license,,,,maybe its a bug or unusual error
