### ISSUE TITLE
AVI files not working 

### ISSUE THREAD

**Issue by annoyingfan** [ccseer/Seer#139]
Saw a closed bug report for a previous version #85. But I'm on Windows 10 with Seer version 0.8.1 and if I try to preview an .avi file, seer tries to preview it, but it crashes and I'm unable to preview any files at all until I restart Seer.

**Comment by ccseer** [comment]
Would you provide the link for “closed bug report for a previous version”?
And the previous version is 1.6.1.

The free version is quite stable. It works fine I think.

**Comment by ccseer** [comment]
Hi~

the  #85  is a problem of the official version, and the problem have been truly solved. It's has nothing to do with the 0.8.1, they use different backend (CPU rendering and GPU rendering).

**Comment by ccseer** [comment]
the things is that I'm not developing the free version any more. 
Sorry about that.
