### ISSUE TITLE
预览窗口没有焦点

### ISSUE THREAD

**Issue by fireattack** [ccseer/Seer#14]
一般的预览倒是无所谓，但是预览PDF文档之类的时候无法直接用滚轮滚动，还得先点一下，比较麻烦

**Comment by ccseer** [comment]
有全局快捷键...  设置 - 键盘 - common -> focus

预览窗口没有焦点为了 让你使用方向键可以继续预览别的

另外 windows 10 是可以去 Scroll 没有焦点的窗口的.

**Comment by fireattack** [comment]
用快捷键和直接点一下差不多麻烦了吧？

我是Win7，是滚不了的

**Comment by ccseer** [comment]
但是  使用方向键 去 切换文件真的很重要啊。。

**Comment by fireattack** [comment]
你说的有道理，按你觉得最合理的方式实现吧。

不过能不能在你这边做到无焦点捕捉鼠标滚轮动作？又或者有个选项默认带焦点？倒不是什么大事儿就是了

**Comment by ccseer** [comment]
我可以试试   无焦点捕捉鼠标滚轮动作

但优先级不会太高

**Comment by ccseer** [comment]
谢谢啊~~~

这个应做起来也不难..不过得考虑下是不是有必要
