### ISSUE TITLE
Better RTF Support

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ccseer/Seer#140]
Currently, if I use seer to preview a .rtf file, it has lots of unnecessary extra characters that I assume have something to do with formatting. 

A file that looks like this in WordPad:
"- bleed and poison on broken sword
- give crescent sword all physical damage
- pure magic damage on dark drift
- luck scaling on chaos blade
- HP/FP on crits"
looks like this in seer:
"{\rtf1\ansi\ansicpg1252\deff0\nouicompat{\fonttbl{\f0\fswiss\fcharset0 Helvetica;}}
{\*\generator Riched20 10.0.15063}\viewkind4\uc1 
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\f0\fs24\lang9 - bleed and poison on broken sword\par
- give crescent sword all physical damage\par
- pure magic damage on dark drift\par
- luck scaling on chaos blade\par
- HP/FP on crits\par
}"

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/33355705-8ecb79c0-d4f3-11e7-8b6d-f22aa091eda2.png)



http://1218.io/seer/plug-in.html
