### ISSUE TITLE
Next File While Seer is Focused

### ISSUE THREAD

**Issue by supersaiyansubtlety** [ccseer/Seer#141]
It would be convenient to be able to have keyboard shortcuts to move to the next file in file explorer even when the Seer preview window is focused. For example, if I click on the Seer preview so I can use forward and backward arrow to seek forward and back in a video, I would like to be able to use the up and down arrows to switch to the next and previous file in File Explorer. In a list view it would of course go up and down, in a grid view it would go left to right in a row and then move to the next row when it reaches the end of a row.

**Comment by ccseer** [comment]
there is a shortcut to switch the focus back to the previous app, that might help

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/33355931-9b8b378a-d4f4-11e7-94c4-336387f1cb34.png)

**Comment by supersaiyansubtlety** [comment]
That doesn't solve the problem, as I'd have to constantly be switching the focus back and forth between seer and File Explorer.

**Comment by supersaiyansubtlety** [comment]
Please reopen

**Comment by ccseer** [comment]
Hi~

Seer works like this since the first version. I think it's the nature behavior logic.

: )

**Comment by supersaiyansubtlety** [comment]
Could you please restate your previous comment using proper grammar so that I may understand what you mean?

**Comment by ccseer** [comment]
Seer worked this way from the first version. I think this is the basic logic of interaction.

😢
