### ISSUE TITLE
HTML preview support

### ISSUE THREAD

**Issue by mingyee2** [ccseer/Seer#142]
Many other viewers have HTML rendering support, and it seems quite useful. Would it be easy to implement this?

**Comment by ccseer** [comment]
Are you using 0.8.1?
This feature had added into Seer since Seer-1.0.0


mingyee2 <notifications@github.com>于2017年12月5日周二 下午8:28写道：

**Comment by ccseer** [comment]
http://1218.io

**Comment by ccseer** [comment]
http://1218.io/seer/release-note.html

1.1.0

**Comment by mingyee2** [comment]
Ah, yeah, thanks. I thought that the downloads were on the SourceForge, but I guess they have not been for some time. Thanks!
