### ISSUE TITLE
something unexpected happened

### ISSUE THREAD

**Issue by HermanZYZ** [ccseer/Seer#143]
1.7.1：预览一个pdf，弹出一个蓝色圆圈，点击，3天试用，然后报错，OK和cancel都没用

**Comment by ccseer** [comment]
报错？

报啥错？

正常逻辑是这样的，就是试用到期后有个蓝色圆圈。和 PDF 没关系。
右下角有 tray icon 可以退出或者激活啥的。

HermanZYZ <notifications@github.com>于2017年12月5日周二 下午10:05写道：

**Comment by HermanZYZ** [comment]
我是刚刚才下载第一次用的，然后空格预览的时候，弹出一个蓝色圆圈嘛，我就顺手点击一下，以为是个试用提醒，然后就有一个弹窗，“something unexpected happened”，点击OK和Cancel都没用，还是不断弹出来。我系统是Windows 10 1709.现在看issue看到说用0.81没问题，然后下载安装能用。预览的时候大概占6%CPU

**Comment by ccseer** [comment]
呃。。。。。好的。。

估计是试用的窗口有啥问题。
试用期第一次按空格是会出现一个 提示的。

我明天看一下。

谢谢反馈

HermanZYZ <notifications@github.com>于2017年12月5日周二 下午10:25写道：

**Comment by ccseer** [comment]
fixed in 1.8.2 or 1.9.0
