### ISSUE TITLE
Frequent network activity with auto check for updates OFF

### ISSUE THREAD

**Issue by menace97** [ccseer/Seer#145]
Seer Version 0.8.0.0
Automatically check for updates OFF

Observed what seemed to be Seer attempting to connect every 30-60 seconds (approximately) by looking at my firewall information/logs after noticing slowdown of internet connectivity after option was set as described:

Process ID: 4620
Name: Seer
Program: C:\program files (x86)\seer\seer.exe
Source Port: 1141
Destination Address: 151.101.0.133
Destination Port: 443

I'm very new to using Seer - and I absolutely love it! Thanks very much Corey. I'm not sure if this is due to me doing something wrong or not, but I thought I would send some information regarding what I observed. If I need to simply keep automatic updates ON, that is no problem... I just usually turn off auto updates and prefer to do it manually.

Cheers!
~menace97

**Comment by ccseer** [comment]
Hi~

it‘s a bug.

I am still looking into this.
The thing is that I can't reproduce it.

Please update to v0.8.1
There is a fatal bug in v0.8.0. 
And the free version is not updating anymore. 
Sorry.

**Comment by menace97** [comment]
Thanks so much for looking into this.

If there is anything I can do (or provide you with my system information) to help with reproducing it, let me know.

I will be sure to update to 0.8.1

Thanks! :)

**Comment by ccseer** [comment]
fixed in 1.9.0
