### ISSUE TITLE
文件名为Makefile与makefile不能预览

### ISSUE THREAD

**Issue by llxwj** [ccseer/Seer#146]

**Comment by ccseer** [comment]
可以吧

你用的免费版？

新版本是可以的

llxwj <notifications@github.com>于2017年12月27日周三 下午5:14写道：

**Comment by ccseer** [comment]
1218.io

**Comment by llxwj** [comment]
我用的是从sf.net 下载的版本. 0.8.1

**Comment by llxwj** [comment]
![image](https://user-images.githubusercontent.com/2971388/34412039-ad8e3f76-ec15-11e7-9a42-3d8901f66611.png)

**Comment by ccseer** [comment]
如果你希望尝试下 正式版的话 可以从这里下载
www.1218.io

正式版已经更新到 1.8.1 了
这个bug已经修复了

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/34879693-0685ab62-f7e9-11e7-958a-d50181f8f690.png)
