### ISSUE TITLE
Seer 1.8.1 plus Dopus 12.7 not working

### ISSUE THREAD

**Issue by Qvinto1** [ccseer/Seer#147]
Seer latest version and Dopus Pro latest version 12.7 Build 6540 are not working.

I have followed the config advice specified here but still seer does not work in opus. When trying to preview a file the mouse icon briefly changes but no preview is launched. The dopus path is specified corrcetly and i have restarted my PC after installation

https://github.com/ccseer/Seer/issues/17

**Comment by Qvinto1** [comment]
Any help? thanks

**Comment by ccseer** [comment]
Hi

I just got my new PC

I am currently working on HiDPI support
Please give me a few minutes

**Comment by Qvinto1** [comment]
ok thanks

**Comment by Qvinto1** [comment]
Can i get some help? its been 2.5 weeks.

**Comment by ccseer** [comment]
Would you please try it after 1.9.0 released?

Qvinto1 <notifications@github.com>于2018年2月4日周日 下午4:17写道：

**Comment by Qvinto1** [comment]
Sure, when will it be available? Thanks

**Comment by ccseer** [comment]
Sorry
I can't guarantee anything.
It's almost the Spring Festival here.
But I am trying to release it next week if anything works fine.

Qvinto1 <notifications@github.com>于2018年2月4日周日 下午4:33写道：

**Comment by ccseer** [comment]
try Seer-1.9.0
if it still exists, reopen this issue
: )
