### ISSUE TITLE
能把iso文件的sha1、md5信息与其他文件一起显示出来吗？

### ISSUE THREAD

**Issue by ddkk3000** [ccseer/Seer#149]
我感到很奇怪，不知道为啥没有

**Comment by ddkk3000** [comment]
最好能把所有文件的该信息都显示了。不明白为何不显示

**Comment by ccseer** [comment]
有的. 只是大的文件显示要计算一会.
其他的文件 要在右上角点 "i" 显示

ddkk3000 <notifications@github.com>于2018年2月1日周四 上午9:00写道：

**Comment by ddkk3000** [comment]
需要点i我知道，可是我点了，等了大概一分钟也没显示呀。我的电脑不可能那么慢呀。囧。

╭( ′• o •′ )╭☞ lixiaozhe.com<http://lixiaozhe.com>

发件人： Seer<mailto:notifications@github.com>
发送时间： 2018-02-01 09:02:23
收件人：  ccseer/Seer<mailto:seer@noreply.github.com>
抄送：  ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [ccseer/Seer] 能把iso文件的sha1、md5信息与其他文件一起显示出来吗？ (#149)
有的. 只是大的文件显示要计算一会.
其他的文件 要在右上角点 "i" 显示

ddkk3000 <notifications@github.com>于2018年2月1日周四 上午9:00写道：

**Comment by ddkk3000** [comment]
不好意思。显示了。囧。能不能加个进度条。。

╭( ′• o •′ )╭☞ lixiaozhe.com<http://lixiaozhe.com>

发件人： Seer<mailto:notifications@github.com>
发送时间： 2018-02-01 09:02:23
收件人：  ccseer/Seer<mailto:seer@noreply.github.com>
抄送：  ddkk3000<mailto:lixiaozhe@live.com>; Author<mailto:author@noreply.github.com>
主题： Re: [ccseer/Seer] 能把iso文件的sha1、md5信息与其他文件一起显示出来吗？ (#149)
有的. 只是大的文件显示要计算一会.
其他的文件 要在右上角点 "i" 显示

ddkk3000 <notifications@github.com>于2018年2月1日周四 上午9:00写道：
