### ISSUE TITLE
Photoshop Dosnt work, and seer isnt available for Camera raw photos.

### ISSUE THREAD

**Issue by imanagers** [ccseer/Seer#155]
when seer is running photoshop key commands dosnt work at all.

**Comment by ccseer** [comment]
what version?

**Comment by ccseer** [comment]
install a plugin to support .rw2
![image](https://user-images.githubusercontent.com/15963166/37249312-457e0774-2520-11e8-843e-ed043f360264.png)

**Comment by ccseer** [comment]
not sure which version you are using, but the plugin can be used with Seer-1.8.1
