### ISSUE TITLE
Not an issue : Request

### ISSUE THREAD

**Issue by kkthebeast** [ccseer/Seer#156]
Love your tool sir!

Any chance of seeing previews for theses formats?

http://www.open3mod.com/
^^here is an open source viewer that would take the leg work out of the process

.3ds
.obj
.max
.fbx
.dae  https://github.com/KhronosGroup/OpenCOLLADA
.nif   https://sourceforge.net/projects/niftools/

Don't care if they have textures or anything fancy, just the jist of what is in them would be amazing and a huge time saver :)

Thanks for your hard work sir!

**Comment by ccseer** [comment]
2.1.0 has a plugin - 3D viewer
