### ISSUE TITLE
Seer Not Previewing any file just showing its properties

### ISSUE THREAD

**Issue by mahmudayaz** [ccseer/Seer#179]
Hi All,

Seer is not previewing any file, just showing the file properties.
![issue](https://user-images.githubusercontent.com/41432924/42941256-9edb4ca8-8b75-11e8-93a2-2ce62565876f.png)

Anyone know the solution?

Kindly help

**Comment by ccseer** [comment]
According to the UI, I assume that you are using the free version -- 0.8.1, please check if you installed any plugin.
The free version has worked well for years
