### ISSUE TITLE
整合进 wox

### ISSUE THREAD

**Issue by happlebao** [ccseer/Seer#18]
就像 alfred 的 shift 键一样
有想法吗？
不过既没有源码也没有 dll……

**Comment by ccseer** [comment]
我用过一段时间的 alfred，我知道 wox 是它的 win 版。

不过，你具体是什么意思啊？能不能详细一点。

**Comment by happlebao** [comment]
就是 wox 的条目 按 shift 键 -》 调用 seer -》 给出当前条目预览
利益相关：wox 现在我在开发

**Comment by ccseer** [comment]
刚回家了...
我得安装一个试试，看具体怎么做

我尽快给你回复啊
😄

**Comment by happlebao** [comment]
不急，我也有一大堆 issue 没关（逃

**Comment by happlebao** [comment]
如果不想开源的话，最好能暴露成一个服务，然后提供 dll 的sdk。像 everything 那样。

**Comment by ccseer** [comment]
现在 Seer 里面还有一部分代码是我之前为公司写的，要开源需要把整个界面模块换掉才行啊。
另外，我还指着这个 Seer 能帮我找份工作... 
虽然从过去的一个月找工作的经历来看并没啥用 😢

**Comment by ccseer** [comment]
另外我应该没法像 Wox 那个调 Everything 的SDK 。
Wow 要的是搜索结果，这个 Everything SDK 可以做到。但是要直接显示的话，需要两个软件配合才行吧，比如我现在要支持 Everything ，但是这个软件把空格键给吃了，我就没办法继续了。（不过作者说下个 Everything 版本会改

如果需要支持 Wox，我能想到的是利用调用参数，设置 Seer 的显示位置和显示大小。每次 Wox 里selected 一个文件后就可以直接命令行调用 Seer， 然后在 配置好的地方显示？

**Comment by ccseer** [comment]
目前还只支持 
`Seer.exe FILE_PATH` 
的方式命令行调用 ..

如果可行的话，我可以为 Wox 协调一下。
我也非常希望能够支持 Wox 啊～

**Comment by happlebao** [comment]
你这软件什么语言写的？c#还是c++？

命令行调用错误返回就很麻烦。。
如果是 c++ 写的话，作为使用方，我希望能用 dllimport 直接调用函数。不是比命令行好多了。
.net 的话就更简单了。

我需要两个接口：
```
show(filePath, top, left, width (optional), height(optional))
hide()
```

那就把坑挖起来，到时候一起去打广告（逃

**Comment by happlebao** [comment]
不要指望用 github 找工作了，纯 c# 项目，微软爸爸连面试都不给我（哭

**Comment by ccseer** [comment]
C++ 
框架是 Qt

所以，你的方法的具体操作流程是怎样的？

**Comment by happlebao** [comment]
wox 按 shift 快捷键 -> 调用 seerSDK.dll 的 show() 方法 -> seerSDK.dll 调用 seer 主体或者服务（取决于你怎么写）

**Comment by happlebao** [comment]
用命令行的话，等于重新开一遍程序，要初始化一大堆东西，很慢吧。。。

**Comment by ccseer** [comment]
如果 Seer 是开启状态，用命令行调用和直接在文件夹触发的速度应该相当的。

主要是用 dll 调 Seer 主体的话，估计我还是用命令行去调更方便。

**Comment by happlebao** [comment]
命令行错误返回怎么弄
至少要有如下吧：
1. 文件类型不支持
2. 文件不存在
3. seer 没有运行

**Comment by ccseer** [comment]
当 Seer 没有运行的时候，用命令行调用，第一次会打开 Seer ，忽略路径参数不显示文件。这个应该会在下个版本改成第一次就直接显示预览。
这样第三点就没问题了。

目前只有没有后缀名的不支持。其余的不能显示内容的也会显示文件属性。这个应该也会改掉，没有后缀名的也直接显示文件属性。
这样第一点就没问题了。

第二点，目前的逻辑是，触发了两次相同的路径，再第二次触发的时候会关掉预览
对于不存在的路径会在内部直接返回，什么也不做。
如果需要的话，Seer 可以加一个参数，让你在文件不存在的时候进行一次提示，提示方式就是右下角 system tray icon 那里 show 一条 msg 了

**Comment by happlebao** [comment]
这听起来不错。那没问题了。
那么位置呢？多显示器怎么办？

**Comment by ccseer** [comment]
我就说今天下载怎么变多了...

发现了这个  http://sspai.com/34288

**Comment by happlebao** [comment]
2333 我也被加进去了

**Comment by happlebao** [comment]
所以我才想起来找你一起打广告（

**Comment by ccseer** [comment]
hidpi 我已经支持了啊...
多显示器我也支持了，不过如果确定了位置的话，应该就没有多显示器的啥事了。位置和窗口大小可以让你这边给参数。不给参数，我这边也会有默认的。

你的那个第四点，Seer 挂了和 Seer没有运行 应该就是同一个问题了。

**Comment by happlebao** [comment]
那如何知道 seer exe 的位置呢？
你写 path 了吗？还是绝对路径？
你把版本也写进文件名了，岂不是每次更新都要重新选？

**Comment by ccseer** [comment]
版本不在文件名里，升级后执行路径也不会变。只有安装文件有版本号。

没有写path，应该也不会去写环境变量，方便以后出绿色版。

对于你那边，唯一的麻烦可能就是要手动去设置 Seer 路径了。

**Comment by happlebao** [comment]
那基本没问题了
位置参数放出来后在这里通知我一下吧

**Comment by ccseer** [comment]
@happlebao  Hi~ 我今天下午就能写完命令行调用了.... 要不你给个邮箱，我发给你?

**Comment by ccseer** [comment]
Seer.exe [options] [path]

Options:
  -v, --version   Displays version information.
  -?, -h, --help  Displays this help.
  -l, --log       Generate a "seer.log" file.
  -c, --cya       Hide the preview window.
  -s, --shake     Shake the preview window.
  -x <int>        The x position of the preview window.
  -y <int>        The y position of the preview window.
  -w <int>        The width of the preview window.
  -a <int>        The height of the preview window.

Arguments:
  path            File to preview, optionally.

**Comment by ccseer** [comment]
@happlebao  需要你在机器上装一个Seer-0.7.4.exe  https://sourceforge.net/projects/ccseer/ 

然后我给你发个当前的exe. 你替换掉就可以了

**Comment by ccseer** [comment]
![75524](https://cloud.githubusercontent.com/assets/15963166/16539830/559d5dd8-4081-11e6-8463-a7c7138e97a1.png)

**Comment by ccseer** [comment]
@happlebao   Hi, 我要发布新版啦...  还要兼容嘛?

**Comment by happlebao** [comment]
最近比较忙。。。。 你先发吧。。

**Comment by ccseer** [comment]
Ok....

等你那边好了我们再联系吧那

**Comment by ccseer** [comment]
@happlebao    hahahahahaha    快看这个 http://www.theverge.com/circuitbreaker/2016/8/4/12347032/switch-mac-to-windows-apps-utilities

大网站啊...


说真的.我们啥时候测试下兼容

**Comment by S7venYoung** [comment]
我两大 Windows 软件作者竟然在这里 py 交易

**Comment by happlebao** [comment]
@S7venYoung 不 py 交易活不下去了。。。
@ccseer 真的太忙。。。

**Comment by S7venYoung** [comment]
@happlebao 话说啥时候支持 Windows UWP 软件搜索，Listary 5.0 支持了，而且还支持了web search。。。

**Comment by happlebao** [comment]
@S7venYoung 
web search 不一直有吗。。。
uwp： 
https://github.com/Wox-launcher/Wox/issues/198#issuecomment-240590603
https://ci.appveyor.com/project/happlebao/wox/build/1.3.254/artifacts

**Comment by S7venYoung** [comment]
@happlebao 我凑，我凑，看来我掉队了。我是说 Listary 5.0竟然支持 web search了，以前并没有。。。

**Comment by ztmdsbt** [comment]
谢谢二位作者的辛苦.
作为程序员真的想给二位贡献点啥代码啊!
你们能不能把需求列在 issue 上我领一个给你们发 PR?
@happlebao @ccseer

**Comment by ccseer** [comment]
真的吗~？ 

@ztmdsbt   我确实有一个需求，一直写不出来，折腾了好久~~~   还准备出个 500~1k 求一个demo 来着。

就是如何获取 系统标准 open/save 窗口的当前选中文件。

**Comment by ztmdsbt** [comment]
@ccseer  我来 spike 一下.

**Comment by S7venYoung** [comment]
期待大神们的新作

**Comment by ccseer** [comment]
@happlebao  想到一个新方法.. 是不是可以通过系统api找到已打开程序的句柄, 再通过句柄去给 Seer  SendMessage . 这样在内部处理应该好很多
