### ISSUE TITLE
Something unexpected happened

### ISSUE THREAD

**Issue by lawrencegs** [ccseer/Seer#186]
Hello guys, I'm running **Seer 1.9.0 (Paid License)** on **Windows 10** - and once a week, I faced this error. Hitting Cancel, OK or Close button will only re-spawn the dialog

![image](https://user-images.githubusercontent.com/232827/45680596-7ee79f80-bb65-11e8-9953-a16c76229e3a.png)

My solution is either 
A. "End Task" from Task Manager, or
B. Restart Windows

I am running this on **Microsoft Surface Pro 2017**. No idea how to replicate the issue, but I notice that this happens sometime after I use external monitor.

**Comment by ccseer** [comment]
Update to 2.0.0 please
