### ISSUE TITLE
Cannot view Office 2016 documents

### ISSUE THREAD

**Issue by TheFatherMind** [ccseer/Seer#188]
When I preview Office 2016 documents I get a list of files.

Great app!!!
Just a side note.. 
The latest version on sourceforge does not match the latest version on your website.
There is a link to your homepage on your sourceforge support page that goes to a bad page.  http://www.1218.io/index.html?sf does not exist.

Update:
After installing it there was no tray icon.  So I was unable to get to the settings and unaware there were settings.  I had to terminate the app and re-run it.  After doing so I saw the section for the extensions.  Took me a minute to sort through it since there were no clear directions.  But I have it working now.

![screenshot](https://user-images.githubusercontent.com/11869399/45932356-a3f65c80-bf2f-11e8-98bb-12f7117251af.png)

**Comment by ccseer** [comment]
#33
