### ISSUE TITLE
Closing the Preview

### ISSUE THREAD

**Issue by foudamo** [ccseer/Seer#19]
This is a great tool - however, why isn't there a setting for closing the preview by pressing on "Esc" or clicking away anywhere on the screen? 

It doesn't also help trying to close it by pressing alt+F4 because the focused screen is typically Explorer.exe (in other words, when I try to close it by pressing alt+F4 I end up closing the Explorer window and not Seer)

Is there any plans to add this setting soon?

**Comment by ccseer** [comment]
If preview window doesn't have focus, it closes when you triggered a file twice.

**Comment by foudamo** [comment]
No I get that, I think you misunderstood what I am trying to say so I will break it down below ... 

Issue_1: When I preview something by pressing on the Spacebar, the app isn't automatically in focus (this is the issue). So I can't press on the ESC button or Alt+F4 to exit the preview (I must click on the preview first to get it in focus, then press ESC) ... So I would like the preview to always be in focus as it starts.

Issue_2: When I preview something by pressing on the Spacebar, I would like to be able to click anywhere outside the preview window once I am done for the preview to close automatically.

Hope that explains a bit better.

**Comment by ccseer** [comment]
1. First of all, the shortcut for close preview window is Esc / Ctrl+W. 
   And Seer should leave focus to the Windows Explorer, so we can use  **↓→←↑** to change the previewing file.
2. You see, Seer can't have the focus, so this _Issue_2_ doesn't exist.
