### ISSUE TITLE
QTTabBar 拦截空格指令, Seer 不能正常使用 

### ISSUE THREAD

**Issue by Tomotoes** [ccseer/Seer#192]
您好. 

每次我选中所要查看的文件A 并摁下空格后 , 都会自动跳转到开头的某个文件B,然后打开这个文件B.
并且 不管我选中该文件夹下的哪个文件 摁下空格, 都会快速跳转到文件B,并且打开B. 

也就是说 启动 QTTabBar 这个软件后, 我选中文件 摁下空格,就会迅速跳转到另一个文件. 从而 Seer 也打开了错误的文件.

在我研究后, 只有修改了 Seer 快捷键 , 方可正常使用. 可这样 不是我想要的.

您有没有其他办法呢? 谢谢.

环境: Windows10 1803
软件: QTTabBar 1083 
Seer: 2.0

**Comment by Tomotoes** [comment]
我通过设置 QTTabBar 快捷键 解决了这一问题.
将 `聚焦文件夹视图`  设置为 `Space` 
😄

**Comment by liangtao** [comment]
> 我通过设置 QTTabBar 快捷键 解决了这一问题.
> 将 `聚焦文件夹视图` 设置为 `Space`
> 😄

Nice, many thanks.

For those using English version, shortcuts -> focusing -> set space as a key shortcut for Focus folder view -> done :)
