### ISSUE TITLE
No Directory Opus support in latest version of seer

### ISSUE THREAD

**Issue by Apocalypse612** [ccseer/Seer#196]
Seer doesn't work inside of Directory Opus. I see there have been other requests for this which were all closed.

Please maintain a working copy of seer that stays functional with directory opus.

Thanks!

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/49993482-b974a300-ffc1-11e8-860e-7d1ec877293b.png)

**Comment by Apocalypse612** [comment]
Oh cool, thank you!

**Comment by AlexanderChina** [comment]
最新版的后面还有一个脚本功能的为什么在高级设置里都没有第三方呢

**Comment by AlexanderChina** [comment]
@ccseer 最新版的后面还有一个脚本功能的为什么在高级设置里都没有第三方呢

**Comment by ccseer** [comment]
> @ccseer 最新版的后面还有一个脚本功能的为什么在高级设置里都没有第三方呢

不用设置. 默认支持 https://support.qq.com/products/366565/faqs-more?id=115792

**Comment by AlexanderChina** [comment]
@ccseer 在directory opus 预览窗口打开的情况下使用了seer结果导致seer在do中打开预览停留在出错前的最后一个文件，如何修复？

**Comment by ccseer** [comment]
> @ccseer 在directory opus 预览窗口打开的情况下使用了seer结果导致seer在do中打开预览停留在出错前的最后一个文件，如何修复？

权限问题.
