### ISSUE TITLE
Error: LoadLibrary failed with error 87: The parameter is incorrect.

### ISSUE THREAD

**Issue by edgariscoding** [ccseer/Seer#197]
Started receiving this error after updating to Windows 10 v1809. I've attempted uninstalling and reinstalling but I receive the same error. I'm using version 2.0.

**Comment by ccseer** [comment]
Are you saying you can not use Seer now?

Please email me if that is true

**Comment by edgariscoding** [comment]
Correct. Emailing now.

**Comment by ccseer** [comment]
please download Seer-2.1.0 and try again~
