### ISSUE TITLE
EPS and AI previews

### ISSUE THREAD

**Issue by seanekimber** [ccseer/Seer#198]
When I try to preview .eps or .ai files (which I frequently have to do in my field), I only get a bunch of text in the window. Is there a fix for this?

Thanks.

**Comment by ccseer** [comment]
Which version are you using?
.ai is supported by default, eps can be supported by plug-in if you are
using Seer-0.8.1 or Seer-2.1.0.

**Comment by seanekimber** [comment]
Hi! Thanks for your reply. I"m using version 2.1.0. What plug-in should I be using? And how do I install it?

Thanks!






________________________________
