### ISSUE TITLE
win10 x64上使用有一些bug

### ISSUE THREAD

**Issue by ustcltx** [ccseer/Seer#2]
## BUG
- 打开pdf浏览时上下滑动太卡了
- msoffice上打开直接闪退，无法预览，但我到临时目录里可以找到成功生成的pdf

## 建议
- 打开预览时最好有一些渐变的动画，类似Picasa
- 优化一下office文件的预览速度，或者换msoffice转成pdf的库

**Comment by ccseer** [comment]
1. 考虑到以后的跨平台
PDF 的工作量其实挺大的.. 也比较复杂.. 只能以后慢慢优化了
2. MSoffice 的问题确实是个bug.. 新版本已经改了

---------------------------------------------------
1. 我在获取资源管理器里面的文件坐标位置的时候遇到了一点问题...但是桌面的可以获取到..所以目前还没有动画..
2. office 的预览目前能完整展示内容的方案太少了...所以我也没有太好的方法.

thx

**Comment by ustcltx** [comment]
Happy New Year！

**Comment by PaaandaChen** [comment]
在设置里面，如果我勾选过一两个设置项，切换到其他设置页（比如从General换到Type）再切换回来，那么勾选过的设置项会丢失。

也不知道算不算个bug，在这里提一下，最好加个“应用”选项，不然多个设置页中的设置会变得很麻烦。

祝好！

**Comment by ccseer** [comment]
啊…我想起来了…

我这几天看不了，但我能想起来造成这个原因的 傻x 代码。

谢谢…这个会在下个版本更正。
非常感谢。
下个版本应该会在二月之前…

**Comment by coooooooooorey** [comment]
找到原因了...

@ustcltx   关掉 设置里 general 的   跟踪资源管理器   选项就好了...

我一般都不开这个选项...
今天查到没改这个问题就直接发布 0.6.0 了...
我现在正在着手改这个问题..

谢谢反馈.
: )

**Comment by ustcltx** [comment]
msoffice预览速度也太慢了。。。

**Comment by coooooooooorey** [comment]
没办法啊~真是找不到更好的办法

不过我在新版本做了一些提升: 如果文件的md5值没有变化的话就不用再次转换~~

你要不要先试用一下..顺便帮我测试测试.

**Comment by PaaandaChen** [comment]
这个0.6.0算是发布了吗？为什么页面上还是0.5.1。
以及settings里面的auto check for updates有用的没有

**Comment by ccseer** [comment]
@PaaandaChen  
还没发布..
还在测试..

想帮忙吗?

**Comment by PaaandaChen** [comment]
额，怎么帮忙

**Comment by ccseer** [comment]
@PaaandaChen  给我个邮件地址 或者给我发个邮件... 

我把最新版发给你

0.6.0 的 changelog 在主页上看得到..

你看看有啥问题，及时反馈给我。我改了再发布。

**Comment by PaaandaChen** [comment]
pandachen0611@gmail.com
你发我这里吧，我帮你测测

**Comment by ustcltx** [comment]
我也可以帮忙！


[image: Lin Taixing on about.me]

Lin Taixing
about.me/lintaixing
  <http://about.me/lintaixing>

2016-01-15 11:33 GMT+08:00 Zhuohan Chen <notifications@github.com>:

**Comment by coooooooooorey** [comment]
给我个邮箱…我晚上发给你

On Jan 15, 2016 7:32 PM, Taixing Lin <notifications@github.com> wrote:
我也可以帮忙！


[image: Lin Taixing on about.me]

Lin Taixing
about.me/lintaixing
<http://about.me/lintaixing>

2016-01-15 11:33 GMT+08:00 Zhuohan Chen <notifications@github.com>:

> pandachen0611@gmail.com
> 你发我这里吧，我帮你测测
>
> ―
> Reply to this email directly or view it on GitHub
> <https://github.com/ccseer/Seer/issues/2#issuecomment-171863920>.
>

―
