### ISSUE TITLE
MS converter plugin

### ISSUE THREAD

**Issue by Lateron** [ccseer/Seer#200]
The SEER plugin (MSOffice) to view .doc files is not working for me. I know it is not recommended but I have very many of these files to preview amongst the many .docx files (which preview fine)
Is there another solution other than batch converting .doc to .docx?

**Comment by ccseer** [comment]
The new plugin excel2html included in Seer-2.2.0 can replace the `MS converter`
so please try to remove `ms converter` plugin

![image](https://user-images.githubusercontent.com/15963166/57563513-57359800-73d1-11e9-80bc-91689965623f.png)
