### ISSUE TITLE
CTRL+ALT+S is  registred by another application 

### ISSUE THREAD

**Issue by jasmineanic** [ccseer/Seer#202]
Hi when I try to have seer working on win 10  it does not work and it says : CTRL+ALT+S is  registred by another application 
what should I do ? thanks for your help kind regards from France

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/54064448-535d8c00-424f-11e9-9727-10bd51b5fdd8.png)

delete it or modify it
