### ISSUE TITLE
如何设置默认不渲染 Markdown 文件？

### ISSUE THREAD

**Issue by Moyf** [ccseer/Seer#204]
当前预览 Markdown 会自动渲染成格式化后的效果，但这需要一定的加载时间。
我希望能设置默认作为代码文件进行预览，请问有办法进行设置吗？

![image](https://user-images.githubusercontent.com/4013062/54174460-8dce5f80-44c1-11e9-8393-813efc63aec4.png)
当前用这个按钮可以切换成代码式的预览模式，可以将其设置为默认模式吗？

**Comment by ccseer** [comment]
目前没有，我考虑下要不要记录预览状态。
如果是渲染状态下次就渲染，如果不是就显示原文字

**Comment by Moyf** [comment]
嗯嗯，好的，非常感谢！

Seer <notifications@github.com> 于2019年3月12日周二 下午12:53写道：

> 目前没有，我考虑下要不要记录预览状态。
> 如果是渲染状态下次就渲染，如果不是就显示原文字
>

**Comment by ccseer** [comment]
等更新吧.
已经做了
