### ISSUE TITLE
Seer 软件经常崩溃

### ISSUE THREAD

**Issue by Tomotoes** [ccseer/Seer#205]
## 操作系统
Window10 1803 专业版

### 版本
2.0.0
![image](https://user-images.githubusercontent.com/32236122/54432225-84642200-4763-11e9-8226-00421d50585c.png)

### 报错信息
![image](https://user-images.githubusercontent.com/32236122/54432160-5848a100-4763-11e9-824a-8d868b310a30.png)

这种情况经常出现 , 搞得我都不敢对文件摁空格了...
不管是什么类型的文件 , `.c` 或者 `.png` 或者 `.docs` 等...

最近老是出现这种问题 🇼🇫

**Comment by Tomotoes** [comment]
![image](https://user-images.githubusercontent.com/32236122/54432524-74007700-4764-11e9-80a5-53b8882081a4.png)

尤其是`pdf` 类型的文件...

**Comment by ccseer** [comment]
更新到2.1.0再试下

**Comment by ccseer** [comment]
抱歉，有操作步骤吗

**Comment by ccseer** [comment]
手动检查一下更新

先升级一哈

**Comment by Tomotoes** [comment]
嗯嗯 , 好的 , 已更新 , 已无大碍 , 谢谢!
