### ISSUE TITLE
3DViewer not working

### ISSUE THREAD

**Issue by felipetorrents** [ccseer/Seer#207]
I'm running Windows 10 17763, Seer 2.10, java 8, python 3.5. I tried with different supported 3d models and they all just open a blank html page.
![image](https://user-images.githubusercontent.com/48898378/54892767-2cc36600-4e89-11e9-8bb2-89f187c973c0.png)
I downloaded the plugin's zip, extracted to a folder in downloads, and added the plugin.json at the seer plugin section.
Great utility BTW! i've been long missing this feature from macOS and linux.
Is there something else I need to install?

**Comment by ccseer** [comment]
Please wait for one or two weeks.

I am working on Seer now. And this plugin will be updated as well.

**Comment by felipetorrents** [comment]
Thank you! You're awesome!

**Comment by ccseer** [comment]
Download https://github.com/ccseer/Seer-plugins/raw/master/release/3DViewer.zip

1, download and add it again
2, Go to "Settings - Advanced - Others", click the button "Folder" on the right to open Temp
3, remove "libs" folder, remove all .html files

**Comment by ccseer** [comment]
Please let me know if it works.

**Comment by felipetorrents** [comment]
It doesn't work but just found out something that might help. I have Chrome set as default, and when I grab index.html to firefox y loads the 3dviewer interface. In chrome it opens a blank page. Maybe it has to do with chrome permissions to run scripts?

**Comment by felipetorrents** [comment]
![image](https://user-images.githubusercontent.com/48898378/56304150-7cedbb00-610b-11e9-9f5e-0a86e816a1fc.png)
Here's the output of index.html in chrome

**Comment by ccseer** [comment]
No seer has the access to local file. Did you remove the old plug-in and go
to the temp folder to remove the “libs” folder and all the other html files

**Comment by felipetorrents** [comment]
Yes I did both and behaving the same.

**Comment by ThunderDoc** [comment]
Mine doesn't work too, instead it displays the HTML file.

![Seer_SpgnnPSw9c](https://user-images.githubusercontent.com/54566314/81730883-9a06d180-9464-11ea-90bb-39c3334a153a.png)

**Comment by ccseer** [comment]
> Mine doesn't work too, instead it displays the HTML file.

Sorry, Seer-0.8.1 cannot use this plugin. 
It's for Seer-2.3.0.

**Comment by ccseer** [comment]
2.4.0 has released. Please try again

**Comment by felipetorrents** [comment]
3D viewer now works well for me with the 2.4.0 version. Thank you!
