### ISSUE TITLE
一打开 Seer 就自动闪退

### ISSUE THREAD

**Issue by Moyf** [ccseer/Seer#209]
[ReportArchive.zip](https://github.com/ccseer/Seer/files/3068689/ReportArchive.zip)
这是崩溃后生成的文件，分别位于：
![image](https://user-images.githubusercontent.com/4013062/55959079-a1c1d880-5c9c-11e9-888f-9bc957ceb7ea.png)

已尝试彻底卸载并重装，版本号为 2.1.0，无法修复。

**Comment by Moyf** [comment]
另，刚才尝试安装了 0.8.0 的老版本，依旧是打开就崩溃 _(:з」∠)_

**Comment by ccseer** [comment]
要不你先装个  win32 版本用一下? 给我发邮件，我给你授权

**Comment by ccseer** [comment]
你这个是 windows 的版本吧

**Comment by Moyf** [comment]
呃，我是从官网下载的……应该就是 Win 32 版本来着

**Comment by Moyf** [comment]
![image](https://user-images.githubusercontent.com/4013062/55959927-60322d00-5c9e-11e9-9c51-ef6b60983f5f.png)
用这个安装的

**Comment by ccseer** [comment]
额.... 给我发邮件吧，我给你Windows Store 的授权. 我查下。
我刚写完发布  PinStack。

大概周日或者下周一开始改 Seer

**Comment by ccseer** [comment]
cc.seer@gmail.com

**Comment by ccseer** [comment]
可以帮忙测试一下吗
刚刚的 dmp  我没法用/. 我再给你个 Seer.exe 执行文件. 
然后.
.
.
.
.
你再崩溃一次?

**Comment by Moyf** [comment]
噗……好的，等晚上我回家里再崩崩看
顺便一提，昨天安装的 WinStore 版本可以正常使用 √

**Comment by ccseer** [comment]
升级新版本试下
