### ISSUE TITLE
graphics could be improved

### ISSUE THREAD

**Issue by olivierdalang** [ccseer/Seer#21]
Hi,

Thanks for this awesome tool !

I think the look of window could be improved a little bit. Currently, the seer window looks a lot like normal explorer window : it's white, square, opaque, slight shadow...
This makes it a bit confusing when there are other window open.

![capture d ecran 2016-06-09 01 50 09](https://cloud.githubusercontent.com/assets/1894106/15916670/bf2c6960-2de4-11e6-8316-d75b9bd93058.png)

If you compare, on Mac OS X, quicklook and normal window have a very different look : 

![quicklook](http://articles-images.sftcdn.net/wp-content/uploads/sites/3/2008/02/quicklook_gallery03_20071016.jpg)

I'd suggest copying what they did : semi-transparent, dark and rounded window

**Comment by coooooooooorey** [comment]
![image](https://cloud.githubusercontent.com/assets/3081374/15919010/b43f2c94-2e3f-11e6-87b8-f7c3a58e0b20.png)


------
As you can see, not everything is as same as OSX, I have my own ideas.

And there will be a new UI in the next version(0.8.0), the designer is working on it.
In v0.8.0, there will be a _light theme_ and a _dark theme_. Hope you like it. : )
