### ISSUE TITLE
Not really an issue, just a request for photographers!

### ISSUE THREAD

**Issue by GabrieleVergottini** [ccseer/Seer#210]
Hi, I'm Gabriele, and Italian guy who bought seer 2/3 years ago! Today I'm here to ask you if you can improve seer for peoples like me, that every day have to choose Xnumber photos for our customers. The idea is to make seer compatible with all RAW formats CODECS like SONY, NIKON and CANON, and to make the video preview at 60fps.

This would be an insane time-saver for photographers/designers cause it'll save time before opening softwares like Lightroom.

Cheers, Gabriele.

**Comment by ccseer** [comment]
[image: image.png]


https://www.xnview.com/en/nconvert/#formats

[image: image.png]

**Comment by ccseer** [comment]
[image: image.png]
[image: image.png]

**Comment by GabrieleVergottini** [comment]
I really tried to understand what you linked to me there but I don't understand. I navigated in the Seer menu and I choose the Plugins, Available and than I found out that there were a Plugin for RAW image files (imagemagick), but when I installed it, I reach out that I'm still having problems previewing these type of files. Can you help me more? I'm not an expert..

Cheers, Gabriele.

**Comment by ccseer** [comment]
I will try to add a internal support next version - 2.3.0.

**Comment by ccseer** [comment]
[image: image.png]


would you please try to use this plugin?

**Comment by ccseer** [comment]
and would you please let me know if it works.

at the same time, can you send me a .RAW file to test?

**Comment by GabrieleVergottini** [comment]
Hi again and thank you so much for interest. I tried the plugin and it did not work for me. Mayb it's just me, that I can't use it, but the user guide say that you have just to download the .ZIP file, unzip them and then select the .JSON file... and it's done. But this isn't working for me, on the site of the plugin they're saying that the plugin supports a lot of media files but it isn't working..

Best regards, Gabriele.

PS this is the .ARW file, the Sony a7III original output file

It would be great also the support for .eps (also that plugin isn't working, and I'm a little bit confused cause ''hey, this plugin let you preview .eps files!'' and than ''why isn't it working?'') as well as 50/60p, 100/120p for videos, CMYK color space etc. The quick preview on MacOS can do this, and I'm sure that Seer can do it much better, but you have to close a little bit the software in my opinion, making it less customizable. Maybe the perfect solution would be a second version of Seer, where you (I said you cause you are the developer and who, besides you, could make it better?) put all the codecs and media files support (heavier in terms of disk space and pc performance) and a lighter one, fully customizable as it is right now!

[DSC00864.zip](https://github.com/ccseer/Seer/files/3194130/DSC00864.zip)

**Comment by ccseer** [comment]
I would let you know when it's done.

**Comment by ccseer** [comment]
[raw.zip](https://github.com/ccseer/Seer/files/3275069/raw.zip)

0. quit Seer
1. download this zip and extract two files
2. put libraw.dll into your installation folder, it is the same level with Seer.exe
3. put qraw.dll into Seer/imageformats
4. restart Seer.exe

**Comment by Divinenickname** [comment]
> Hi again and thank you so much for interest. I tried the plugin and it did not work for me. Mayb it's just me, that I can't use it, but the user guide say that you have just to download the .ZIP file, unzip them and then select the .JSON file... and it's done. But this isn't working for me, on the site of the plugin they're saying that the plugin supports a lot of media files but it isn't working..
> 
> Best regards, Gabriele.
> 
> It would be great also the support for .eps (also that plugin isn't working, and I'm a little bit confused cause ''hey, this plugin let you preview .eps files!'' and than ''why isn't it working?'') as well as 50/60p, 100/120p for videos, CMYK color space etc. The quick preview on MacOS can do this, and I'm sure that Seer can do it much better, but you have to close a little bit the software in my opinion, making it less customizable. Maybe the perfect solution would be a second version of Seer, where you (I said you cause you are the developer and who, besides you, could make it better?) put all the codecs and media files support (heavier in terms of disk space and pc performance) and a lighter one, fully customizable as it is right now!
> 
> P.S. this is the .ARW uncompressed file, the Sony a7III original output file at 14Bit color depth
> [DSC00864.zip](https://github.com/ccseer/Seer/files/3194130/DSC00864.zip)

When you added json, double click to img-convertor plugin and add your raw format. I added cr2 for CANON and it works for me.

**Comment by ccseer** [comment]
please follow the steps above. it is much more faster.

Because next version is not releasing very soon. I want to add the support
here first for ppl who asked.
Of course, the changes will be released in next version.

**Comment by ccseer** [comment]
new version will be released very soon. this has been fixed in Seer-2.3.0

**Comment by ccseer** [comment]
raw images are supported in 2.8.3, plugins for RAW Images can be removed.

BTW, last version is Seer-3.0.0
