### ISSUE TITLE
Window position and size won't be remembered if system reboot.

### ISSUE THREAD

**Issue by jcplus** [ccseer/Seer#211]
AS subject the size and position of the preview window is remembered but it will lose if the system restarts.

**Comment by ccseer** [comment]
You mean, you want them to be remembered after reboot?
Seer will adjust its size for every file automatically, I really cannot see
the point to save this data

**Comment by jcplus** [comment]
The default preview window size is roughly 500x500. The image dimension is far bigger than the default size these days. After system reboots, you have to preview any large photos or a standard A4 size PDF in a small window. That's why many people choose to adjust the window size. And these people have to adjust again and again after every reboot.

**Comment by ccseer** [comment]
what version are you using?

the last version is Seer-2.2.0

**Comment by jcplus** [comment]
2.1.0
Does 2.2.0 remember the size after reboot?

**Comment by ccseer** [comment]
No, but please update.

I will try to add this feature when "Keep window size and position" option
is checked

**Comment by jcplus** [comment]
Updated.

Thanks for taking my advice.

**Comment by ccseer** [comment]
this feature has implemented to Seer-2.3.0.
