### ISSUE TITLE
Microsoft Store Version, Seer dosn't autostart / unable to start through start menu

### ISSUE THREAD

**Issue by Motioneer** [ccseer/Seer#213]
When using the Microsoft Store Version Seer dosn't automaticly start at startup. Nor can Seer be started using the Start Menu entry. The only way to start it, is by launching the Microsoft Store, going to the Seer Page and pressing _Launch_ there.

**Comment by ccseer** [comment]
Please email me to get a .exe version to solve it first.
Because new version was just released last week, the next version might
take a while.

**Comment by melronkixy** [comment]
Hi i also just realised seer doesn't always start when i start my machine, i sometimes have to initiate it via programs. thanks.

**Comment by ccseer** [comment]
I will look into it next version
Thanks for your feedback

**Comment by ccseer** [comment]
Fixed in Seer-2.3.0
