### ISSUE TITLE
Seer can not view some picture files

### ISSUE THREAD

**Issue by vanti235** [ccseer/Seer#214]
In windows explorer, I can not view some picture files. All the file are JPEG format, with "jpg" or "jpeg" extensions.
My questions is some JPEG files can view by pressing the spacebar, but some are not. And most ridiculous thing is, I don't know the rules that when Seer can view a JPEG file, when can not. I go to the preferences to find solution, but get no answer, I already selected every possible option.
When I view a JPEG file that Seer can not open, a window displayed as shown in the attached file.
![Snipaste_2019-06-05_11-58-16](https://user-images.githubusercontent.com/39259192/58929385-56eaab80-8789-11e9-82f8-ff455a094d11.jpg)

Seer version: 0.8.1
OS: Windows 10 for education
CPU: i5-7500
RAM: 8G

**Comment by ccseer** [comment]
send 我一个不能预览的文件吧

**Comment by ccseer** [comment]
呃... 免费版 0.8.1 已经不更新了.. 已经过去好几年了
: (
最新版是 2.2.0 了.

**Comment by vanti235** [comment]
这个文件就无法预览。


    On Wednesday, June 5, 2019, 12:37:54 PM GMT+8, Seer <notifications@github.com> wrote:  
 
 
send 我一个不能预览的文件吧

**Comment by vanti235** [comment]
![IMG_20180117_163639](https://user-images.githubusercontent.com/39259192/60249124-b3f40000-98f6-11e9-9b80-47cfe98ed2de.jpg)
上面这个文件就不能预览。

**Comment by ccseer** [comment]
应该是软件版本的问题。
看你的 ui 应该是 0.8.1，几年前的版本了。
老版本确实一小部分图片文件看不了。
后来解决了。
