### ISSUE TITLE
Works over network?

### ISSUE THREAD

**Issue by robcop2000** [ccseer/Seer#22]
First of all great software.
Is must have in wondows 10.
But I look that doesn't work with the files stored in my smb server.
Can you implemet it or is a bug?
Thanks

**Comment by ccseer** [comment]
hi, it works on windows7, windows8, windows10.

**Comment by robcop2000** [comment]
The computer I'm using is windows 10, But the file are on the server with Windows Server 2013 R2.
And I share in smb

**Comment by robcop2000** [comment]
Sorry Windows Server 2012 R2

**Comment by ccseer** [comment]
Sorry. 
It doesn't work for now.

**Comment by robcop2000** [comment]
ok is planned? if you can I assume will be perfect. Anyway thanks an good job

**Comment by ccseer** [comment]
I tried to create a network drive from local disk. It works fine.

I would like to try add a real network drive to my computer, but I don't have one.

sry~

**Comment by robcop2000** [comment]
I you think  I can help you testing if it works, let me know.
Thnaks

**Comment by pepsifan92** [comment]
Hi!
Any progress on SMB shares? I have mounted an Linux Debian SMB share with Windows 10, and it doesn't work in the share (Z:\)
With local files it work's fine ;)

**Comment by ccseer** [comment]
I think I will try to look into it in version 0.9.0.

But I don't have a real network drive. I still don't know how to do it.

**Comment by robcop2000** [comment]
I have updated to seer 0.7.5 and now work on SMB shares.
Thanks

**Comment by ccseer** [comment]
@robcop2000  Are you 4 real?

**Comment by ccseer** [comment]
@robcop2000  I didn't do anything

**Comment by ccseer** [comment]
Anyway, if the bug doesn't exist, you can close this issue now~
😄

**Comment by ccseer** [comment]
@pepsifan92    Does SMB share work fine in Seer-0.7.5?

**Comment by robcop2000** [comment]
Yes
