### ISSUE TITLE
建议：增加触摸板双指左右上下滚动图片的功能以及增加放大图片到全屏的功能

### ISSUE THREAD

**Issue by iamfeiyu** [ccseer/Seer#220]
建议一：
希望的需求：双指上下左右能够像浏览网页滚动页面那样来操作图片，这将有利于浏览无法在窗口中显示全部的较长/较宽的大图片。

建议二：
希望的需求：能够放大图片到全屏，这样方便浏览大图。当前的做法是，仅能放大到占1/2电脑屏幕，在不能双指左右拖动图片情况下，这不利于阅览较宽的图片，这真的不方便。

**Comment by iamfeiyu** [comment]
提交优化建议

**Comment by ccseer** [comment]
在浏览图片有滚动条的时候，目前支持触碰拖动和鼠标点击拖动。触摸板的话，我下个版本看看啊，估计是可用。

全屏的话，呃。。。目前最大化之后需要 按一下 F5 刷新了才有
否则只有  加载时的 最大大小（屏幕出去任务栏之后大小的 95%），其实差不多

**Comment by ccseer** [comment]
刚试了下。
surface book2 的触摸板
有纵向滚动条的时候 可用双指滑动
但没办法横向滑动，横向操作要按下触控板后拖动

大点的图片可用通过 双指展开 放大到原图片比例， 双指合并  缩小到适配比例，或者双击图片任意未知还原。
最大化窗口/全屏要双击标题栏。

触摸板操作最终还是被操作系统模拟成鼠标操作了。
我试了几个软件，基本都没有这种横向触摸板支持的。
所以先这样吧。
新版本快发布了

**Comment by iamfeiyu** [comment]
> 刚试了下。
> surface book2 的触摸板
> 有纵向滚动条的时候 可用双指滑动
> 但没办法横向滑动，横向操作要按下触控板后拖动
> 
> 大点的图片可用通过 双指展开 放大到原图片比例， 双指合并 缩小到适配比例，或者双击图片任意未知还原。
> 最大化窗口/全屏要双击标题栏。
> 
> 触摸板操作最终还是被操作系统模拟成鼠标操作了。
> 我试了几个软件，基本都没有这种横向触摸板支持的。
> 所以先这样吧。
> 新版本快发布了

谢谢回复。期待新版本！

**Comment by ccseer** [comment]
这个能做了.
不过得下个版本了. 2.4.0.
所有的横向滚动条都会支持.

谢谢反馈
