### ISSUE TITLE
(question) Where do I uninstall Seer?

### ISSUE THREAD

**Issue by BBaoVanC** [ccseer/Seer#221]
I've checked the add and remove programs menu, and the Seer program folder, but I can't find any way to uninstall Seer.

**Comment by ccseer** [comment]
there is a uninst.exe, just run it.
:)

**Comment by BBaoVanC** [comment]
Every time I ran uninst.exe, it wouldn't remove any files, but I finally figured it out! You have you quit Seer before uninstalling, or else it only deletes the uninstaller.

**Comment by ccseer** [comment]
the last version is 2.2.0.
You were probably using the old version.
Thanks for trying out.
:)
