### ISSUE TITLE
Seer wont work without me opening up the app everytime

### ISSUE THREAD

**Issue by qsolan** [ccseer/Seer#222]
Everytime i open my computer for the day if i click on any pdf, img, anything with the spacebar nothing happens. But when i search SEER and click on the app.. everything opens up and works normally... Question is how do i do that without having to click on the app to wake it?

**Comment by ccseer** [comment]
what version are you referring to?
where you download it?

**Comment by qsolan** [comment]
I bought the app from windows online store. I’ll check what version it is

**Comment by ccseer** [comment]
please send me email cc.seer@gmail.com

**Comment by qsolan** [comment]
[image: image.png]
This is the one i have

**Comment by ccseer** [comment]
sorry,

it's a bug.

I would try to fix it in next version.

**Comment by ccseer** [comment]
Fixed in Seer-2.3.0
