### ISSUE TITLE
Seer app constantly crashes

### ISSUE THREAD

**Issue by GatorsUF** [ccseer/Seer#226]
I have Seer Pro and I love it's functionality....when it works.

The problem I have is that everytime I want to use it the app needs to be started again. After my computer sleeps for a while when I wake it up and try to preview a file nothing happens, I can see the seer icon in my system tray (sometimes more than one seer icon), but when I mouse over the icon it disappears.

To fix it I have to go into the start menu and open Seer Pro again.

I have it set to start with windows on "startup", but it basically never works right until I manually start the program.

My computer:
Huawei Matebook X Pro
Windows 10 Home
Nvidia MX150 GPU
Intel i7 8550U

**Comment by ccseer** [comment]
Hi
I have updated it yesterday. The latest version is 2.3.0. This uwp issue
was fixed.

**Comment by ccseer** [comment]
please reopen it if it still happens in Seer-2.3.0
