### ISSUE TITLE
音频预览的播放按钮 bug

### ISSUE THREAD

**Issue by Riajyuu** [ccseer/Seer#227]
STR:
1. 按下触发键预览一个音频，音频开始播放
2. 点击暂停按钮
3. 点击进度条或者拖动进度条

此时可见播放按钮没有变成暂停按钮，但是音频处于播放状态

未测试视频的状况

**Comment by ccseer** [comment]
测试了下，确实是个 bug。
下个版本会改。

**Comment by ccseer** [comment]
fixed in 2.4.0

**Comment by ccseer** [comment]
拖动 进度不会 改变播放状态了现在
