### ISSUE TITLE
[feature] 允许设置 markdown 渲染使用的 font-family

### ISSUE THREAD

**Issue by Riajyuu** [ccseer/Seer#228]
当前使用的方案非常容易出现毛边（狗牙）

**Comment by ccseer** [comment]
你有自定义  css 吗？
[image: image.png]



markdown 的样式好像是写在  css 里的。
当前 Seer 用的 css 是开源的，在 https://github.com/ccseer/Seer-markdown-css
你可以下载下来改了，然后在设置里填你改过的

**Comment by Riajyuu** [comment]
没有

**Comment by ccseer** [comment]
新版本 代码文本 改了字体.
普通文本没变
