### ISSUE TITLE
[feature] 允许文件信息窗口文字随意选中并高亮

### ISSUE THREAD

**Issue by Riajyuu** [ccseer/Seer#229]
这让用户能意识到这是可以被复制的，当前用户可以直接按下 ctrl + c ，但是并不一定能意识到这些文字其实可以被复制

**Comment by ccseer** [comment]
这个大概不行哦
这是个 列表，一次只能选中单个列表项的信息，正好也是当初这么设计的初衷。
实际上，整个预览窗口出现的所有的内容都是可以复制的，包括 mp3
的专辑封面，视频的当前播放帧，图片的当前内容，文件夹里的文件名...为了保证连贯，不可能所有都给处理一下。
