### ISSUE TITLE
[feature] 点击行号列号允许输入数字进行跳转

### ISSUE THREAD

**Issue by Riajyuu** [ccseer/Seer#230]
![image](https://user-images.githubusercontent.com/16912240/63829188-5745ad80-c958-11e9-8d25-11fc3dfa81ca.png)

即是点击图中的带方框部分

**Comment by ccseer** [comment]
这个可能是不行的.
目前不能做到这种程度
整个预览窗口只有 带密码的 pdf 和 压缩包 接收输入。

**Comment by ccseer** [comment]
欸, 看到你  16年就发过 issue 问 付费版和 免费版的区别?
发生了什么，你突然要来提这么多 issue ？
非常感谢，btw

**Comment by ccseer** [comment]
你是有激活的 Seer 了？
最新版是  2.3.0 了a
