### ISSUE TITLE
NOT work on 'TIF' figures

### ISSUE THREAD

**Issue by Johnytian** [ccseer/Seer#231]
After updated to new version 2.3.0, it does not work on 'TIF' figures. 
System: Windows 10 pro 1903 x64.

**Comment by ccseer** [comment]
1. 
![image](https://user-images.githubusercontent.com/15963166/64498861-14d18880-d2e9-11e9-8d45-7975487dcb7f.png)
2. 
![image](https://user-images.githubusercontent.com/15963166/64498909-506c5280-d2e9-11e9-8303-4f6ecb54676b.png)

**Comment by Johnytian** [comment]
Awesome, thanks.
