### ISSUE TITLE
预览和无法查看图片

### ISSUE THREAD

**Issue by 260361577** [ccseer/Seer#234]
![TIM截图20191101153051](https://user-images.githubusercontent.com/25073345/68009309-9b3c9200-fcbc-11e9-8526-681902174548.png)
![image](https://user-images.githubusercontent.com/25073345/68009066-d4c0cd80-fcbb-11e9-88c5-8b7fb02b8ce2.png)
PS和AI类文件无法预览缩略图、只能空格查看。
还有一些图片（JPG或PNG）无法空格查看（只能显示图片相关的文件信息）。

**Comment by ccseer** [comment]
Hi
你用的 Seer-0.8.1？
抱歉啊，这个免费版已经不更新了。
正式版已经到 2.3.0 了。

**Comment by ccseer** [comment]
UI 上的 界面显示问题  高分屏问题 已经都在 新版本修复改进了

**Comment by 260361577** [comment]
> UI上的界面显示问题高分屏问题已经都在新版本修复改进了
新版本在哪里下载啊，有没有连接

**Comment by ccseer** [comment]
1218.io/seer/dl

**Comment by ccseer** [comment]
1218.io
