### ISSUE TITLE
EPS Plug-in works after you first install, then doesn't work

### ISSUE THREAD

**Issue by Tallscot** [ccseer/Seer#235]
This is an ongoing issue with the EPS plug-in. After I initially install it, it works fine and I can preview EPS files. However, at some point later, it just stops working. SEER is working fine with the default file formats, but I can't preview EPS.

**Comment by ccseer** [comment]
Did you try to remove the plug-in and install again?

**Comment by ccseer** [comment]
the plugin is updated.

https://github.com/ccseer/Seer-plugins/blob/master/release/eps2png.zip

please remove the old one and retry it.
