### ISSUE TITLE
Media playback option

### ISSUE THREAD

**Issue by chongyunxiang** [ccseer/Seer#237]
![Annotation 2019-12-17 132341](https://user-images.githubusercontent.com/57867863/70967159-75cee080-20d0-11ea-9c86-bfd6ff21f877.png)
![Annotation 2019-12-17 132414](https://user-images.githubusercontent.com/57867863/70967188-8a12dd80-20d0-11ea-8a40-a1dd272b178c.png)
Whenever I play an audio file, can we have an option to display the file name, as well as have the scrub bar appear automatically, instead of needing to mouseover to the bottom to get it to appear?

**Comment by ccseer** [comment]
I am not sure
Seer has too many options now
I need some time to check  if it is really necessary

**Comment by ccseer** [comment]
Thanks for your feedback
