### ISSUE TITLE
Seer displays portrait JPGs and MP4s in landscape

### ISSUE THREAD

**Issue by scottjenson** [ccseer/Seer#238]
Portrait image and video shot on my Pixel3a is displayed in landscape. The rotate Left/Right buttons work but it doesn't stick (also the L/R keys don't work, I must click on the icon each time.)

I found a previous bug which is now closed saying this has been fixed. It appears to be back.

Some Exif Data
Image is 3.13 MB
Image Height: 3024
Image Width: 4032
Height: 4032
Width: 3024

This file opens correctly rotated in MS Photos

Seer 0.8.1 on an Intel NUC running Windows 10 Pro 1809

**Comment by ccseer** [comment]
Hi
the last version is 2.3.0 which has already fixed this issue.
http://1218.io
the free version is not updating anymore
sorry
