### ISSUE TITLE
Windows Explorer issue

### ISSUE THREAD

**Issue by chongyunxiang** [ccseer/Seer#239]
Pressing space bar on the Windows Explorer Search Bar, will bring up Seer Pro, which gets frustrating when you're looking for a file name.

![Annotation 2019-12-24 003713](https://user-images.githubusercontent.com/57867863/71369416-b5705d80-25e5-11ea-83da-3c2905387563.png)

**Comment by ccseer** [comment]
Sorry for the inconvenience.
I will try to fix it in next version

**Comment by ccseer** [comment]
fixed in 2.4.0
