### ISSUE TITLE
win10 不能使用

### ISSUE THREAD

**Issue by qbosen** [ccseer/Seer#24]
win10 专业版，空格没有反应。重新安装后同样没效果。

**Comment by ccseer** [comment]
关掉所有其他软件再试试。应该是被别的杀毒软件或者啥的拦截了。

再看是桌面不能使用还是资源管理器不能使用。

**Comment by qbosen** [comment]
没有杀毒软件  资源管理器和桌面指的是什么，如果是系统的资源管理器 是可以使用的

**Comment by ccseer** [comment]
你是指 Seer 不能在桌面使用???

seer 版本号是多少

**Comment by qbosen** [comment]
在所有地方都不能使用，空格不能触发。 我以为你说进程管理,资源管理器。 0.7.4和0.7.3都试了。

**Comment by ccseer** [comment]
一般这种问题都是 因为别的软件引起的。
如果其他软件确实都关闭了还是不行的话，可以试试 这个。

![image](https://cloud.githubusercontent.com/assets/15963166/16909624/72ab1334-4d06-11e6-9b1c-f923a5738f6c.png)

**Comment by qbosen** [comment]
还是不行，重启也试过了。我朋友能用，我不能。难受。

**Comment by qbosen** [comment]
终于搞好了，虽然没弄清楚什么原因。我用CClean把注册表和系统文件清理了一遍，然后换了个目录安装就可以了。谢谢你的帮助，软件很好用，支持！
