### ISSUE TITLE
Seer issue with Windows 10 version 1909

### ISSUE THREAD

**Issue by brunoalec** [ccseer/Seer#241]
Hi there, I am a happy user of seer from Brazil, also I am youtuber and I pretend to record some videos sharing this great software with my followers (see link bellow), but last week I update my windows 10 to version 1909, and seer is not working well.

I've setup seer 2.3.0 to load when windows startup, and It is... but after I press the hotkey with a image selected, it dont show up the preview window as spectated. After doing some tests I realize the popup window will only open after I click on the seer icon, on the system tray area.

Any tip on how can I fix it, and make work again? 
The previews version of seer was working well, is there a way to download that version to test it here?

![Screenshot_1](https://user-images.githubusercontent.com/12716755/72759184-aca68380-3bb3-11ea-814b-315724b4ad7b.png)

With best regards
Bruno Alecrim
www.tutorialmaster.com.br
https://www.youtube.com/user/tutorialmasterbrasil

**Comment by ccseer** [comment]
Hello~
Have you tried to restart your PC?
The left button click from system tray icon is designed for touch device
If the selected file can be triggered this way, it looks like the problem
is that Seer failed to monitor your Space-bar event.

Or maybe try to launch Seer with a administrator access？

**Comment by ccseer** [comment]
I don't think it would make a difference to go back to old version.
Because I am already working on Seer-2.4.0 now. The old version contains
some bugs when it is checking for updates.

**Comment by brunoalec** [comment]
On Mon, Jan 20, 2020 at 11:05 PM Seer <notifications@github.com> wrote:

> Hello~
> Have you tried to restart your PC?
>

*Sure, also re-installed it*


> The left button click from system tray icon is designed for touch device
> If the selected file can be triggered this way, it looks like the problem
> is that Seer failed to monitor your Space-bar event.
>

*Trying to access the SEER settings, but the menu is not working.*
*See attached image.*


>
> Or maybe try to launch Seer with a administrator access？
>

*I tried, but same result.*


I thought to install previous version, so we can confirm if this issue is a
conflict
with my system config or an issue in Seer 2.3. Just an Idea.

Thanks anyway.
Bruno

**Comment by ccseer** [comment]
Hi
Is the App licensed?

Would you please send me email so I am able to provide the download link of
old version

**Comment by brunoalec** [comment]
On Wed, Jan 22, 2020 at 2:20 AM Seer <notifications@github.com> wrote:

> Hi
> Is the App licensed?
>

I download the free version and every time I start Seer it opens a popup
asking to register.
Can I still use a free version? It is really necessary to register?

[image: Sem Título-3.jpg]


>
> Would you please send me email so I am able to provide the download link of
> old version
>

my email: alecrim.bruno@gmail.com

Thanks
Bruno



>
> On Tue, 21 Jan 2020 at 11:53 PM, brunoalec <notifications@github.com>
> wrote:
>
