### ISSUE TITLE
REQ: could you add an option to disable animations?

### ISSUE THREAD

**Issue by mishaxz** [ccseer/Seer#242]
because on Windows RDP sessions it is slow to view because of the animations

**Comment by ccseer** [comment]
all animations?

**Comment by ccseer** [comment]
That's sad.
I took a lot of effort to add these effects

**Comment by mishaxz** [comment]
the animations when you open and exit the preview... I enjoy them on my notebook, just my remote connection, it's really not enjoyable. Maybe if you have a fast connection but I'm connecting only maybe 5mbps to that server.

so I mean just an option to be able to disable it... would be very nice.

**Comment by ccseer** [comment]
Sorry
The free version Seer-0.8.1 is not updating anymore.
The last one is 2.3.0 which doesn’t have a opening animation

**Comment by mishaxz** [comment]
ok cool... I didn't realize it passed v1
