### ISSUE TITLE
预览webm格式视频卡顿掉帧

### ISSUE THREAD

**Issue by lonelygoneby** [ccseer/Seer#243]
如标题所述。

**Comment by ccseer** [comment]
下个版本会有新的 视频模块

**Comment by chongyunxiang** [comment]
When will the next version 2.4 come?

**Comment by ccseer** [comment]
Not sure.

Working on it now.
I am planning to replace video&pdf module at Seer-2.4.0.

**Comment by ccseer** [comment]
最晚5月. 
换了新的 视频模块， 应该得到了改善。 到时候还有问题再打开
