### ISSUE TITLE
预览文本缩小后无法放大

### ISSUE THREAD

**Issue by QIANWC** [ccseer/Seer#245]
ctrl + 鼠标滚轮，可以缩小字号，它就是无法放大。。。再次打开后并不恢复正常字号，已经小到看不清了。
v2.3.0，关闭了可能有影响的onequick和Logitech options，重装seer后依旧。

**Comment by ccseer** [comment]
呃... 有部分机器会出现这个情况. 还搞不懂为啥.
需要改一下注册表才行

HKEY_CURRENT_USER\Software\Corey\Seer\Text
point_size
我当前的  hex/十六进制值 是 16

**Comment by QIANWC** [comment]
只有我家里的台式机最近出现了这个问题，其他电脑正常。
另外想问一下license验证方法？
我一共有四台设备四个license，设备也会不断升级（换显卡，硬盘，主板。。。），是否可能出现license失效？

**Comment by ccseer** [comment]
主板变了是 肯定会的
其他的一般不会

出问题了可以给我邮件。

**Comment by ccseer** [comment]
改了一下
下个版本更新了你再看看,. 如果还有再打开

**Comment by ccseer** [comment]
Seer-2.4.0 里还存在。

gg

**Comment by ccseer** [comment]
找到原因了。如果屏幕显示有小数倍的缩放比例，会在某些情况下截断小数部分，导致大小不变。

已经修复。发布在 2.5.0 里。

**Comment by ccseer** [comment]
2.4.1 发布了

**Comment by QIANWC** [comment]
稳，不过我电脑刚升级了，license废了，暂时试不了。
大概要买第六个激活码了，可有账户制/浮动许可证的计划？
虽然只是笔小钱，但这样的数字版权接受不了。。。
这问题应该不是个例。

**Comment by ccseer** [comment]
可以给我发邮件啊. 我给你新的 授权

**Comment by QIANWC** [comment]
吼啊，新机器ID
3fd3e19ee9de3d5595515c49b3c8e79596409eed21791803585e1c271b33506c25056578698c33fe810ced868b62464c1433400ad35e0d7bfe8e95bb576041b9

Seer <notifications@github.com> 于2020年5月31日周日 上午12:10写道：

> 可以给我发邮件啊. 我给你新的 授权
>

**Comment by ccseer** [comment]
> 个激活码了，可有账户制/浮动许

突然看到这个了。我最后给你解决了吗？你买了6个授权？我可以给退还5个的费用。能给我发邮件吗？

**Comment by QIANWC** [comment]
好久没看邮箱，实际算是解决了，我后面没有再买license，需要的时候单独发邮件申请了激活码。
希望能够有账户制，挂windows商店也是不错的，比如OneQuick就很省心。

我的实际情况是：
我大概有三台设备使用seer，如果开发搞崩了系统就会重装，硬件大升级也会导致license失效，，所以陆续买了6次。

seer非常好用，多出的费用作为赞助，不必退给我了。
祝学业顺利

Seer ***@***.***> 于2021年11月21日周日 00:27写道：

**Comment by ccseer** [comment]
商店有。 叫做Seer Pro
你可以发个邮件，然后我给你兑换码
