### ISSUE TITLE
Stopped working, after I connected to new windows-network

### ISSUE THREAD

**Issue by sambuev** [ccseer/Seer#247]
Hello, it was working great, now it doesn't work, no matter I restart Windows or just an application, recently I got reconfigured and connected to my work-network, it seems like it the issue, but why network configuration affecting image previews? Please help me to fix it. Windows 10+all updates.

**Comment by ccseer** [comment]
What version are you using?
Maybe you need a license

**Comment by ccseer** [comment]
If you are using 0.8.1, it might be a bug.

If the version is 2.3.0, then it has 3 days free trail
