### ISSUE TITLE
HEIC preview doesn't work in 2.4.0

### ISSUE THREAD

**Issue by bgoupil** [ccseer/Seer#253]
Hi Corey, I just installed 2.4.0 which brings native support for HEIC/HEIF. But when I preview an HEIC image (from an iPhone 11) it brings the generic panel with file information, there is no image preview.

Version 2.4.0 with no plugins installed.
Windows Enterprise version 10.0.18362

**Comment by ccseer** [comment]
If the Seer-2.4.0 is updated from old version, there might be a .dll
conflict.
So you have to manually remove all files in Seer installation folder, then
install 2.4.0 to the same place.

Then everything should be working fine. If it doesn't, please let me know.

**Comment by bgoupil** [comment]
Thank you Corey, it works after uninstalling Seer, removing folder %ProgramFiles(x86)%/Seer and reinstalling 2.4.0.
There's another problem (no fit to window) but I'll open a separate ticket.

**Comment by bgoupil** [comment]
Thank you Corey, it works after uninstalling Seer, removing folder %ProgramFiles(x86)%/Seer and reinstalling 2.4.0.
There's another problem (no fit to window) but I'll open a separate ticket.
