### ISSUE TITLE
HEIC preview doesn't fit to window

### ISSUE THREAD

**Issue by bgoupil** [ccseer/Seer#254]
I installed 2.4.0 with HEIC support and when I quick look an HEIC file from an iPhone 11 the image seems to display with a 1 screen pixel = 1 photo pixel, in other words it is huge and you can't see the full image, just a small element of it (you have to scroll to explore it).
Is it possible that HEIC images fit to the preview window so they can be in full, like is the case for example for JPEG images?

Version 2.4.0 with no plugins installed.
Windows Enterprise version 10.0.18362

**Comment by ccseer** [comment]
Would you please send me a sample file?

**Comment by bgoupil** [comment]
Here is a sample image with the problem (all my iPhone 11 photos have this issue) :
[IMG_5544 2020-01-03 09_58_12.zip](https://github.com/ccseer/Seer/files/4651240/IMG_5544.2020-01-03.09_58_12.zip)

**Comment by ccseer** [comment]
Thank you for your report.

I will keep you informed when it's fixed.

**Comment by ccseer** [comment]
[qtheif.zip](https://github.com/ccseer/Seer/files/4666838/qtheif.zip)


1. quit Seer
2. replace the dll in Seer/imageformats

**Comment by bgoupil** [comment]
It works great, thank you!
