### ISSUE TITLE
Stopped working on connected NAS server

### ISSUE THREAD

**Issue by craigrusso** [ccseer/Seer#255]
The update you just pushed doesn't work on my NAS anymore. I have a bunch of Sound FX ( .wav files) on a Synology NAS. if I search the NAS with windows I could hit space bar and hear the sound. Now when you click space bar nothing happens. If the file is on my local drive it works fine. but no files on the connected server will work now with the space bar click.

**Comment by craigrusso** [comment]
Never mind I jumped the gun. The system just needed a restart to get it working again

**Comment by ccseer** [comment]
Maybe this would help as well.

![image](https://user-images.githubusercontent.com/15963166/93302790-1e130080-f82d-11ea-8df3-e2869fcd6924.png)

**Comment by limbunny** [comment]
tried restarting windows explorer, sadly it didn't work

**Comment by ccseer** [comment]
Is there anyone willing to email me and help me to solve this problem?

1. I can build a new exe file, this file will have more detailed log to help locate the problem
2. all you need to do is
    -  quit Seer
    - remove the Seer.log
    - replace Seer.exe with my newly built Seer.exe 
    - start Seer again and try to preview on a NAS that doesn't work
    - then send me back the log file.

**Comment by ccseer** [comment]
> Seems to be a problem between a “name server” connection the NAS and a “IP Connection”. The first one doesn’t work, the second one does…

**Comment by ccseer** [comment]
I just found that it doesn't work if Seer is running as administrator.
