### ISSUE TITLE
Program can't start MSVCP140_1.dll is missing

### ISSUE THREAD

**Issue by mark2016** [ccseer/Seer#256]
Tried re-installing multiple times.  What am I doing wrong?  I have the licenced version.

**Comment by ccseer** [comment]
what is the last version you can use?

**Comment by ccseer** [comment]
Thank you.
Seer was built with 2019  32bit.

Appreciate your information~
I will look into it.


Thanks

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/83349404-38e96400-a367-11ea-8c90-f76c2e981bfa.png)

**Comment by ccseer** [comment]
this should be fixed in 2.5.0.
Please update.
