### ISSUE TITLE
CR2 AWR NEF RAW 

### ISSUE THREAD

**Issue by AlexandrNazarov91** [ccseer/Seer#257]
2.4.1
Windows 10
The program does not open raw (cr2, awr, nef) files as an image, only info.

**Comment by ccseer** [comment]
Your Seer is updated from old version?
If you are, remove all files then install again. There is a dll conflict
from 2.3.0 to 2.4.0.

I just tried. NEF and rw2 are supported.  ARW can be supported by the
plugin "ImageMagick".

**Comment by ccseer** [comment]
There images are supported by default since 2.8.3.
