### ISSUE TITLE
seer crashing on opening .mp4 files

### ISSUE THREAD

**Issue by patrickpuszko** [ccseer/Seer#258]
Seer (v 2.4.1) will crash everytime i try to preview/play a .mp4 file on my WIN10 desktop (latest version). 
Any ideas? Thank you.

**Comment by ccseer** [comment]
[mdk.zip](https://github.com/ccseer/Seer/files/4755670/mdk.zip)


replace this dll file.

**Comment by patrickpuszko** [comment]
That did not fix it.

**Comment by ccseer** [comment]
Are you sure you replaced the dll correctly?
It's a known bug, and can be fixed with the new dll.
make sure that Seer has quit while you are replacing the file.

Otherwise, please wait for a week. Currently I am working on the HiDPI
support.

**Comment by patrickpuszko** [comment]
Yes, i am sure. Deleted the old, copied the mdk.dll into the main folder. Restarted Seer, rebooted PC. Seer still crashing when hitting SPACEBAR with any .mp4 selected.

**Comment by ccseer** [comment]
I just released Seer-2.5.0.
Reopen this issue if it still happens

**Comment by patrickpuszko** [comment]
The 2.5.0 Update fixed the problem! Thank you
