### ISSUE TITLE
用 seer 打開文件的關閉問題

### ISSUE THREAD

**Issue by kigiron** [ccseer/Seer#259]
你好，近日更新至最新版 (2.5.1) 使用時產生一個問題

新版在 Seer 中，選擇用 Seer 打開文件時 (我通常用於開啟影片) ，會另外開啟一 Seer 視窗。而此視窗無法使用 Seer 的 trigger 鍵關閉，須另行用滑鼠關閉視窗。

舊版本記得是在同一視窗中打開文件故無此問題，請問是否可以讓人選擇在同一視窗中打開文件，或是讓新視窗也支援用 trigger 鍵關閉呢？

**Comment by ccseer** [comment]
http://1218.io/seer/release-note.html


2.4.0 的第一条就是这个功能的改变。
我希望保证同样的按钮行为一致。因为查看 zip/rar 压缩包的子文件功能是在分离窗口中进行的，所以这里文件夹的子文件也是在分离窗口中。

分离窗口，也就是标题栏的右侧的第一个按钮功能，需要通过 ctrl+w 或者鼠标点击来关闭。

此外，主窗口里，当标题栏出现时按下 Shift，可以关闭所有 分离窗口。
[image: image.png]

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/85379848-cf780200-b56e-11ea-9297-e64e0cae04d8.png)

**Comment by kigiron** [comment]
感謝告知

**Comment by ccseer** [comment]
2.5.3 添加了新的 快捷键 和 鼠标方法 满足这个需求

![image](https://user-images.githubusercontent.com/15963166/88472990-935c0680-cf4b-11ea-8f44-43a35ec4bc93.png)

**Comment by kigiron** [comment]
剛更新了2.5.3版，試用了此改動符合我原本需求。
感謝作者。
