### ISSUE TITLE
How to use Seer in total commander?

### ISSUE THREAD

**Issue by D-Zen** [ccseer/Seer#26]
i always use total commander instead of exploler.
How to use Seer in total commander?
Thanks

**Comment by ccseer** [comment]
wait for Seer-0.9.0.

**Comment by ccseer** [comment]
#11

**Comment by Remiol** [comment]
Still does't work in TC

**Comment by ccseer** [comment]
@Remiol  Hi~   this is a duplicate issue.  please visit here : https://github.com/ccseer/Seer/issues/26
