### ISSUE TITLE
Alt+F4 Permanently Closes Seer Preview Window

### ISSUE THREAD

**Issue by WalterRoberts** [ccseer/Seer#263]
Seer v2.5.2
Windows Version 2004 (OS Build 19041.388)

Steps to reproduce:
1. Open any file by hitting space.
2. Click the Seer Preview window itself to focus
3. Press Alt+F4 to close it
4. Try to open another file by hitting space
> No Preview window is opened
> The tray icon is still available, so Seer is indeed still running.
> Currently manual restart of Seer is required to fix this issue

I have remapped Alt+F4 to a convenient hotkey [WinKey+X] and generally close opened windows this way.

**Comment by ccseer** [comment]
Thank you for your professional report.
Will be fixed in next version.

**Comment by ccseer** [comment]
Now try to close with Ctrl+W

**Comment by ccseer** [comment]
Fixed in Seer-2.5.3
