### ISSUE TITLE
SEER - having to re-start app everytime on new system boot

### ISSUE THREAD

**Issue by nat-ai** [ccseer/Seer#264]
Apologies if I am missing something obvious. 

I recently switched from Mac OS to windows and missed the space bar open preview functionality so downloaded SEER - great, works great! 

BUT, I noticed that each time I shut my computer off and reboot, SEER no longer functions. I have to re-open the app before it then works again for that 'session'. 

Is this the normal behavior? I was hoping that once installed it would just work by default and I wouldn't have to keep loading it up each time. 

I'm a complete novice when it comes to code, so I am hoping there is a fix in the app settings somehow rather than me needing to input stuff into the directories etc. 

Thanks in advance. 

P.S if this is the normal behavior, is it possible to add this functionality please?

**Comment by ccseer** [comment]
do you have this option checked?

[image: image.png]

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/88035953-71423d00-cb75-11ea-96d4-5c2b9832a1db.png)

**Comment by nat-ai** [comment]
Hi thanks for the quick response. I don't have any app settings. When I search for SEER in the start menu, all I can do is open the app and it then runs in the background, I'm not shown any start screen or options for the app. When I search/open it again whilst it's running, windows just tells me that SEER is already running

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/88036519-3ee50f80-cb76-11ea-80f4-4bf263e91dfc.png)

Check your task bar in the corner. Right click

**Comment by nat-ai** [comment]
WONDERFUL! Thanks a million. 

I'm still finding my feet around windows and didn't know about this little panel. Again, thanks

**Comment by ccseer** [comment]
Great.
Not what version you are using right now.
Because if it’s a official version, you will have three days free trial,
then it won’t work.

**Comment by nat-ai** [comment]
Oh? It says 0.8.1 version, and I just got it from here:

https://sourceforge.net/projects/ccseer/

I hit the green download button at the top

**Comment by ccseer** [comment]
It’s the free version.
 You can do whatever you want.

FYI, you can try the official version from http://1218.io

**Comment by nat-ai** [comment]
I am confused! So did you not create the version that I have downloaded from sourceforce? It says that it was created by coreyisme

Whats the difference between the version I have downloaded and the 'official version'?

**Comment by ccseer** [comment]
Yes it's me. It's the very old version. The version number is 0.8.1.
The last version is 2.5.2 which is released a week ago. 
You can check the rel-note for all updates: http://1218.io/seer/release-note.html

**Comment by nat-ai** [comment]
Oh ok, all clear! 

FInal question then, if I get the newest version, do I need to delete the old one or will the new version overwrite it?

Again, I'm new to windows so I'm not sure how to completely delete apps etc FULLY from the system.

**Comment by ccseer** [comment]
https://support.microsoft.com/en-us/help/4028054/windows-10-repair-or-remove-programs

It is better to uninstall the old version before having the new version since the version gap is too big

**Comment by ccseer** [comment]
Hi,
I am closing this issue, you can still reach out through email~

![image](https://user-images.githubusercontent.com/15963166/88046426-9e491c80-cb82-11ea-8316-b7ba090306c8.png)


![image](https://user-images.githubusercontent.com/15963166/88046454-b02abf80-cb82-11ea-82c0-6d4a50a0e0bb.png)
