### ISSUE TITLE
Crash when opening .pptx

### ISSUE THREAD

**Issue by wchniou** [ccseer/Seer#265]
There is a crash when opening .pptx, I already downloaded the plug-in provided well.

**Comment by ccseer** [comment]
I just released 2.5.3, however, it does make any difference.

I am planning to figure out a way to solve the MS Office display issue in
2.6.0.

**Comment by ccseer** [comment]
Thanks for your feedback.

**Comment by wchniou** [comment]
Thanks. Just downloaded the latest version.

Sincerely

________________________________

**Comment by ccseer** [comment]
Update to 2.6.0, install oit.
