### ISSUE TITLE
|Feature Request| Seer the annotation in PDF

### ISSUE THREAD

**Issue by wchniou** [ccseer/Seer#266]
I sometimes annotate the PDF, but when I want to seer it, no annotations showed in the window. Could you add this function?

**Comment by ccseer** [comment]
Send me a sample file and a screenshot what it should look like. I have no
PDF editor.

**Comment by wchniou** [comment]
Sure.
![image](https://user-images.githubusercontent.com/68987042/89414051-5fa78a80-d75c-11ea-81f2-8acc76ad93f9.png)
![image](https://user-images.githubusercontent.com/68987042/89414158-88c81b00-d75c-11ea-84e6-37d9b9c7da7d.png)

**Comment by wchniou** [comment]
First one is in Acrobat
Second is Seer

**Comment by wchniou** [comment]
[Review_ Urban Microclimate.pdf](https://github.com/ccseer/Seer/files/5028439/Review_.Urban.Microclimate.pdf)

**Comment by ccseer** [comment]
added in 2.5.4
