### ISSUE TITLE
Key pressed will be passed to Seer after closing

### ISSUE THREAD

**Issue by jcplus** [ccseer/Seer#268]
Windows 10 Pro
Reproduce:

1. Create a sample BAT file and write a comand that close the cmd window when spacebar is pressed.
2. Run the BAT file and see the prompt messgae.
3. Press the spacebar to close the window.
4. Seer will open a preview window of this BAT file.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/91702419-46eb9280-ebab-11ea-9ea9-5382981a2af0.png)


CMD window handles Key_down first, then Seer handles Key_Up event.

**Comment by jcplus** [comment]
That means it's normal?

**Comment by ccseer** [comment]
Yes, it’s expected.
