### ISSUE TITLE
Hide tray icon

### ISSUE THREAD

**Issue by TheJaredWilcurt** [ccseer/Seer#27]
I can't stand having things in the tray that I don't need. I want the app to just run at startup and be permanently running in the background. If I want to change settings I can find it in the start menu. But get the stupid icon out of my tray.

I'm uninstalling until this is added. I'd rather lose the functionality this offers than add another tray icon.

**Comment by TheJaredWilcurt** [comment]
Any reason behind not implementing this?

**Comment by ccseer** [comment]
We can drag it to hide. 
<img width="356" alt="ccedc435-6d50-4b82-9c0f-e7e02000b7d3" src="https://cloud.githubusercontent.com/assets/15963166/18091048/e21f6e3a-6ef9-11e6-8168-5d003df338d1.png">

**Comment by TheJaredWilcurt** [comment]
Like many people, I choose **always show** icons in the notification area of the taskbar.

![always-show](https://cloud.githubusercontent.com/assets/4629794/18097673/da43fb1a-6eac-11e6-8ed8-5d3e2bb8d46d.png)

Benefits to doing this:

* Instant access to notification software. Prevents you from having to click a small target area, scan a randomized list of application icons and target another smaller area that doesn't benefit from Fitt's Law.  Instead, just use muscle memory and Fitts Law to quickly access your tray apps with one click.
* Forces you to acknowledge running software, so you don't end up with 50 icons down there that load on startup that you don't need running all the time slowing your machine down.
* Lets the notification area of the taskbar work for **notifications**, what it was meant for.

Why Seer **should not** be in my notification tray:

* It isn't a chat, email, calendar, or security software that needs to alert me of things on a daily basis.
* It doesn't have any reason to show notifications beyond maybe update alerts. Which probably don't occur often enough to have it sitting there 24/7.

If you aren't giving me notifications, get out of my notification tray.

**Comment by TheJaredWilcurt** [comment]
Are you guys going to fix this?

**Comment by ccseer** [comment]
Sorry.

**Comment by TheJaredWilcurt** [comment]
lame

**Comment by endling9973** [comment]
Hey, nice app, amazingly useful, but I completely agree that the tray icon makes no sense at all. I hope you guys change your mind about this.

Best wish.

**Comment by ccseer** [comment]
Maybe this can be solved by starting Seer with a command line parameter

**Comment by endling9973** [comment]
That would be amazing. Where is the donate button? :)

**Comment by TheJaredWilcurt** [comment]
Couldn't you just add this into the UI, so that *it* runs the CLI option for you? and if you have "run on startup" it would add the CLI args into the startup

**Comment by ccseer** [comment]
@endling9973 
Hi~ there is no donate button.
If you are using a free version(v0.8.1), you can try to buy a license to get v1.2.0.
www.1218.io

I think I will add this feature to v.1.3.0.

**Comment by endling9973** [comment]
I sure will. Thank you so much for the good work.

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/623666/Seer.zip)


Replace your installed Seer.exe,  try  **Seer.exe -i**
