### ISSUE TITLE
开机自启动有问题

### ISSUE THREAD

**Issue by Mosaic67** [ccseer/Seer#270]
开机自启动会弹出未知开发者控制电脑是否确认的确认框，在控制面板->安全和维护->更改用户账户控制设置，调整至从不通知后，开机无法自启动。
1.可否在启动时去掉未知开发者控制电脑的确认框
2.调整账户控制设置后，无法开机自启动

**Comment by ccseer** [comment]
你是开始管理员权限启动了吗

设置 第一页 的管理员权限启动关了就可以了，一般不需要这个，除非你要兼容everything
