### ISSUE TITLE
Seer keeps randomly closing

### ISSUE THREAD

**Issue by rp1231** [ccseer/Seer#271]
Cant pinpoint when but it does happen quite a lot.
Just randomly, I'll press the space bar to see a preview and realize that it is not working.
I don't know if it happens after I put my laptop to sleep or because of the plugins that I have added.
I have added all the 8 plugins to seer.

**Comment by ccseer** [comment]
What version are you using?

Currently, Seer only has 7 plugins

![image](https://user-images.githubusercontent.com/15963166/95431089-4058f380-097f-11eb-9406-3af419e3e080.png)

**Comment by rp1231** [comment]
Sorry meant all 7 plugins.
Was encountering the problem with the last few versions of the app.
Hoped that using the windows store version (2.6.1 uwp+) would solve the issue.
But still encountering the problem so decided to post here.

**Comment by ccseer** [comment]
Email me the log file.
It is placed at tempfolder/Seer/seer.log

**Comment by rp1231** [comment]
Are you referring to the folder named "temp" in the windows folder?
Can't seem to find a folder named seer in that....

**Comment by ccseer** [comment]
Normally the path of Temp folder will be

C:\Users\<username>\AppData\Local\Temp



In order to locate temporary folder in windows 7, follow the below steps:



   1. Click Start, in the search box, type CMD.
   2. Right click on CMD and choose run as Administrator.
   3. In the command prompt type ECHO %Temp%.

This displays the full path of the actual temp folder and you can follow
the path and identify its location by copying the entire path and pasting
it in Run command or in search options.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/95532695-b4dd7200-0a13-11eb-8856-bbed27078448.png)

**Comment by rp1231** [comment]
Sending it immediately after it randomly closed.

**Comment by rp1231** [comment]
Hope you recieved it.
I replied directly to the email and not on github.
Sending a more recent one here again just to be safe.

Thanks
[seer.log](https://github.com/ccseer/Seer/files/5362420/seer.log)

**Comment by ccseer** [comment]
Maybe you sent to the wrong address, it could be found in About-About Seer.

However I got your email and deleted the file for you to protect your data.

**Comment by ccseer** [comment]
You added the OIT plugin, but you moved the folder, so Seer could not find the OIT dir. This is the reason you can not preview office file.

**Comment by rp1231** [comment]
So how do I fix this?
The crashes happen regularly

**Comment by ccseer** [comment]
to preview office files, you need to remove the old one, and add again, at same time, do not move the OIT folder.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/95699293-ab077900-0c76-11eb-94d3-f8a69aad09ab.png)

**Comment by ccseer** [comment]
Do you want to switch to EXE version?
Please email me

**Comment by rp1231** [comment]
I had switched to the uwp version in hopes of solving the crashing problem.
Is it better to use the exe version?

**Comment by ccseer** [comment]
Maybe not.
But I can send you a dev version to see the detailed log. Hopefully it will
help me locate the bug and solve the problem.

Please email me.

**Comment by ccseer** [comment]
The PDF module has a defect which would cause crash. 
I believe this is the reason.
I have fixed it.
The new version is coming very soon

**Comment by rp1231** [comment]
Glad to hear that!
Sorry wasn't able to install the dev version...
I got delayed installing it and then forgot about it.

Looking forward to the new version!

**Comment by ccseer** [comment]
reopen it if it still happens after 2.7.0 released
