### ISSUE TITLE
Option to keep showing title and progress bar

### ISSUE THREAD

**Issue by mickv133** [ccseer/Seer#275]
I like being able to see what file I'm listening to and I also skip through files a lot often looking for specific things.  The fact that the title and progress bars keep auto hiding as soon as you take the mouse off of them can get really annoying.  Particularly for audio, there's no picture to display so the bars are not getting in the way of anything if they were to stay visible, or even display the title in the middle of the box area like on quick look for mac?

If you could include a setting in options, or even just a way to pin the title and progress bars on the main interface and stop them from disappearing that would be greatly appreciated.  

Thanks.

**Comment by ccseer** [comment]
this will be added for next release.

thank you

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/111737353-6da8b680-88ba-11eb-9368-3f6e478eb94b.png)

added option in 2.7.0

**Comment by mickv133** [comment]
thank you so much
