### ISSUE TITLE
高级设置中隐藏托盘图标后如何才能再次显示

### ISSUE THREAD

**Issue by WitherZuo** [ccseer/Seer#277]
在“高级设置”中勾选“隐藏图片图标”后，任务栏上 Seer 的托盘图标就消失了，如果我想让它再次显示请问有其它的办法吗？
（清除设置重新安装除外）
![QQ截图20201222110610](https://user-images.githubusercontent.com/25317916/102844328-2d19d800-4446-11eb-9ab3-9c6380c4f813.png)

**Comment by ccseer** [comment]
最新版  2.6.1

关闭程序后，再打开，图标会显示 5s 。
你有 5s 时间去点图标的右键，再次进行设置。

**Comment by ccseer** [comment]
当然，如果你实在手速不够快，我们可以再来讨论 plan B。

**Comment by ccseer** [comment]
#286 286
