### ISSUE TITLE
建议：增加滚轮缩放图片功能

### ISSUE THREAD

**Issue by pzzzling** [ccseer/Seer#278]
可否增加使用Ctrl+鼠标滚轮缩放图片的功能？
这样可以更方便看清楚图片中的细节

**Comment by ccseer** [comment]
可以缩放，在预览大小喝图片实际大小不一致的情况下。

不支持超过原图的缩放

**Comment by pzzzling** [comment]
可以增加超过100%的缩放吗？这样图片的细小部分也能看得很清楚了

**Comment by ccseer** [comment]
我想想吧。

我个人感情上只能接收缩小，因为放大了会模糊。

**Comment by pzzzling** [comment]
感谢~我觉得可以设置一个上限，能缩放到200%我感觉就差不多了😂

**Comment by ccseer** [comment]
2.7.2 添加了   和 pdf 一样的   适应窗口宽度  / 适应窗口高度  功能。
会方便一丢丢。

当然， 还是不能大过原图。

**Comment by pzzzling** [comment]
还是老老实实用图像浏览器比较好（其实也已经习惯了哈哈哈~）
