### ISSUE TITLE
For some .jpg files, pressing space shows only file details, not the actual photo

### ISSUE THREAD

**Issue by Angelusz** [ccseer/Seer#279]
I didn't see it happening before I looked at the properties page at least once (which I didn't know existed until I toyed around with the app for a bit).

Now, some photos show normal, but some always only show the properties page in the screen, not the photo. I can't get it to show photo instead. When I select a correctly pictured photo and try to 'scroll' to the malfunctioning photo, the app just does nothing.

I've uploaded one of the pictures that shows the issue for me, you can use this to try and reproduce: https://1drv.ms/u/s!AvF2EPeRBE95hLkz8gBN0cbMGtFjtA?e=3ncZwv

**Comment by ccseer** [comment]
What version do you have?
The last version is 2.6.1.
It works fine here
![image](https://user-images.githubusercontent.com/15963166/104259905-57970800-54bd-11eb-9d28-8c85d0730f32.png)

**Comment by Angelusz** [comment]
Odd. I'll do some testing and get back to you! Thanks. :)

Groet, Mark

________________________________

**Comment by Angelusz** [comment]
Well, this is awkward, haha! I downloaded it from 1218.co after clicking the "FREE VERSION" button which pointed to: http://sourceforge.net/projects/ccseer/

The file there is.... a tad older. Apparently I was using 0.8.1. From what I understand now, the normal download button also provides a freeware version? It works now on 2.6.1. Cheers.

**Comment by ccseer** [comment]
the 2.6.1 has three days free trial, after that, it stops working

**Comment by Angelusz** [comment]
Ah alright. So it's intended to be broken on the 0.8.1 version? I haven't yet decided if I'll use it enough to pay 13 bucks for it, and I wonder what'd happen if I upgraded and reinstalled my PC - would I have to request a new code each time?

Best,
Mark

**Comment by ccseer** [comment]
0.8.1 was released 4 years ago. It's a bug and it got fixed in the following versions. I didn't write any bug on purpose.

 if you upgraded and reinstalled my PC, the ID would remain the same, however, you can always email me if anything happened

**Comment by Angelusz** [comment]
Ah I understand, so you just let a deprecated version online as trial software, not so much free software. Thanks for the info! :) I'll consider it as the price feels a bit steep for relatively simple software, and as you well know there's a free competitor I can test a bit more.

Best regards

Groet, Mark

________________________________
