### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by xXReDxSparoweXx** [ccseer/Seer#28]
First I have to say I simply love the program! I also own a Mac and since I use my Windows PC most of the time for gaming and modding I was really missing the "quick look" feature!

I am having some problems with setting up Controls, more specifically on how to actually use this feature of Seer? The Controls.jpg doesn't really do a good job on explaining on how to setup them up or how they even work. I followed the pictures and even made a random txt file and changed the extension to .cpp as shown in the pictures but nothing happens. I saved the txt file to a folder instead of the Desktop since Seer doesn't support the quick look feature from the actual Desktop itself and I couldn't get it to view the txt file when I tried to "Seer" it from the Desktop folder itself.

Any input would be greatly appreciated! All in all great work on the program!

**Comment by ccseer** [comment]
I know it looks different. But you can still understand it. : )


![1](https://cloud.githubusercontent.com/assets/15963166/18084447/e976fa06-6ed9-11e6-9619-60c8fef726a2.png)

**Comment by ccseer** [comment]
The last version is 0.7.5.

Make sure you are using the newest one.

**Comment by ccseer** [comment]
It requires the application you choose must support command line call with a parameter.

All Seer did is to start a process with one parameter. 

For example, in the picture I just provided, I chose the PS.exe and wrote an image extension(JPG) in text field. 
After that, when you are previewing a "JPG" file, you can open this file with PS.exe.

It works as same as you right-clicked the file, then selected a action in "Open with".

![image](https://cloud.githubusercontent.com/assets/15963166/18085376/7f3a298e-6edd-11e6-847d-418fbf28e155.png)

Hope you could understand what I said.

**Comment by ccseer** [comment]
Please let me know if you still don't get it.

**Comment by xXReDxSparoweXx** [comment]
Oh wow! Now I feel like an idiot! When I tried it before I kept putting "CPP" as the extension, since it was the one used in the pictures...omg.

Thanks! =P
