### ISSUE TITLE
【BUG】打开了几次文件预览后会死机

### ISSUE THREAD

**Issue by wchniou** [ccseer/Seer#280]
每次我预览了几次文件以后软件就不再打开，并且图标退出，但是process还在。

**Comment by ccseer** [comment]
你说的死机是指 程序崩溃 吗？

“process 还在" , 你应该使用的是 UWP 版本？
一些情况下，主程序 Seer.exe 肯定是退出了。可能会偶发一些辅助的子进程 hook.exe 会没有正常退出。

**Comment by wchniou** [comment]
没有，seer.exe没有退出，但图标任务消失了

________________________________

**Comment by wchniou** [comment]
嗯，对 程序崩溃哈哈哈哈哈

________________________________

**Comment by ccseer** [comment]
这是 不合逻辑啊
seer.exe没有退出  和 程序崩溃 不会同时出现的。
除非你在 Seer 的配置里设置了 隐藏任务栏图标

**Comment by wchniou** [comment]
但确实会发生。下次要是发生，我截个图吧哈哈哈哈

________________________________

**Comment by wchniou** [comment]
我又试了几下，似乎程序每次打开大的譬如视频文件或者PDF，在它刚加载出来我关掉，再打开其他的类似文件，整个程序就死掉了，然后要手动退出进程重启才可以。另外，我发现，.3gp的视频好像都很卡，并且跳跃播放会死，特别是以前拍的视频。

**Comment by ccseer** [comment]
可以给我发个 3gp 的视频吗

你说的大的视频和 pdf 是多大。 我测试的 视频 几个g 的都没问题， PDF 测试了几十兆的也没啥问题

**Comment by ccseer** [comment]
或者 你看看有没有 C:\Users\********\AppData\Local\CrashDumps     里的 Seer.exe.*.dmp
文件
把最近的dmp文件发给我看看

**Comment by wchniou** [comment]
[Seer.exe.12988.zip](https://github.com/ccseer/Seer/files/6081477/Seer.exe.12988.zip)

PDF差不多50M以上就有了，一般加载界面显示超过2秒的都会崩溃

**Comment by ccseer** [comment]
能把那个 PDF 发给我吗

**Comment by wchniou** [comment]
[Subject Two.zip](https://github.com/ccseer/Seer/files/6089096/Subject.Two.zip)

我选了其他的4个，等在loading的时候退掉，再打开其他的或者原来的，就会闪退

**Comment by wchniou** [comment]
百分百的话是那些需要loading的pdf空格打开关闭再打开，就会闪退了

**Comment by ccseer** [comment]
非常感谢~
<3

**Comment by ccseer** [comment]
能复现了。 谢谢。

**Comment by ccseer** [comment]
已经修复了.

很快就会发布.

这是个严重的bug.
非常感谢.

**Comment by wchniou** [comment]
好的， 谢谢 ，哈哈哈哈

**Comment by wchniou** [comment]
这次更新好棒！我用了很久，没有任何问题，哈哈哈哈！很厉害！

Sincerely
