### ISSUE TITLE
Unable to preview item when path contains " ' & " in Directory Opus

### ISSUE THREAD

**Issue by marqqer** [ccseer/Seer#281]
in Directory Opus, when item path contains ampersand (&) or apostrophe ('), Seer fails to preview it.
for example, when trying to preview file: "X:\©®'& .txt" in DOpus, no Seer preview window was created.
I noticed "%Temp%\Seer\do_listsel.txt" logged:
<item id="10" name="©®&apos;&amp; .txt" path="X:\©®&apos;&amp; .txt" type="0" />
there might be a decode operation required after obtained selected item path by using dopusrt.exe.

**Comment by ccseer** [comment]
sorry
will try to fix this next time

**Comment by ccseer** [comment]
fixed in  2.7.0
