### ISSUE TITLE
【UI 问题】 Column View下，Title Bar会自动弹出遮挡文件

### ISSUE THREAD

**Issue by DanShouzhu** [ccseer/Seer#284]
如下图，正常Tree Virw下，因为有细节栏，自动弹出Title的时候没有问题。
![image](https://user-images.githubusercontent.com/69270923/109378696-bce97000-7928-11eb-8fe7-21a880518018.png)

但是如果在Column View下，如果尝试点击前几个文件时，自动弹出的Title Bar会将内容遮挡住。
![image](https://user-images.githubusercontent.com/69270923/109378764-38e3b800-7929-11eb-840c-08d15480db9c.png)

与issue #275 一样，建议在底部增加一个显示/隐藏Title的功能。

**Comment by ccseer** [comment]
你用的是 0.8.1？

这个问题已经在正式版改过了

[image: image.png]

**Comment by DanShouzhu** [comment]
呃，原来如此。
Thanks.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/109381538-f795dd00-7915-11eb-9fe7-b1ac7f73b533.png)
