### ISSUE TITLE
资源管理器搜索框输入意外触发

### ISSUE THREAD

**Issue by zdongno01** [ccseer/Seer#285]
如果在 windows**资源管理器** 右上角的**搜索框中用输入法输入**中文内容内容, 然后点击**空格确认**会意外触发Seer的浏览, 实际上我是在输入搜索内容, 如果不点空格, 而是点数字键选择就不会意外触发

![Snipaste_2021-03-04_14-42-20](https://user-images.githubusercontent.com/74941983/109922343-2803bf80-7cf8-11eb-8396-1b5f4bda32a7.png)

操作系统 Windows 10 家庭中文版(20H2)
输入法  QQ输入法 OR 微软输入法

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/109931875-643d1d00-7d04-11eb-955f-aa166d95bd7a.png)

**Comment by ccseer** [comment]
能把这个给我看看吗

**Comment by zdongno01** [comment]
Windows 10 家庭中文版 
20H2
19042.844

![Snipaste_2021-03-05_17-02-17](https://user-images.githubusercontent.com/74941983/110092977-2d830780-7dd5-11eb-99fc-e8dbc5d62b4d.png)

![Snipaste_2021-03-05_17-03-59](https://user-images.githubusercontent.com/74941983/110093038-3d9ae700-7dd5-11eb-8cb1-b6ba849a9a0d.png)

![Snipaste_2021-03-05_17-03-37](https://user-images.githubusercontent.com/74941983/110093019-396ec980-7dd5-11eb-8b5f-1555bed83d32.png)

**Comment by ccseer** [comment]
抱歉啊。 
接下来发布的 2.7.0 还不能解决这个问题。

这是个和特定系统相关的 bug。我得搞个虚拟机和特定的系统 iso 才能解决。

2.7.0 的后一个版本肯定能解决。

**Comment by ccseer** [comment]
2.7.1 已修复.
感谢反馈
