### ISSUE TITLE
有大量图片的远程文件夹，加载速度极慢

### ISSUE THREAD

**Issue by aa13058219642** [ccseer/Seer#287]
算是优化建议？
---

### 环境：
- seer：2.6.1+
- 系统： Windows 10 专业工作站版，
  - 版本20H2，
  - 内部版本号19042.844

###  目标文件夹属性
- 属于映射网络驱动器，位于`\\192.168.1.100\Picture\Wallpaper\all`
- 网络传输速度约为100MB/s
- 文件夹内有3万张图，总计37GB，占用空间52GB

![](https://i.loli.net/2021/03/22/PMuaNEoTVWLU7hK.png)

### 问题
按空格打开任意图片时，会卡非常久（30秒左右）
加载完一张图后，每切换一次文件都会卡这么久

但是如果把这3万张图的文件夹放在本地HDD硬盘时（读写约为37MB/s），打开只有3秒不到

---

抓包看了下，有非常多的文件访问，估计和文件遍历有关

**Comment by ccseer** [comment]
好的。
2.7.0发布后我再看下啊。
我要复现这个还真得下点功夫 😄

**Comment by ccseer** [comment]
这个应该是解决不了的。

本地的都有系统缓存。
远程文件夹都是有网络请求的，估计没啥好办法。

**Comment by ccseer** [comment]
Sorry

**Comment by aa13058219642** [comment]
显示一个文件的预览，为啥会触发整个文件夹的遍历？
是不是该用个变量存一下当前路径，没变化的话就不请求文件列表

**Comment by ccseer** [comment]
没有请求文件列表。
预览文件夹也是 点了展开 也才会获取展开的那一层的文件。

可能是因为开了文件夹监控。
控制栏有两个按钮，用于在当前目录切换同后缀名的文件。如果同类型文件消失了或者新增了，会影响 <  > 按钮的行为

**Comment by ccseer** [comment]
设置里  控制栏-显示-导航按钮  没有选中的时候，是不会打开文件夹监控的。
这样应该能快一些。
