### ISSUE TITLE
Preview PDF only shows file info instead the content

### ISSUE THREAD

**Issue by jcplus** [ccseer/Seer#292]
Windows 10
Seer 2.7.0

Press spacebar on any PDF files only shows below information:
Name, size, location, type, opends with, created, modified, accessed, MD5, and SHA1.
No real file content is showing.

**Comment by ccseer** [comment]
Your system language?

**Comment by jcplus** [comment]
English

**Comment by ccseer** [comment]
any PDF file at any path?

**Comment by jcplus** [comment]
Not all PDF files but some. I'm not sure why but I haven't figured out the common part from them yet.
They are in English and Japanese and in different folders (all English paths)
[Uploading 提携を検討している企業 _ AUBA(アウバ).pdf…](Sample file)

**Comment by ccseer** [comment]
it is the file name.

**Comment by ccseer** [comment]
I will try to fix it next verison

**Comment by ccseer** [comment]
rename it to English would solve it

**Comment by jcplus** [comment]
It's weird. Japanese file names wouldn't work at all. English file names must be shorter than certain length. Chinese file names are working fine and not limited by length.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/116406612-6edae500-a863-11eb-9bd8-743f2fae35a3.png)



Don't worry, I am working on it.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/116406681-7d290100-a863-11eb-8d5f-48344ed92674.png)

**Comment by jcplus** [comment]
Thanks. No rush on it as far as there is a temporary fix.

**Comment by ccseer** [comment]
https://bugs.chromium.org/p/pdfium/issues/detail?id=682

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/6409519/Seer.zip)


Hi,
I think I have solved the issue. 
Maybe you can help me to test it?

Unpack the zip, replace the files in your seer_installation_folder.

This version is very close to the one I am about to release.
Please let me know if you find any other bugs.

**Comment by ccseer** [comment]
2.7.1 solved it.

**Comment by jcplus** [comment]
I will try it tonight. Thanks for the great work.
BTW, a little suggestion to add a small feature in it that users swing mouse with enlarge the mouse cursor. That's gonna help a lot on Windows.
