### ISSUE TITLE
[BUG] Video file .mkv corrupt

### ISSUE THREAD

**Issue by wchniou** [ccseer/Seer#293]
当在seer上拖动进度条到最后，再往前拖动的时候，整个程序会崩溃，并且无法自动退出，要任务管理器强制退出

**Comment by wchniou** [comment]
我试的视频是带章节标签的

**Comment by ccseer** [comment]
好的，收到。
 感谢反馈。

**Comment by wchniou** [comment]
![image](https://user-images.githubusercontent.com/68987042/116891534-674f7d80-ac61-11eb-911f-840c32ad616f.png)
我可以拿个redeem code 吗 我一共报了4次吧哈哈哈哈  正好看到

**Comment by ccseer** [comment]
一共5个。
但是有两个是 feature。
还有一个 office 是从第一个版本开始已经被报了很多遍了的。

所以还差一个。

**Comment by wchniou** [comment]
哦哦，应该还有一个的，那时候不知道你有GitHub，是直接邮箱给你的
![2021-05-03_23-00-08](https://user-images.githubusercontent.com/68987042/116893250-53a51680-ac63-11eb-946d-59c2d0f4da49.png)

**Comment by ccseer** [comment]
给我发邮件吧。

**Comment by wchniou** [comment]
给你发了


Sincerely

**Comment by ccseer** [comment]
这个应该解决了. 
2.7.2 发布了还能复现  你再打开
