### ISSUE TITLE
Have to reinstall plugins everytime new version comes out

### ISSUE THREAD

**Issue by rp1231** [ccseer/Seer#294]
I recently installed 2.7.1 and I noticed that all the plugins had become uninstalled and had to reinstall them again.

**Comment by ccseer** [comment]
It’s because you are using Windows store version, and you changed some
settings (not in Seer), after that the data couldn’t be saved.

**Comment by ccseer** [comment]
Some users had the same problem before and they told me that moving the App
to the system driver would solve this.

https://www.addictivetips.com/windows-tips/move-an-installed-app-to-a-different-drive-in-windows-10/

**Comment by ccseer** [comment]
Wait,

**Comment by ccseer** [comment]
Sorry.

I think it is because you have certain security software preventing Seer to read/write register data.

**Comment by ccseer** [comment]
Computer\HKEY_CURRENT_USER\SOFTWARE\Corey\Seer  is the place Seer store `Settings` data

**Comment by ccseer** [comment]
Please email me if it still happens.

**Comment by rp1231** [comment]
Will do
