### ISSUE TITLE
Bug: 一些视频文件无法预览,画面全黑(视频编码:mp4v)

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#295]
测试样本: 使用以下命令转换的视频文件
`ffmpeg.exe -i in.mp4 -c:a copy -c:v mpeg4 -y out.mp4`
使用Seer预览时有声音,但画面全黑

**Comment by ccseer** [comment]
临时目录 /Seer/  里有个 seer_mdk.log 

能发给我吗

**Comment by VierSNV** [comment]
好的:
[seer_mdk.log](https://github.com/ccseer/Seer/files/6433456/seer_mdk.log)
如果方便的话您可以用上面的 ffmpeg.exe 转换一个视频试试,我测试所有视频编码mp4v的视频文件Seer预览时都是全黑画面.

**Comment by ccseer** [comment]
最好能直接把  稳定复现的 那个文件发给我
用  https://cowtransfer.com/ 或者  https://wetransfer.com/

**Comment by VierSNV** [comment]
[out.zip](https://github.com/ccseer/Seer/files/6464900/out.zip)
测试,谢谢

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/118209745-c8662500-b49b-11eb-89cb-d081e0b8d968.png)


好了.

**Comment by VierSNV** [comment]
怎么解决的?还是你那没问题?

**Comment by ccseer** [comment]
是 bug
mft解码有的mpeg4可以有的不行

下个版本发布就可以看到了
mpeg4 会使用软解

**Comment by ccseer** [comment]
新版本已经发布了。
可以给我邮件 领取一个兑换码。

感谢反馈~
<3

**Comment by VierSNV** [comment]
非常开心能领取一个兑换码，谢谢！
周末测试一下新版给你反馈。
Regards.
Seer ***@***.***> 于2021年6月22日周二 下午3:56写道：
