### ISSUE TITLE
Bug: 动态PNG文件无法预览动画

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#296]
动态PNG文件无法预览为动画,只显示第一帧,除非扩展名重命名为.apng
测试样本 https://apng.onevcat.com/assets/elephant.png

**Comment by ccseer** [comment]
默认是根据后缀名来的。
如果后缀名的格式能读到数据就说明数据没问题。

**Comment by ccseer** [comment]
目前所有

**Comment by ccseer** [comment]
目前所有 带动画效果的 jpg 和 png 都是按静态处理的。

**Comment by VierSNV** [comment]
这里可以优化吗,对PNG加一个是否为动画的判断?

**Comment by ccseer** [comment]
试了下。 目前不支持。

以后再看吧

**Comment by ccseer** [comment]
这个就这样了。 png 格式固定的，动画特性应该也是后来加的。如果后缀名是 apng 也是支持的。
