### ISSUE TITLE
图片文件无法使用快捷键 Scroll to top/Bottom

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#297]
其他类型文件如文本,PDF,MD等预览时Ctrl Home/End 可滚动到顶部/底部,但当预览放大的长图时,此快捷键无效。
望修复谢谢

**Comment by ccseer** [comment]
图片就单页，没法使用 Home/End 吧。 图片出现的滚动条只能使用 pagedown 和 pageup。

**Comment by VierSNV** [comment]
放大图片后会出现滚动条,很多下载的图片都是长图,有滚动到顶部/底部功能浏览起来更加方便.

**Comment by ccseer** [comment]
已添加。
下个版本能看到了。



Home/End 控制纵向滚动条。
Enter/Return 把滚动条居中。
