### ISSUE TITLE
Bug: 使用“分离”命令后，无法使用命令行调用方式打开Seer预览

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#299]
尝试使用命令行方式预览某些应用的文件项目，过程中发现一些问题:
以下为了区分：
由Explorer快捷键或使用命令行唤起的Seer预览窗口或命名为**唤起窗口**。
在唤起窗口使用"分离"命令创建的窗口命名为**分离窗口**，也适用于预览文件夹类型项目时使用"用Seer打开选中文件"创建的窗口。
处于以下条件时，命令行方式打开Seer预览失效：
1：仅存在分离窗口时
2：分离窗口在唤起窗口关闭后再关闭
3：唤起窗口和分离窗口同时存在时，最后的激活窗口是分离窗口

**Comment by ccseer** [comment]
程序的核心预览功能已经做的足够了。

下个或者下下个 大版本 会重新写下分离窗口的功能。

**Comment by VierSNV** [comment]
你可能没明白我的意思，问题出在命令行方式打开预览，预览功能本身没有问题。
在上面描述的几个条件下，命令行方式打开预览失效，相同条件下，Explorer使用快捷键预览文件可以按预期工作。

**Comment by ccseer** [comment]
噢，好的
我看到的都是和分离窗口有关，所以我说会重写分离窗口功能。
到时候应该能解决。

**Comment by ccseer** [comment]
改好了
