### ISSUE TITLE
Win 10 虚拟桌面问题

### ISSUE THREAD

**Issue by S7venYoung** [ccseer/Seer#30]
目前在用系统为 Win 10，我习惯使用两个虚拟桌面，一个负责浏览器和工作办公，另一个桌面负责 IM 软件（不要戳穿）。
但是当我在虚拟桌面1使用 Seer 预览图片的时候，切换到虚拟桌面2，虚拟桌面2依然会显示预览图片，必须切回到虚拟桌面1，按下快捷键取消预览，再切换到虚拟桌面2才可以正常使用其他软件，否则预览图片回挡住屏幕。
望解决这个事。

**Comment by ccseer** [comment]
预览窗口获取焦点之后 按下空格 或者 ctrl+w  或者 Esc  都可以关闭窗口啊

**Comment by S7venYoung** [comment]
@ccseer 能不能切换虚拟桌面就自动关闭预览，或者预览画面停留再当前桌面，不再另一个虚拟桌面显示

**Comment by ccseer** [comment]
呃...

这个应该需要考虑考虑

也可能有要跨工作区显示的需求..

毕竟关闭预览这么方便, 这个应还是会先这样

**Comment by S7venYoung** [comment]
@ccseer 所以考虑到了多显示器的情况，但是暂时没有考虑到多桌面的情况是不是（逃，说的好义正言辞...

**Comment by ccseer** [comment]
刚发现 置顶窗口 好像都会一直显示，不论在哪个桌面。

以后应该会有取消置顶选项。。

先关啦~
