### ISSUE TITLE
功能建议: 预览图片时,某些条件下直接显示100%画面而不是显示鸟瞰图

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#300]
Seer预览图片，如果其高度或宽度过大时，会缩小图片使其适应窗口，如果是普通的照片文件，这样的设计很好，可以直接预览到图片的全貌。但一些特殊情况就必须有个放大操作才能查看图片的内容，希望这里的处理优化下，比如浏览长图(如width>=480 && height/width>2)时，直接按100%画面显示。

**Comment by ccseer** [comment]
有些长图片是文字 可能需要这样，但不能是 假设图片的内容。并且这是一个是预览程序，保证整体预览更重要一点。

还有就是需要保证软件行为的可预期性，复杂了判断用户可能会不知道会看到什么。

**Comment by ccseer** [comment]
下个版本提供了 和 PDF 一样的   适应高度  和 适应宽度   功能

这样就看这种图片会方便点
