### ISSUE TITLE
Seer doesnt work on network drives

### ISSUE THREAD

**Issue by limbunny** [ccseer/Seer#301]
Seer doesn't work on network drives like NAS shared folders.

works here:
![image](https://user-images.githubusercontent.com/44810197/117573588-08fb2280-b0d9-11eb-8b0f-1f6d563ef796.png)

Doesn't work here:
![image](https://user-images.githubusercontent.com/44810197/117573555-de10ce80-b0d8-11eb-9ace-888d53649a83.png)

**Comment by ccseer** [comment]
#255
