### ISSUE TITLE
Seer: can't move cursor when opening audio files

### ISSUE THREAD

**Issue by patrickpuszko** [ccseer/Seer#302]
Hi,
The cursor stays at the start of each audio file and won't let me change the position within a track.
Any ideas? Using v2.7.1.

Thanks,
Patrick

**Comment by ccseer** [comment]
Some files may not have duration data. So Seer can not know the exact
length of playing time.

I know some players may allow to change position, but it’s not always
correct.

**Comment by patrickpuszko** [comment]
The exact length is not relevant. I can not scrub any audio file. Before the recent update, there was the possibility to change the position in a track. Now, all i can do is start from the beginning each time.

**Comment by ccseer** [comment]
I’m confused.

Are you saying you want Seer to start playing the file from the position
where you closed last time?

**Comment by ccseer** [comment]
Okay.

Please send me a screenshot of previewing a audio file. Make sure the
controls widget is visible.

**Comment by patrickpuszko** [comment]
<img width="384" alt="Screenshot 2021-05-19 155928" src="https://user-images.githubusercontent.com/66690805/118825713-36a35100-b8bb-11eb-819c-ef099561f9d8.png">

Sorry, for my bad description.
I "preview" the audio file using the spacebar. Although the track is been audibly played, the position cursor won't move. Dragging won't do anything. There is no indication of the playing position. Neither the time indicator "00:00" is changing nor the full length is being displayed.

**Comment by ccseer** [comment]
All audio files or a specific format?

**Comment by ccseer** [comment]
Send me one or two  sample files please.
Via wetransfer

**Comment by patrickpuszko** [comment]
I have send you an audio file. Video files (e.g. mp4 h264) can be opened and transitioned forwards and backwards. Also the time indication is correct.

**Comment by ccseer** [comment]
Thanks for your support. I will check it out and get back to you tomorrow

**Comment by patrickpuszko** [comment]
Great! Thank you.

**Comment by ccseer** [comment]
will be fixed next version. 
sorry.

**Comment by ccseer** [comment]
[mdk.zip](https://github.com/ccseer/Seer/files/6519537/mdk.zip)

replace this file will solve the problem

**Comment by ccseer** [comment]
New version will be released soon

**Comment by ccseer** [comment]
released
