### ISSUE TITLE
Unable to reenter Settings area after hiding tray icon

### ISSUE THREAD

**Issue by iClouds** [ccseer/Seer#304]
**Unable to reenter Settings area after hiding tray icon**

**Comment by ccseer** [comment]
Kill the process.
Start the software again, it will display the icon in the taskbar for 8s.

**Comment by iClouds** [comment]
注册后 重新安装电脑 怎么重新注册  重装系统前已卸载软件

**Comment by ccseer** [comment]
之前的 license 应该可以继续用。
