### ISSUE TITLE
建议csv能不能加个行号，如果不影响性能的话

### ISSUE THREAD

**Issue by arthasgxy** [ccseer/Seer#305]
rt， 影响性能就算了，如果对性能影响微乎其微，建议加个行号会比较方便

**Comment by ccseer** [comment]
文本不是 都可以开行号吗

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/124101078-95024880-da91-11eb-8901-9766a4095e12.png)
