### ISSUE TITLE
建议：希望可以增加cdr后缀名文件的支持，以及增加ArcGIS软件文件（mxd）的预览支持

### ISSUE THREAD

**Issue by baileichao** [ccseer/Seer#306]

**Comment by ccseer** [comment]
发两个 sample 文件我看看

**Comment by baileichao** [comment]
1、ArcGIS软件的mxd文件，估计可能有点儿困难，因为这个后缀名的文件，只是保存了相差数据链接在文件里面，里面所用到的大量数量还要是打开软件去看，就是不知道能不能实现直接用这个mxd文件预览；

2、cdr文件是coredraw软件的矢量绘图格式，和photoshops软件的psd格式是一样的，所有文件都在cdr里面；

3、还加了个office公司出的专业流程图软件visio软件的svg格式文件，不知道能不能实现预览。

 

这三个格式的文件都对应的图片如附件所示。

 

 

 

发件人: ***@***.*** ***@***.***> 代表 Seer
发送时间: 2021年7月8日 12:06
收件人: ccseer/Seer ***@***.***>
抄送: baileichao ***@***.***>; Author ***@***.***>
主题: Re: [ccseer/Seer] 建议：希望可以增加cdr后缀名文件的支持，以及增加ArcGIS软件文件（mxd）的预览支持 (#306)

 

发两个 sample 文件我看看

**Comment by baileichao** [comment]
您好，想再请你看看能不能增加kml和kmz格式的文件预览，这两个文件都是Google Earth软件的，如附件的png格式图片所示，里面有点、线、面数据，点、线、面数据下面的遥感影像是Google Earth软件自带的，不在kml或kmz文件里面，而且点、线、面都是有经纬度属性的。

 

 

发件人: ***@***.*** ***@***.***> 代表 Seer
发送时间: 2021年7月8日 12:06
收件人: ccseer/Seer ***@***.***>
抄送: baileichao ***@***.***>; Author ***@***.***>
主题: Re: [ccseer/Seer] 建议：希望可以增加cdr后缀名文件的支持，以及增加ArcGIS软件文件（mxd）的预览支持 (#306)

 

发两个 sample 文件我看看

**Comment by ccseer** [comment]
github 里是看不到你发的 sample 文件的。

但是
如果你用的是正式版， 2.6.0 以后的版本。安装了 OIT 插件。
你看下这个文件，里面是有你要支持的格式的。

https://docs.oracle.com/outsidein/853/oit/supportdocs/ds_oitfiles_8_5_3.pdf

所以，你只需要安装OIT插件后，在 `后缀名` 那一栏 手动添加 你需要的格式就可以了。（记得点 ✔，然后保存）

**Comment by baileichao** [comment]
有的有支持的格式，比如Visio和coredraw，但是将其后缀名加入到OIT插件里面，虽然能打开，但是打开的显示结果很差，完全无法使用；另外，没有kml格式和mxd格式的，希望可以增加这两个格式的支持，感谢~~~~

**Comment by ccseer** [comment]
第三方程序的自定义太多了，没办法都支持的。
目前只能根据反馈多的来。
所以先关闭这个问题了，以后根据反馈再看处理方式吧。
