### ISSUE TITLE
预览自动换行的文本文件出现无意义的横向滚动条

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#308]
我试了一下这个问题V2.7.1未出现，2.7.2以后版本才有，按道理自动换行条件下不应该出现横向的滚动条啊！
这个滚动条碍眼而且占用预览窗口空间，望修复！

https://user-images.githubusercontent.com/78007725/125919484-85036d88-60d9-4b1b-9231-d9380c5b557d.mp4

非常感谢！！

**Comment by ccseer** [comment]
是的。

特定情况下会出现，还没找原因。

**Comment by VierSNV** [comment]
2.7.1没这个问题啊,查查中间代码的变动

**Comment by ccseer** [comment]
修好了

下个版本就有了
