### ISSUE TITLE
预览后,不能修改祖先(上级目录的上级目录)目录名称,被锁定

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#309]
预览文件后，父目录以上的上级目录都被锁定了,预览文件和父目录反而没影响，望修复！

https://user-images.githubusercontent.com/78007725/125921607-95f5f95c-95fc-4e1a-8b4b-1fec4d6281eb.mp4

感谢！

**Comment by ccseer** [comment]
这种文件， 程序不会一次全部读到内存的。
音视频，pdf，超过3M 的文本，这些文件都可能无限大，都是要显示哪里再根据位置从文件里读了放到内存。 

正在使用的文件不能修改是预期内的。

**Comment by VierSNV** [comment]
但预览文件本身并未被锁定

**Comment by VierSNV** [comment]
预览文件和父目录都可以重命名：
https://user-images.githubusercontent.com/78007725/125923901-b2015b0e-e4e1-416d-bec8-833c03fefa3e.mp4

**Comment by ccseer** [comment]
当窗口目录变化时选中文件应该也会变化吧，然后导致你打开的预览窗口内容变化

**Comment by ccseer** [comment]
事实上，如果上级或者当前文件能改名，说明文件已经读完了，或者被释放了。
上上级改不了名 大概率和 Seer 无关

**Comment by VierSNV** [comment]
退出Seer后上上级目录就能正常重命名了

**Comment by VierSNV** [comment]
希望你那做下测试，是不是预览一个文件并关闭预览窗口后，不能重命名上上级目录，问题就奇怪在锁定表现在祖先级目录上，预览文件和父目录反而不受影响。

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/125927568-8bf8966c-8214-4ec5-ab05-8017ab740046.png)

监控文件夹的问题。
如果每打开一个文件就会监控该文件夹下相同文件后缀的文件。

**Comment by ccseer** [comment]
目前来说关了就可以。

**Comment by ccseer** [comment]
需要在下次另一个文件被触发后才会清理上一次的监控。

已经改好了。
下个版本就有了。

谢谢

**Comment by ccseer** [comment]
这个 bug 有点深了。

谢谢反馈

**Comment by VierSNV** [comment]
问题排查出来就好，感谢及时修复还给了临时解决方案。

**Comment by ccseer** [comment]
你这是什么 资源管理器？

**Comment by VierSNV** [comment]
Directory Opus

**Comment by ccseer** [comment]
> Directory Opus

你这个能用 Seer 直接 空格触发吗

不能的话要看下这个 ： https://github.com/ccseer/Seer/issues/291
