### ISSUE TITLE
注册表文件(.reg)，预览不能正确识别代码页

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#311]
收到了issues Fixed通知，非常感谢您的辛苦工作！！
我再提交几个Seer使用过程中发现的问题：
1.  注册表文件(.reg)，预览不能正确识别代码页，实际编码：Unicode BOM(regedit.exe导出时默认编码)，预览时编码：UTF-16，显示为乱码

https://user-images.githubusercontent.com/78007725/126319991-5152a10d-61ce-4526-8fb6-516e2edbf2c4.mp4

测试文件：
[Reflect.mrimg.zip](https://github.com/ccseer/Seer/files/6848053/Reflect.mrimg.zip)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/126323432-06ae38d8-394c-47fc-94e5-559ca3c61d61.png)


ok了

**Comment by VierSNV** [comment]
为什么字符间这么大的间距？不能按一般编辑器那样显示吗？
