### ISSUE TITLE
预览PDF时，两次点击适应宽度按钮，也会出现作用不明的横向滚动条

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#312]
如题，这个滚动条也没有实际作用，文档是固定宽度的，以前版本没有这个问题，收到通知[issue #308](https://github.com/ccseer/Seer/issues/308) 解决了，把这个也提交一下希望也能统一修复。
非常感谢！

https://user-images.githubusercontent.com/78007725/126321036-10644357-4686-46be-95a8-34bc286252c8.mp4

**Comment by ccseer** [comment]
嗯。 
我知道这个。 
一般多按两次就没了

**Comment by ccseer** [comment]
✔
