### ISSUE TITLE
预览具有rotation flag的Mp4文件时，未按rotation flag创建预览窗口

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#313]
预览Mp4文件时,如果这个文件Metadata中提供了rotation flag，seer会按照rotation flag 信息正确旋转并预览， 但打开的预览窗口却未相应改变，还是使用了原始宽高信息，希望这里加以改进，预览窗口也按旋转后的信息加以创建，比如以下例子，预览窗口直接创建为不带黑边的横向窗口，即后面预览程序QuickLook打开文件的方式。
Seer的视频预览已经很完善了，这只是个小瑕疵，不很麻烦的话希望能优化一下。
再次感谢！

https://user-images.githubusercontent.com/78007725/126331622-66bb1347-7cf7-4ad3-bb30-37f5ddc10cf5.mp4

**Comment by ccseer** [comment]
把视频文件发出来

**Comment by VierSNV** [comment]
[抖音-6507054692361571598.zip](https://github.com/ccseer/Seer/files/6848645/-6507054692361571598.zip)

**Comment by ccseer** [comment]
✔
