### ISSUE TITLE
Seer continually says a new version is available immediately after updating

### ISSUE THREAD

**Issue by martylavender** [ccseer/Seer#314]
**Issue:**
Seer alerts that there is an update available. Once updated, Seer will alert that the same update is available when the application is started. 

**Steps to reproduce**
- Open Seer
- Seer will check for updates
- Seer will indicate a new version is available
- Update Seer
- Restart the computer or restart Seer
- Seer will indicate a new version is available (same version that was just updated to)

**Seer Version:** 2.7.0
**Windows Version:** Windows 10 Build 21H1

**Comment by martylavender** [comment]
I noticed that when updating and then rebooting the computer, Seer states that it is still v2.7.0 even though it just said it updated to v2.7.4.

**Comment by ccseer** [comment]
Maybe try to uninstall then download from 1218.io and install it ?

**Comment by ccseer** [comment]
Before uninstalling, make sure there no Seer.exe in your task manager.

**Comment by ccseer** [comment]
Problem solved?

**Comment by martylavender** [comment]
Havent reinstalled yet. Rebooted as I was changing somethings on my machine. Seer of course popped up and said there was an update.

![image](https://user-images.githubusercontent.com/5631619/127181941-2e2da037-be5a-493a-90d4-8d9b37d05d75.png)

You can see in the screenshot above, Seer is v2.7.4.0.  The updater states I am running v2.7.0. Seer itself shows v2.7.0+

Are there any logs you would like me to grab before I uninstall and reinstall?

**Comment by martylavender** [comment]
I went ahead and uninstalled Seer. Downloaded the newest version from the web site. Installed. Had it check for updates. Shows I have the latest version. Going to reboot real quick and see what that does.

**Comment by ccseer** [comment]
Did you install Seer multiple times on different locations?
Perhaps that’s the problem

**Comment by ccseer** [comment]
The log file is on %TEMP%/Seer/seer.log

**Comment by martylavender** [comment]
Only installed in one location.

E:/AppInstalls/Seer

Attaching logs. 
[seer.log](https://github.com/ccseer/Seer/files/6886857/seer.log)

**Comment by ccseer** [comment]
Did the problem solved after uninstalling?

**Comment by martylavender** [comment]
Sort of.

Reinstalling and then checking for an update resulted in Seer stating I was on the newest version. After rebooting, Seer complains that there is a newer version and that I am still on v2.7.0, which I am not.

**Comment by ccseer** [comment]
Would you please email me?

**Comment by ccseer** [comment]
The license module doesn't work well.

**Comment by ccseer** [comment]
Do you have any security software? 
If you modify the Settings, then click "OK", will these settings be saved?

Anyway, email me to get a UWP version. This can surely solve it.

**Comment by ccseer** [comment]
Btw, the  `+` in version `v2.7.0+` means you are running as Admin.
