### ISSUE TITLE
issue #311 未解决,还是有乱码

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#315]
issue #311 未解决,还是有乱码 ：
![2021-08-01-](https://user-images.githubusercontent.com/78007725/127754746-8985e13b-bdad-4b18-bb7f-a31766400d31.jpg)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/146265015-7c0d556d-ea35-4ef4-844e-7684f44402a3.png)


fixed in 2.8.0
