### ISSUE TITLE
issue#312 未解决

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#316]
[issue #312](https://github.com/ccseer/Seer/issues/312)未解决，滚动条出的跟凶残了，上一版第一次按“适应宽度”还不出现

https://user-images.githubusercontent.com/78007725/127754835-0ea39672-efa7-4f5a-bc2e-eb488f54a57a.mp4

**Comment by VierSNV** [comment]
所有pdf都是这样，应该和具体文件无关，如果你哪没有这种情况，请排查是因为系统缩放设置的原因：
我这的缩放设置：
![image](https://user-images.githubusercontent.com/78007725/131232771-e9484c2b-067e-4469-963c-042e6fbb8f0e.png)
![image](https://user-images.githubusercontent.com/78007725/131232774-740137a7-2203-4a77-acea-210bffdcc582.png)
测试的pdf文件：
[manual.pdf](https://github.com/ccseer/Seer/files/7071597/manual.pdf)

**Comment by ccseer** [comment]
好的， 可能是 高级缩放设置  的原因

**Comment by ccseer** [comment]
中文反馈先关了。
移到这里了。
https://support.qq.com/products/366565
