### ISSUE TITLE
two windows now open using seer (spacebar)

### ISSUE THREAD

**Issue by hdrabkin** [ccseer/Seer#318]
The example shown in screen shot; one large window and one small. pressing spacebar again closes one but not the other. BOth can be closed using the X
Not sure if this is due to a windows update or another (mystic thumbs; I see no options listed for preview in program description)(![Ashampoo_Snap_Sunday, August 15, 2021_17h07m59s_002_](https://user-images.githubusercontent.com/10440080/129492980-7e4920d8-15de-44a6-8170-9b89d722b90a.png)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/133266780-93c46925-1e94-4d63-9182-d5d16b90bf00.png)

The preview window needs the input focus to response to the shortcut. If it is a separated window (F4), it only accepts `ctrl+w`.

**Comment by ccseer** [comment]
Btw, what version do you have? 
Currently, the last version is 2.7.4.

**Comment by hdrabkin** [comment]
Not really sure I understand the comment about input focus. 
I usually tap space bar to open, the spacebar to close. But why am I suddenly getting two windows; 
Interestingly, the problem went away for a while, and now occasionally occurs. 
I am using 2.7.4

**Comment by ccseer** [comment]
the left one is not from Seer.
![image](https://user-images.githubusercontent.com/15963166/133274962-1d33cb5d-8b48-4772-9e4b-34635b8f8af6.png)

**Comment by hdrabkin** [comment]
AH; ok; that is helpful. some other program apparently updated to have a similar function. Just have to find it and shut it off.
