### ISSUE TITLE
希望可以增加锁定功能。

### ISSUE THREAD

**Issue by baileichao** [ccseer/Seer#319]
现在这个选择一个图片，按空格是直接预览了，但是当我预览的时候，如果点击了其它的相关文件，前面的图片预览就变成了点击的那个文件，但是我不想它变化，一直是保持前面选择的图片预览，直接锁定它。要不然有时候不注意，点击其它文件，老是变，很麻烦。

**Comment by ccseer** [comment]
那你就只能按一下 F4 把当前预览分离出来了
