### ISSUE TITLE
Crashes on large files!

### ISSUE THREAD

**Issue by JoachimBarrum** [ccseer/Seer#32]
Hi, I love this app! but when I open psd files that are 500mb+ the program crashes most of the time.

**Comment by ccseer** [comment]
Seer can't open a 500mb+ psd file, that's for sure. 
The large file would make Seer out of memory, then crashes.

I will see what I can do to replace crashes with displaying the file property.

**Comment by JoachimBarrum** [comment]
Ok too bad. it does seem like its trying to open it, but while it starts scaling up the image it crashes. Btw, I had no problems opening images of that size on my Mac. 
PS! my pc has 128gb of RAM and the gpu has 8gb of ram, so I cannot understand that its a ram issue. 

Anyway, if its not possible to fix an display message instead of program crash would of course be better.

**Comment by ccseer** [comment]
Hi~~

There is another solution.

**Comment by ccseer** [comment]
![image](https://cloud.githubusercontent.com/assets/15963166/18378608/8a414bb2-76a0-11e6-9327-cd15cc18949b.png)


![image](https://cloud.githubusercontent.com/assets/15963166/18378615/96f39b58-76a0-11e6-8215-239de9e921d3.png)

**Comment by ccseer** [comment]
Add  the plugin named: AutoCAD.

Add json file  named "plugin_jpg.json" from the AutoCAD plugin folder.

Modify the extension jpg to psd

**Comment by ccseer** [comment]
This will never make Seer crash.

**Comment by JoachimBarrum** [comment]
thanks :) that did the trick. I made one for psd and for psb - and it diesnt seem to crash. It takes forever to convert them though, but I guess thats not something fixable. I dont know how Apple manages to do that fairly instantly.

**Comment by JoachimBarrum** [comment]
also PSD gives me broken result, like this: http://prntscr.com/cfx3i2

**Comment by ccseer** [comment]
Sorry. 

I'm out of ideas

**Comment by JoachimBarrum** [comment]
Np, just thought I ask. Btw I said wrong. Pad works fine. It was psb that gave me the bug. But all in all its a great app and really appreciate you helping me out. Kudos!

**Comment by ccseer** [comment]
Can you send me a 500m+  psd file for testing?

**Comment by JoachimBarrum** [comment]
Sure thing, heres a PSD: https://www.dropbox.com/s/fv14l1v506cg8h7/Ide2.psb?dl=0
and heres a PSB: https://www.dropbox.com/s/fv14l1v506cg8h7/Ide2.psb?dl=0

It is the PSB that got buggy. 
Btw, I think how apple lets you preview such huge images quickly is that it shows the thumbnail image scaled up before converting it to a larger preview. Just a suggestion if you consider adding more features, showing a preview thumbnail image instead of progress dots would be a nice one.

**Comment by ccseer** [comment]
fixed
