### ISSUE TITLE
希望可以增加不支持格式的缩略图内容

### ISSUE THREAD

**Issue by baileichao** [ccseer/Seer#321]
像Quicklook这个软件一样，不支持的格式时，不能预览，但是会有个缩略图，而seer则没有缩略图，希望可以增加，这样感觉要方便一点。

**Comment by ccseer** [comment]
缩略图是 文件图标 吗。 不能预览怎么来的 缩略图

**Comment by zdongno01** [comment]
> 缩略图是 文件图标 吗。 不能预览怎么来的 缩略图

我觉得他是不是想让你把thumbs.db或thumbcache_x.DB里的图读取出来显示?

**Comment by ccseer** [comment]
我知道啥意思了。就是放大图标后图标会变成缩略图是吧。
我考虑一下吧，尽量下个版本加到 未知文件的 table 视图里。

这个先关了，中文反馈移到这里了。
https://support.qq.com/products/366565
