### ISSUE TITLE
Stopped working on NAS server

### ISSUE THREAD

**Issue by yuppegundam2** [ccseer/Seer#324]
Seer doesnt work on NAS(QNAP).

I tried：
・restarting windows.
・restarting windows explorer.

Thank you for your work.

**Comment by ccseer** [comment]
What version do you have?

**Comment by yuppegundam2** [comment]
Version 2.7.4.

**Comment by yuppegundam2** [comment]
If you assign a drive name to the NAS,Stopped working seer.

**Comment by ccseer** [comment]
OS version?

**Comment by yuppegundam2** [comment]
windows10(21H1).

**Comment by ZetaKebab** [comment]
2.8.5, issue still happening. Sadly it's a bit limiting on how I can use the app :( Hope you'll find time soon to fix this!

**Comment by StFl123** [comment]
Hi, I'm still having this problem and it bugs me everyday - loved the plugin, recommended it a couple of times an bought two licenses for work...
...now I accidentally found out: my two coworkers can use it on the nas. I can't. Or to be specific: I can't use it on mapped network drives. If I go to the same drive through the windows network explorer Seer works fine.
Any ideas? I'm on 3.0.1

**Comment by ccseer** [comment]
> now I accidentally found out: my two coworkers can use it on the nas. I can't. Or to be specific: I can't use it on mapped network drives. If I go to the same drive through the windows network explorer Seer works fine. 

Are these paths the same?

**Comment by ccseer** [comment]
Is it possible to record a video for it?

**Comment by ZetaKebab** [comment]
In my case, it doesn't work either way.

**Comment by StFl123** [comment]
> Is it possible to record a video for it?

Actually I already did ... asked an IT friend for help.... anywhere private where I can send you a link?

**Comment by ccseer** [comment]
email me.
You can find the address in "About" dialog

**Comment by ccseer** [comment]
Sorry. I will not be fixed any sooner. I still need time to figure out how to reproduce this bug on my PC.

**Comment by ccseer** [comment]
fixed in 3.3.1
