### ISSUE TITLE
Leaking 20-60mb on every play of VP9 or H265 (hevc) video

### ISSUE THREAD

**Issue by RanHum** [ccseer/Seer#325]
If you preview any (afaik) VP9 video, about 20mb minimum (around 60mb on 4K video rip from youtube) will be leaked every time playback ends, including every repeat, hence for very short VP9 videos it's leaking very fast. VP8 (and other codecs, I suppose) has no such problem for me. I can reproduce this with every webm video downloaded from youtube now, for example

Seer 2.7.4
Windows 10 x64 1909
Nvidia Pascal

**Comment by ccseer** [comment]
would you please send me a sample file?

**Comment by RanHum** [comment]
As I said, any file from youtube will do for me, but I used this for testing: [webm vp9 test file.zip](https://github.com/ccseer/Seer/files/7315938/webm.vp9.test.file.zip)

**Comment by ccseer** [comment]
Thank you~

**Comment by ccseer** [comment]
The bug has been located. It is a bug from Windows. But there is a workaround to fix it.
Please wait until next update release.

Thank you for your report.

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/7488281/Seer.zip)

1. Quit Seer
2. Replace Seer.exe
3. Run again

**Comment by RanHum** [comment]
Just tried, it seems working, on 4k file it will eat a couple of hundred megs steadily and not growing more but will release them gradually afterwards. I think it can pass as fixed if you think so

**Comment by ccseer** [comment]
Yes. The memory is not released immediately. Windows has a way to handle it. 
It takes a while. If you preview an image, then stop previewing. The memory will be back to normal after several minutes.

**Comment by ccseer** [comment]
Fixed in 2.8.0

**Comment by RanHum** [comment]
Hmm, I've just updated to 2.8.0 and again saw a rapid increase in memory consumption, but different kind of, and much more aggressive. This time it's not about repeating the same video - repeats don't leak anything, but the very opening of preview does, codecs the same. Every time I open the same test file for preview seer 2.8.0 leaking 100-130mb (!) of memory, and it's rather harsh, quick browse through media folder can stress system badly enough that I noticed it in the first couple of minutes... And it absolutely not going away. Luckily I still have an installer of an old version for this time

**Comment by ccseer** [comment]
Sorry.
I can reproduce it.

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/7776136/Seer.zip)

This is the new Exe file. 
Please use install 2.8.0, and replace the Seer.exe.

I disabled some advanced features for now, so there will be no memory leak.

I will let you know when it is fixed.

**Comment by ccseer** [comment]
The bug is located. Sorry about that. All  d3d related decoding will leak the memory.  Only  FFmpeg decoder works fine, but it is not that efficient.

**Comment by RanHum** [comment]
Sad to hear that, but can we really do nothing with it? Maybe it depends on Windows version, and mine is affected? Is it possible to switch decoders on demand? Sorry if I distract you, I just want to cooperate

**Comment by ccseer** [comment]
Thank you~

I will let you know when it is fixed.
You can help me test it before I release it.

**Comment by ccseer** [comment]
What graphic card are you using, Intel or nvidia?
I guess it's Intel?

**Comment by RanHum** [comment]
As I said in the very first message, I use Nvidia. I have Intel iGPU too but it's disabled in device manager

**Comment by ccseer** [comment]
[Downloads.zip](https://github.com/ccseer/Seer/files/7835488/Downloads.zip)

1. Quit Seer
2. Replace Seer.exe and mdk.dll
3. Run again

it should work now.
Please let me know if it is working well.

**Comment by ccseer** [comment]
Hi

can you take a look at this issue: #341 

Seems like I have fixed it.

**Comment by ccseer** [comment]
fixed in 2.8.3

**Comment by RanHum** [comment]
Yeah, just updated on my pc, it's not leaking anymore afaics, thank you very much!

**Comment by ccseer** [comment]
thank you for your feedback~~
