### ISSUE TITLE
Problem with office plugin

### ISSUE THREAD

**Issue by parainscricao** [ccseer/Seer#33]
First of all, great job! Congrats!

Facing an issue with the office plugin. After I preview the file, I can not delete it. It takes me a reboot to do so. If you can, please, fix it.

One last thing, it would be better if exists another plugin for (all) office documents. The one avaiable or is fast but too restrict or covers all, but too slow.

All the best!

**Comment by ccseer** [comment]
Since 2.2.0, Seer has three plugins for Office formats. 

1. The worst one if MS Office convertor which converts files to PDF.  
    - it requires local MS Office app (2007 or above)
    - it is really slow
    - it may close the editing file.
    - it support all the formats
    - [source](https://github.com/ccseer/Seer-plugins/blob/master/ms-office/1syt.py)
2. excel2html
    - it supports all excel formats
    - no need local app support
    - fast
    - [source](https://github.com/ccseer/Seer-plugins/blob/master/excel2html/excel2html.py) 
3. pandoc
    - docx odt
    - no need local app support
    - fast

**Comment by chongyunxiang** [comment]
Will there be a plugin for office powerpoint instead of the MS Office plugin? The excel2html and pandoc works really well!

**Comment by ccseer** [comment]
Sorry.
Currently no.
I will try and see what I can do next week.

**Comment by ccseer** [comment]
Update to 2.6.0, install oit
