### ISSUE TITLE
希望作者能增加思维导图xmind格式、c4d格式预览，Thank you! I really appreciate it

### ISSUE THREAD

**Issue by fortitudelucifer** [ccseer/Seer#331]

**Comment by ccseer** [comment]
Xmind 下个版本加，c4d 估计不行吧，除了官方的程序没有第三方软件能打开吧

**Comment by fortitudelucifer** [comment]
感谢感谢！明白了，只是个人的想法，能实施就非常感谢，不行也没关系！软件很棒，已购买正版支持！

Seer ***@***.***> 于2021年11月5日周五 下午10:03写道：

**Comment by ccseer** [comment]
#326

**Comment by ccseer** [comment]
Xmind 的插件
 
https://github.com/ccseer/Seer/issues/326#issuecomment-1014095463
