### ISSUE TITLE
在桌面上的软件按空格不反映。

### ISSUE THREAD

**Issue by baileichao** [ccseer/Seer#332]
如题，桌面上的东西打不开，在文件夹里面的正常。

**Comment by ccseer** [comment]
是不是装了第三方桌面整理程序了

**Comment by baileichao** [comment]
没有安装任何的第三方桌面整理软件，目前的问题是有的时候在桌面上敲空格是可以打开文件、图片的，但是绝大部分情况下没有反应，而在某一个文件夹里面打开文件、图片等，均正常，没有出现不能打开的情况。下图是电脑系统版本。
![QQ拼音截图20211117152214](https://user-images.githubusercontent.com/57392772/142154601-e6b90198-6333-482d-94dc-7c7312837557.png)

**Comment by baileichao** [comment]
并且这几次安装了程序以后，在开始菜单里面没有找到软件，以前的是可以的。

**Comment by ccseer** [comment]
可能是和其他软件冲突了
你们试出来是哪个软件吗

**Comment by baileichao** [comment]
完全无法确定是和哪个软件冲突了，希望可以增加一个冲突检测的功能，如果有冲突，可以给提示一下。

**Comment by ccseer** [comment]
这个真没办法的。只能知道冲突了，但是没办法知道是哪个软件导致的冲突。
