### ISSUE TITLE
vhd文本被识别成vhd压缩包怎么解决

### ISSUE THREAD

**Issue by JayceVane** [ccseer/Seer#334]

**Comment by ccseer** [comment]
?

**Comment by ccseer** [comment]
#333

**Comment by ccseer** [comment]
不是回答了么

**Comment by JayceVane** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    抱歉，刚在GitHub上没找到回复以为昨天的提问被系统吞了，又麻烦你发一遍刚看到邮件才知道作者你回复了，真是抱歉。
    
     
    
        
                    ***@***.***
        
    
    
        签名由网易邮箱大师定制
    
 

    在2021年11月21日 ***@***.***> 写道： 




不是回答了么
