### ISSUE TITLE
打开有些WPS中的word文档，打开是代码格式。

### ISSUE THREAD

**Issue by baileichao** [ccseer/Seer#336]
发现有的word文档，用office打不开，只能用WPS打开，这种word文档用Seer打开的时候，看不到内容，显示的是代码。
![QQ拼音截图20211126095313](https://user-images.githubusercontent.com/57392772/143515149-aefbc69e-efd3-45cf-ad7d-dd27c357bf46.png)

**Comment by ccseer** [comment]
如果 office 都打不开就没办法了。

**Comment by ccseer** [comment]
特定格式的问题是没法解决的。

**Comment by ccseer** [comment]
目前能做的是针对大众的通用的格式。
一些文件格式 存在不同的 文件版本，更有些是商业的公司的私有格式，不知道怎么生成的话很大概率是没办法很好的打开显示的。
