### ISSUE TITLE
helper.exe entry point not found

### ISSUE THREAD

**Issue by D347H7HR347** [ccseer/Seer#337]
hi getting this error.

<img width="380" alt="Screenshot 2021-12-07 095232" src="https://user-images.githubusercontent.com/95664639/144951826-b4ce16da-e3b0-4a60-8b99-fa355faeba56.png">

**Comment by ccseer** [comment]
What is your OS version?

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/145249760-e0a20e77-7f4f-4c2f-a109-56c4b0a383f4.png)

**Comment by D347H7HR347** [comment]
windows 10 pro
19042.1348

**Comment by ccseer** [comment]
I think it was fixed in Seer-3.x
