### ISSUE TITLE
jpeg rotation

### ISSUE THREAD

**Issue by chuckkahn** [ccseer/Seer#34]
Seer displays portrait oriented jpegs in landscape orientation.  Opening in Irfanview displays jpegs in correct portrait orientation. Spacebar-ing with seer displays portrait jpeg in landscape mode.   

p.s.: my neck's getting sore tilting my head to look at these jpegs...

**Comment by ccseer** [comment]
Your jpg is made by a phone or camera, and the  file contains a exif information.  That's why.

I would try to fix thix in the future.

btw, Seer can rotate image file by the **L**/**R** key.

**Comment by ccseer** [comment]
Done.

I can send you a developing version with this bug solved.

**Comment by chuckkahn** [comment]
Yes please.  Thank you.

**Comment by ccseer** [comment]
Need an email address~~~

**Comment by chuckkahn** [comment]
chuck.kahn@gmail.com

**Comment by ccseer** [comment]
Ooops.

Did some tests this morning, found some bugs.

Might be later

**Comment by ccseer** [comment]
Can you send a BIG jpeg image which Seer preview it with wrong rotation.

**Comment by ccseer** [comment]
this has fixed.

**Comment by wss7932** [comment]
I'm running 0.8.1 is there any way I can get a release mentioned above that doesn't rotate photos?
