### ISSUE TITLE
连续预览多个视频后seer崩溃

### ISSUE THREAD

**Issue by Chandler-Lu** [ccseer/Seer#340]
## 环境
![image](https://user-images.githubusercontent.com/18322610/147842772-b0f636e5-d458-4af9-a9d4-e31a1e1a554e.png)

![image](https://user-images.githubusercontent.com/18322610/147842793-1fab0853-3a58-48db-8770-b327070c4a87.png)

## 复现方法
连续预览同一个视频或多个不同视频，6-7次，如视频所示，seer 崩溃（状态栏第一个图标是 seer）
https://user-images.githubusercontent.com/18322610/147842786-f5e852be-dbf5-4c15-9433-36815aea5017.mp4

测试过其他 .mp4 的视频，均能复现崩溃，这里就暂时不上传视频样本了，文件比较大

## 其他问题
如视频所示，暗色 win 状态栏配这个颜色的seer图标非常奇怪，建议允许用户自定义图标颜色

**Comment by Chandler-Lu** [comment]
crash log 因含有敏感路径等信息，以发至作者邮箱 cc.seer+gmail.com，谢谢

**Comment by ccseer** [comment]
感谢。

任务栏图标 应该是 **系统**黑色主题 使用 白色图标，  白色主题 使用黑色图标的。
我发布了才在  虚拟机sandbox 里发现有个  app 主题。

**Comment by ccseer** [comment]
然后导致 程序拿到的数据不对。
![image](https://user-images.githubusercontent.com/15963166/147842888-e2c464a0-2f0f-4678-96ad-0135894b9e28.png)


我下个版本改下。
下个版本快了。

**Comment by Chandler-Lu** [comment]
感谢回复~如果可以的话不知道能否先提供一下2.7.4的版本，因为近期确实有连续预览视频的需求，如果crash的话就比较麻烦，谢谢

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/7797318/Seer.zip)

替换 exe.
![image](https://user-images.githubusercontent.com/15963166/147842940-f734bc3f-83df-4d19-8952-25a3b0a2845a.png)

可以改成 到只有 ffmpeg

**Comment by ccseer** [comment]
最好是 把 appcrash 打包发给我
![image](https://user-images.githubusercontent.com/15963166/147842955-045a049d-1b41-49fc-ab98-06caec1ae9b0.png)

**Comment by Chandler-Lu** [comment]
我的seer崩溃后，这个路径下没有seer相关的appcrash哎

**Comment by ccseer** [comment]
> [Seer.zip](https://github.com/ccseer/Seer/files/7797318/Seer.zip)
> 
> 替换 exe.
> 
> ![image](https://user-images.githubusercontent.com/15963166/147842940-f734bc3f-83df-4d19-8952-25a3b0a2845a.png)
> 
> 可以改成 只有 ffmpeg, 把前面的都删了

先用这个就可以了。 然后把  ffmpeg 前面的删了，只使用软解。

**Comment by ccseer** [comment]
那就不用了。 我也能复现。

你先用上面我发的那个exe。 把 文件替换就可以了。

这是接近完成的2.8.2版本。有其他 bug 可以告诉我。

**Comment by Chandler-Lu** [comment]
> 那就不用了。 我也能复现。
> 
> 你先用上面我发的那个exe。 把 文件替换就可以了。
> 
> 这是接近完成的2.8.2版本。有其他 bug 可以告诉我。

感谢，这个方案已经OK啦，谢谢！

**Comment by ccseer** [comment]
好的。  图标的问题我也刚改了。

**Comment by ccseer** [comment]
https://support.qq.com/embed/366565/blog/543198

**Comment by ccseer** [comment]
2.8.3 之后 bug修复了. 所以 编码那个设置可以改回去了

**Comment by Chandler-Lu** [comment]
> 2.8.3 之后 bug修复了. 所以 编码那个设置可以改回去了

感谢跟进！已经OK啦，谢谢~
