### ISSUE TITLE
Can't disable "The system is muted" message

### ISSUE THREAD

**Issue by nathanshipley** [ccseer/Seer#342]
I use my system muted 90% of the time.  Is it possible to remove the "The system is muted" message or create a preference to disable it?   I usually preview very short movies (less than 5 seconds) and this covers up content.

![image](https://user-images.githubusercontent.com/14170135/148838100-0a566ae9-10c4-40e5-bf58-4ceb5e05370b.png)

Using Seer 2.8.2, Windows 10 Pro.  Thank you.

**Comment by ccseer** [comment]
Sorry.
I will fix it next time.
It will show only once every time you run Seer .

**Comment by nathanshipley** [comment]
Thank you!

**Comment by ccseer** [comment]
fixed in 2.8.3
