### ISSUE TITLE
Could add Command line to show the picture with defined location, size?

### ISSUE THREAD

**Issue by lyscop** [ccseer/Seer#347]
It is so nice that Seer previews the image without activation and does not lose focus on the Explorer.

I want to use another mouse gesture program to auto-show the preview by selecting the picture. 

But Seer preview Window can't resize the picture and set the location near the mouse. I think the Command line is a better way based on the selected picture URL.

So, if it is convenient for you to consider it. 

Best.

**Comment by ccseer** [comment]
Thank you for your feedback.

Currently Seer only supports a few cmd options
![image](https://user-images.githubusercontent.com/15963166/154531194-451ed275-dc2f-476b-bc59-5037fa9f2d0e.png)
