### ISSUE TITLE
Enhancement: Setting to try download files when "Seering" Cloud-only files (OneDrive, iCloud, GDrive)

### ISSUE THREAD

**Issue by reddvid** [ccseer/Seer#348]
Hi, I recently purchased Seer Pro from the Windows Store after using the free competition QL.

My few hours using Seer was great as it was fast and feel lightweight. The only problem was it does not preview locally-available files (cloud-only) when I am inside cloud folders like OneDrive. That is where the former app is capable--it downloads the file to preview.

Now it would be great if there is an option to do this in Seer. Take note to make it an "option" in settings since auto-downloading files is not necessary most of the time so a toggle setting would be great.

Looking forward for this feature soon!

**Comment by ccseer** [comment]
Yes. I changed the feature in Seer-2.8.0 2 month ago. 
http://1218.io/seer/release-note.html

It used to download the file. But when downloading the file, the UI is freezed and Seer is blocked until the file is fully downloaded.

Thank you for your feedback. I will take a look into for futrue update.

**Comment by ccseer** [comment]
I tried again, it's not a good idea. Seems like no way to avoid the UI freezing.

**Comment by ccseer** [comment]
added `load_cloud_files` under `General` group.  the value can be found in `user.ini`
