### ISSUE TITLE
[FR] Dark mode tray icon support ?

### ISSUE THREAD

**Issue by Moyf** [ccseer/Seer#350]
Since Seer supports Theme setting and could switch to Dark Theme:
![image](https://user-images.githubusercontent.com/4013062/157158490-f0879720-9520-462d-bd32-a8d325e9f72f.png)

But the Tray icon would stay black, which would make it hard to be seen in Dark Mode system:
![image](https://user-images.githubusercontent.com/4013062/157158464-a36a687a-daf9-4605-bfd8-1d9ef926e770.png)

So could the icon auto switch with the theme setting and, when set to dark theme, change the tray icon into white ( or light?) color?

**Comment by ccseer** [comment]
what Seer version are you using?

**Comment by Moyf** [comment]
[image: image.png]
2.8.3 From Windows Store

Seer ***@***.***> 于2022年3月8日周二 11:11写道：

**Comment by ccseer** [comment]
What if you restart Seer?

**Comment by ccseer** [comment]
update to 2.8.5

Under the `register`
Computer\HKEY_CURRENT_USER\SOFTWARE\Corey\Seer\Others   

manually add `tray_icon_style`

![image](https://user-images.githubusercontent.com/15963166/167022058-05667b67-c9eb-4e24-bb6f-8ddec219672a.png)

**Comment by ccseer** [comment]
There are three values:   blue    dark   light

In your case, set the value to `dark`
