### ISSUE TITLE
反馈几个bug

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#351]
hello,seer作者,你好!

反馈几个新版本的问题:

1,原来某个版本(应该是 V2.8.0及以前)预览视频、Mp3等媒体文件时,快捷键Ctrl+C 能复制当前画面到剪贴板,更新了新版本发现做不到了，到剪贴板的是一个媒体分辨率大小的全黑画面.

2.Seer设置-高级设置-其他-双击窗口打开文件,这里能不能优化一下,开启此项后,双击标题栏时还是保持系统默认功能-最大化/恢复窗口?

3.[issues 316]( https://github.com/ccseer/Seer/issues/316 ) 提过，浏览PDF时，点击“ 适应宽度”，会出现恼人的横向滚动条，这个V2.7.X应该是没问题的

4.再提一个功能建议: 能否增加视频文件预览时顺时针/逆时针旋转的功能?

现就这些,再问一句,中文的issue您是不希望提交到github上吗, support.qq.com那里我登录有问题.

谢谢

**Comment by ccseer** [comment]
1. 应该是个bug. 下个版本能改
2. 我看下吧. 下个版本应该也能改了
3. 这个复现不了...

兔小巢不需要登录也可以反馈

**Comment by ccseer** [comment]
移动端不需要登陆可以发言.  pc 端不行

**Comment by VierSNV** [comment]
1.谢谢修复
2.再次感谢,另外关于"最大化/恢复窗口", 可否加一个选项:最大化窗口不遮挡任务栏.
3.我也不知道如何复现,我这里如上描述操作问题都会出现,可以的话,尝试[issues 316](https://github.com/ccseer/Seer/issues/316)描述的自定义缩放设置,看能能够否复现,关键是V2.7.X没有这个问题,比较一下代码差异应该更容易定位原因.
4.回复未提及,不知道这个功能实现难度如何

**Comment by ccseer** [comment]
不挡住任务栏也看不到别的软件，因为窗口是置顶的。

第四个再看看。应该可以

**Comment by ccseer** [comment]
1/2/4 已解决. 下个版本更新就有了

**Comment by VierSNV** [comment]
非常感谢
