### ISSUE TITLE
Can't search in File Explorer without Seer opening

### ISSUE THREAD

**Issue by edatorbit** [ccseer/Seer#352]
If I'm typing in the search bar in File Explorer and input a space, Seer automatically opens on top of file explorer to show me the folder I'm in. I'm aware I could change the trigger key to spacebar + another key, but I'm assuming Seer opening while I'm using the search bar is an oversight or a bug.

**Comment by edatorbit** [comment]
I'm using Seer 0.8.1, although this isn't a new issue. It's been like this ever since I downloaded Seer 1-2 years ago. My OS is Windows 10.

**Comment by ccseer** [comment]
Hi 
the old version is not updated anymore.
0.8.1 is released 6 years ago.

**Comment by ccseer** [comment]
The free version will no longer be updated.

for more details, please check here: http://1218.io/seer/order.html

**Comment by edatorbit** [comment]
> Hi
> 0.8.1 was released 6 years ago.
> The free version will no longer be updated.

I had no idea - the app doesn’t say anywhere that it’s not the full version. Is this issue present in the modern version of the app?

**Comment by ccseer** [comment]
No, it's not.

**Comment by edatorbit** [comment]
> No, it's not.
> […](#)

Thanks for letting me know.
