### ISSUE TITLE
Previews not working in Everything

### ISSUE THREAD

**Issue by vivadavid** [ccseer/Seer#353]
Hi!

When Everything (https://www.voidtools.com/) displays the list of files of a particular folder and I click on one, nothing happens.

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer/issues/71

**Comment by vivadavid** [comment]
Sorry, @ccseer ! I looked to see if there was an open thread, but I didn't pay enough attention to the list of results!

It's annoying to have to run Everything with administrative rights, as you get the Windows message. I've tried anyway to make sure it works, but it didn't.

**Comment by ccseer** [comment]
The simplest way to make it work is to

1. Quit Seer
2. Search Seer.exe
3. ![ed3a184149c42f757f43f4204fd1b3c9](https://user-images.githubusercontent.com/15963166/167043970-92fb76a6-72ec-4613-b066-03dc6253727b.png)
4. double click the item in Everything to run Seer

**Comment by vivadavid** [comment]
I've followed your instructions, @ccseer, but it didn't work. In any case, I don't want to take more of your time, as I prefer not running Everything with administrative rights. I hope that, at some point, Seer can work on Everything without enabling them. It'd be great!

Aside from this, I've been trying Seer for a couple of days and it's great!

**Comment by ccseer** [comment]
What version do you have?
Seer version and  Everything version

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/167049758-63099db6-679f-4734-9cd1-37c0bb6775e4.png)

![image](https://user-images.githubusercontent.com/15963166/167049781-61c6642c-36dc-4eba-b791-294e2994b01b.png)

**Comment by vivadavid** [comment]
- Everything (x64): 1.4.1.1015.

- Seer (trial downloaded from the Microsoft Store): 2.8.5.

**Comment by ccseer** [comment]
What version do you have?
Seer and Everything.
