### ISSUE TITLE
Enhancement: Ability to preview Excel enabled macro files and Libre Office spreadsheet (Calc)

### ISSUE THREAD

**Issue by mark2016** [ccseer/Seer#354]
Seer Version 2.8.5+, Windows 10 64 bit.

Hi, for some reason Excel enabled macro files (filename.xlsm) and Libre office Calc files (filename.ods) would not preview, so I added them to the plugins extension list for the existing plugin, as shown:
![image](https://user-images.githubusercontent.com/16224288/167053542-962dd3d7-5743-4286-85d8-09227202aa22.png)

The preview for both of these work fine now.  Is what I've done the correct way to enable this?  Seems like a very easy fix, I think it should be part of the default.

Thanks for a great tool.
Mark

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer/issues/298#issuecomment-832474274

**Comment by ccseer** [comment]
If OIT cann't preview the format, then there is no way I can do it.

**Comment by ccseer** [comment]
Sorry. Only the big tech companies(Google, Microsoft, WPS) can handle office formats. The backend of OIT is not open source project, so I cann't do anything about it.

**Comment by ccseer** [comment]
Next time I need to update the OIT plugin, I will add these formats as part of default extensions.

Thank you~

**Comment by ccseer** [comment]
Sorry, I thought you need help to preview these formats. 

The plugins do not have ability to update. I know it's a easy fix, but I can't update OIT like the main exe.
When the plugin is updated, I will write something about it in the release note.
Currently, there is nothing important that needs a update to fix. And I definitely will add these extensions next time I update OIT plugin.

**Comment by mark2016** [comment]
OK terrific.  Thank you for that, keep up the great work.  It's the link between the extension and the plugin that needs to be addressed, is that something that can be set even if the plugin is not updated?  I was trying to find an ini file or similar where the extensions associated with the plugin can be set.
