### ISSUE TITLE
Opus audio format

### ISSUE THREAD

**Issue by vivadavid** [ccseer/Seer#355]
Hi!

I just wanted to let you know that there's no preview for Opus audio files. I hope you can bring it to a future release!

Thanks in advance!

**Comment by ccseer** [comment]
can you send me a sample file?

**Comment by vivadavid** [comment]
There are some samples here:

https://opus-codec.org/examples/

**Comment by ccseer** [comment]
What Seer version do you have?
I tested three files from the website, Seer works fine.
![image](https://user-images.githubusercontent.com/15963166/185989797-e2955afb-ccb5-49c8-b9c9-46355b334027.png)

**Comment by ccseer** [comment]
The last version is Seer-2.8.5.
![image](https://user-images.githubusercontent.com/15963166/185989956-f2ce6512-e2f9-4418-8625-9149dd5ac3ac.png)
