### ISSUE TITLE
 "L" key doesn't work as expected to rotate the video

### ISSUE THREAD

**Issue by VierSNV** [ccseer/Seer#356]
Hi,
It seems when rotating the video, "L" key doesn't work? "R" worked as expected.

Update:
I found  "L" key may have been a shortcut key for "loop(on/off)" in the past
Functioned properly if assign a new key for left-clock rotating
Close this issue 
thanks

**Comment by ccseer** [comment]
更新的时候 都写在更新日志里  https://support.qq.com/products/366565/blog-archive

**Comment by VierSNV** [comment]
opps, 这里的说明真详细,以后从这里看,谢谢指引
