### ISSUE TITLE
How to disabled UAC message when I set seer on startup?

### ISSUE THREAD

**Issue by ivyncent** [ccseer/Seer#358]
windows 11

**Comment by ivyncent** [comment]
Windows 11

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/171674079-1cc72dcf-e1bd-4eec-8887-7efc4a704f68.png)

**Comment by ivyncent** [comment]
> ![image](https://user-images.githubusercontent.com/15963166/171674079-1cc72dcf-e1bd-4eec-8887-7efc4a704f68.png)

I had checked this option already,but it wasn't working. @ccseer
![checked](https://user-images.githubusercontent.com/5794229/171800044-b120e391-69b8-4ac3-8dbe-4dbb3bbc2dd9.jpg)
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=130151997593304150 skey=@crypt_43fc7332_11f7df243578ea71cb6ee7b19114c85a mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/5794229/171800322-dbfc8baf-ff17-4c9d-85ab-4f9fd4041435.jpg)
