### ISSUE TITLE
Seer crashing on launch

### ISSUE THREAD

**Issue by Ynng** [ccseer/Seer#359]
Currently using version 2.8.5

Seer simply won't start. I've tried reinstalling it to no avail.

A crash dump is generated under `C:\Users\<user>\AppData\Local\CrashDumps` every time I tried to run it.

Opening the dump in visual studio revails the following:

> The thread tried to read from or write to a virtual address for which it does not have the appropriate access

> Unhandled exception at 0x592673DE (igd10iumd32.dll) in Seer.exe.26740.dmp: 0xC0000005: Access violation reading location 0x0931D000.

**Comment by ccseer** [comment]
Can you send me the log file?


![image](https://user-images.githubusercontent.com/15963166/173473343-a68dfed1-4300-4b5f-bbb7-853b1ce26a84.png)

**Comment by Ynng** [comment]
The log ended a few days ago. None of my attempts at launching the program today resulted in any new logs.

These are the most recent logs I could find.

[recent seer.log](https://github.com/ccseer/Seer/files/8896186/recent.seer.log)

**Comment by ccseer** [comment]
no valid information.

Would you please send me an email with a screenshot of your purchase.
I can offer a redeem code of UWP version for you to solve this issue.

**Comment by Ynng** [comment]
That did indeed solve the issue. Thanks!
