### ISSUE TITLE
Cannot recognize color profile correctly.

### ISSUE THREAD

**Issue by DoubleLeeSG** [ccseer/Seer#36]
I don't really know how seer manage to preview .psd files.

It seems that the embedded color space profile doesn't get read properly. This leads to a oversaturated preview picture sometimes, a minor problem, if you have time maybe you can have a look into that.

System: Windows anniversary update 64-bit with calibrated profiles enabled.
Hardware: A wide gamut monitor, calibrated with ICC profile.
Files encountered problems: Embedded sRGB or CMYK color space.

**Comment by coooooooooorey** [comment]
Would you please send me three pictures, the original one, the one it should look like, and the one Seer display

**Comment by ccseer** [comment]
Would you please send me three pictures, the original one, the one it should look like, and the one Seer display

**Comment by ccseer** [comment]
#31
