### ISSUE TITLE
Windows search activation instead of Seer via space key 

### ISSUE THREAD

**Issue by Andreascope** [ccseer/Seer#361]
Hi Corey, 
can't figure this out.. 
Seer stopped working in Windows Explorer: when pressing Space key, the search field in Explorer gets activated and a space character is added into it. 
On desktop, Seer functions properly, without issues. 

Tried completely reinstalling Seer with registry cleaning, upon which the new installation strangely got the previous language and other settings (why actually?). 

Any ideas what to look for? 

Thanks! 
Andreas

**Comment by ccseer** [comment]
What version are you using?

**Comment by Andreascope** [comment]
It's Windows 7 Professional 64 Bit with free version Seer-0.8.1

**Comment by ccseer** [comment]
Sorry. 
![image](https://user-images.githubusercontent.com/15963166/181101589-6d72c465-45a6-4035-8060-4f420d6fc9a3.png)

**Comment by Andreascope** [comment]
Yes, I understand that the free version doesn't get any updates, but so does Windows 7... that's why I don't understand why Seer stopped working in Explorer, and instead the search is being activated...

**Comment by ccseer** [comment]
The problem is that even if we figured it out, there is nothing I can do. 
The code for 0.8.1 is from almost 7 years ago, I lost the original copy since Seer-1.7.0, and I am not able to look into the code now.

**Comment by Andreascope** [comment]
Allright, thanks anyway for your reply!
