### ISSUE TITLE
Update Microsoft Store version

### ISSUE THREAD

**Issue by alient12** [ccseer/Seer#362]
Hi, thanks for the great software. I got Seer Pro from Microsoft Store. Third-Party Integration is not supported on this version yet. please update the MS-Store version or add an option to install the website version and activate it via Microsoft account.

**Comment by ccseer** [comment]
It's been verifying by the Microsoft store.
It should be published in three days.

**Comment by ccseer** [comment]
published

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/189706183-9b2e3d09-f793-4cbf-862b-0f0680b042a3.png)
