### ISSUE TITLE
Fontviewer custom text

### ISSUE THREAD

**Issue by LuisBurdallo** [ccseer/Seer#363]
As this is new to Seer I am not exactly what the correct behavior should be but it suppose to let you write what ever you want, right? It just doesn't let me. It let's you change the font size but the rest doesn't work. Would you mind telling us how this suppose to work? Paste and Clear buttons don't do anything even though they highlight. It also let's you change the style but it doesn't work at all.

**Comment by ccseer** [comment]
There is a paste & clear button
Can't type in the UI.

**Comment by ccseer** [comment]
Updated.
Fontviewer has updated yesterday. It's 1.1.0 now.

**Comment by LuisBurdallo** [comment]
I see thanks. What about the font family style? Anything to make that work?

**Comment by LuisBurdallo** [comment]
Hey 1.1.0 solved that problem. Thanks a lot for pointing that out.

**Comment by ccseer** [comment]
You need copy something before click the paste button.
