### ISSUE TITLE
seer无法启动

### ISSUE THREAD

**Issue by laomor** [ccseer/Seer#364]
你好
本人采用的的是WinToGo的方式部署的系统     会经常在三台设备中切换 。今天在更新完3.0.1.0的时候发现seer软件无法打开了。
提示为CLiP许可证设备 ID 与绑定设备许可证中的设备 ID 不匹配。
请给出解决办法。

![Snipaste_2022-10-04_10-14-53](https://user-images.githubusercontent.com/65330036/193720916-a372a84c-922f-4f92-9983-73a503066eb5.png)

**Comment by ccseer** [comment]
这个应该是微软商店的授权管理。我管不了。

**Comment by ccseer** [comment]
商店版 Seer 不作 授权检查。付款/更新/试用全是微软商店管理的。 我也没办法。

**Comment by ccseer** [comment]
我觉得你这个 WinToGo , 可能大部分软件授权都没办法处理。 或者说你其他的 微软商城的付费软件 都会出现这个问题。

**Comment by laomor** [comment]
好的    我尝试一下其他方法来修复这个问题。
感谢关注……
