### ISSUE TITLE
Suggestion: image files metadata info

### ISSUE THREAD

**Issue by LuisBurdallo** [ccseer/Seer#366]
Would this be possible? It would be a great addition IMO. Specially now with Ai generated images that kind of info is becoming more valuable than ever before.

**Comment by ccseer** [comment]
Click Info button on the title bat. Exif info provided for jpg

**Comment by LuisBurdallo** [comment]
I was looking at that tool 10 min ago but my usual format is PNG. Any chance that can be added somehow?

**Comment by ccseer** [comment]
Can you send me a sample file?
I thought only jpg has exif info

**Comment by LuisBurdallo** [comment]
![Snippet_002](https://user-images.githubusercontent.com/33180658/194192070-ba51e921-a311-4961-bb5a-1c46ece09394.jpg)

**Comment by LuisBurdallo** [comment]
Did you see the info from a PNG offered by the tool exiftool.exe? It shows the extra category "parameters" that my PNG files contain. I guess you can add more stuff if you want? I am not sure about it but the tool I use shows it while Seer doesn't see it.

**Comment by ccseer** [comment]
Can you send me the file?

**Comment by ccseer** [comment]
This can be done in next release, but requires user to install the  `exiftool` plugin. Since it's the same exe file, so Seer can make use of it.

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer-Scripts/releases/download/Scripts/exif.zip

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer-Scripts#property

**Comment by LuisBurdallo** [comment]
Hey thanks for sharing the exif script. Now it seems JXR isn't in the supported format.

**Comment by ccseer** [comment]
you can delete the script from Settings, then modify the exif.py file.

**Comment by LuisBurdallo** [comment]
I added the jxr format but it doesn't work. I am not sure if that format requires doing more than just adding the extension to the python file.

**Comment by ccseer** [comment]
Have you removed the script from settings then add modified script again?

**Comment by LuisBurdallo** [comment]
Yes.

**Comment by ccseer** [comment]
No, the exif script supports reading jxr meta info. Preview and Property are separated. 

The preview for JXR is not ready.

**Comment by LuisBurdallo** [comment]
Sounds good. Thanks for clarifying that.
