### ISSUE TITLE
Filelocator Pro by Mythicsoft

### ISSUE THREAD

**Issue by igorlima1701** [ccseer/Seer#368]
Hello!

I use a software to perform searches in my files and folders. It's called "Filelocator Pro".

![image](https://user-images.githubusercontent.com/69910018/198148042-74e7a8d6-87a3-4fa9-b7b4-1f2aadd6003f.png)

When I have the results of the search and I press the spacebar (with Seer open) in one of the selected files, nothing happens.

Is it possible to use Seer with this software?

I think it could be possible since I can use Seer with "everything" by voidtools and with "xyplorer".

Sorry if I'm mistaken.

Any help would be much appreciated! Thank you!

**Comment by ccseer** [comment]
Xyplorer is supported since Seer-2.8.6.
Everything is also supported years ago: https://github.com/ccseer/Seer/issues/71

**Comment by ccseer** [comment]
I think you need to contact with Filelocator Pro. There is nothing I can do inside its software.

**Comment by igorlima1701** [comment]
Like you said. Xyplorer and Everything are supported. So I thought Filelocator pro could be too. Why both those programs are supported but Filelocator is not?

**Comment by ccseer** [comment]
Not many users ask. 
Too expensive. 
No API provided from FileLocator pro.
This is the first time I heard about this software.

**Comment by igorlima1701** [comment]
I see, thank you for the response.

**Comment by igorlima1701** [comment]
That case would be the same for the software called [Tabbles by Tag Forge](https://tabbles.net/about-tabbles/) ? They seem to have an [API ](https://tabbles.net/topic/tabbles-api-v4-start-here/)

**Comment by ccseer** [comment]
Their API are not useful for Seer. Seer needs to get the current selected file path.

**Comment by igorlima1701** [comment]
I see. In Tabbles it's possible to right click and get the path of the selected file.
