### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by hersing** [ccseer/Seer#37]
Hey.

Love your app, but it would be nice if it was possible to change file types. 
As a webdesigner i use TypeScript (.ts) which is plain text, so it would be nice to be able to remove the .ts from "media", and add it to "text"

-Daniel

**Comment by ccseer** [comment]
But, TS is  media file type too.

You can write a little program, simply replace the file extension **.ts** with **.txt**. Or **.js**, so the script can use JS highlight.

1218.io/plug-in.html

**Comment by hersing** [comment]
So should that be written in Py?

and how would the code look?

`nconvert.exe -out js -o /Path/*.ts /SeerPath`?

**Comment by ccseer** [comment]
It doesn't have to be a python.

Seer simply replaces *SEER_INPUT_PATH* with the triggered file, replaces *SEER_OUTPUT_PATH* with the saving path.
Then start a process to execute with cmd.exe.

If you can convert it with a command line in cmd.exe, it should be working in Seer.

**Comment by ccseer** [comment]
I will make a plugin in next version for this situation .

**Comment by hersing** [comment]
That sounds great. Thanks for a great app by the way

**Comment by ccseer** [comment]
fixed
