### ISSUE TITLE
FILE PERVIEW cant works in 22H2 stacked tab

### ISSUE THREAD

**Issue by BearBearian** [ccseer/Seer#370]
FILE PERVIEW cant works in 22H2 stacked tab

**SPACE KEY only can preview files in first one tab**

**Comment by ccseer** [comment]
Not sure what version you are using, but I guess it's the old ones.
![image](https://user-images.githubusercontent.com/15963166/199313115-aaa859e8-0adc-4129-a577-7d5923c3aaae.png)
