### ISSUE TITLE
OIT plugin(MS Office 365) not working properly, doesn't preview file

### ISSUE THREAD

**Issue by Scrutape** [ccseer/Seer#373]
Running Windows 11 Pro, downloaded and connected the OIT plugin, won't process previews for office documents, stays on window with 3 dots moving.

**Comment by ccseer** [comment]
are your office files created by Office 365?

**Comment by Scrutape** [comment]
They’re local files created through the installed Office applications, the license is from Office 365 through our company’s Office 365 tenant.

**Comment by ccseer** [comment]
I think is can be fixed by replacing the dll files
![image](https://user-images.githubusercontent.com/15963166/205128910-c828eb3d-77f0-4a59-abf6-ca64497d2143.png)

**Comment by ccseer** [comment]
[redist.zip](https://github.com/ccseer/Seer/files/10135096/redist.zip)

Last time I try these new dll files, it failed to work with dwg. So the OIT-1.2.0 is still with old dll files

**Comment by Scrutape** [comment]
Will it be updated soon? Otherwise what DLL files should I replace? All of them in the linked zip?

And what’s the directory? Can’t find that documented anywhere, I got this from the Windows Store as recommended.

**Comment by ccseer** [comment]
Under your OIT plugin folder, there is a exe file called  OitViewer.exe.
You put all files from the zip to that folder, these dll files should be at the same level with OitViewer.exe.
I didn't test it, but I think it's better to make a copy first in case it doesn't work.

**Comment by ccseer** [comment]
It will not be updated soon. OIT-1.2.0 has 8.5.5, the latest dll files are 8.5.6, it only doesn't have many improments.
I will write anything important in the release note which you can see when you update.

**Comment by Scrutape** [comment]
Just moved the DLL files and unfortunately it didn’t fix the issue.

**Comment by ccseer** [comment]
I will let you know when I fixed it.

**Comment by ccseer** [comment]
can you send me some sample files?

**Comment by modell3000** [comment]
Hi, has there been any progress on previewing Office 365 documents? I've just installed Seer and it's great except for being able to view these docs - which is a pretty big omission.

**Comment by ccseer** [comment]
it might be fixed in 3.3.0. the new plugin OIT-1.3.0 has that issue fixed.

**Comment by ccseer** [comment]
let me know if it still doesn't work
