### ISSUE TITLE
View Files as they would be in their default application

### ISSUE THREAD

**Issue by Andrew6166** [ccseer/Seer#38]
Why not if you view a for example .html file, there should be two views in my opinion.

- First view: The raw html code or text.
- Second View: HOW THE HTML LOOKS IN A BROWSER ENVIRONMENT
- The point of this being so you can see how it looks in a browser without a browser.
- It doesn’t have to be too detailed. (I.e. loading external css files and external javascript.) That I agree is too much for the simplicity of the Seer Program. But at least understand inline-css or something to that extent
- But formatting strings of text according to the html tags would truly be great and helpful.

I am aware of this feature being developed, and will possibly be available in the next version or coming versions of Seer!

**Comment by ccseer** [comment]
I'm not making any promise.

I'm just saying Seer can view the html code of converted Markdown. And yes, it will be used in raw Html file type after I solved the crash bug when the file is too large.

**Comment by Andrew6166** [comment]
Sorry got a little too excited

**Comment by ccseer** [comment]
Done. Will be included in next version.
