### ISSUE TITLE
Preview of file when being in file dialog

### ISSUE THREAD

**Issue by Inatine** [ccseer/Seer#385]
Is it possible to implement file preview from file dialog? Similar functionality is available on Mac (see the attached files)

![like this 1](https://user-images.githubusercontent.com/73850030/211654909-413e5f32-1de4-429b-9fdc-f4f3fe220856.jpg)
![like this 2](https://user-images.githubusercontent.com/73850030/211654915-2ffe3995-8668-44d9-bcec-ca4a13a2bdec.jpg)

**Comment by ccseer** [comment]
It's implemented. But not going to work if you are using Microsoft Store
edition.

**Comment by Inatine** [comment]
I suppose the reason for that is Microsoft Store sandbox cutting off some permissions? Is it possible to activate Seer outside Microsoft Store to bypass MS sandbox if I bought it there already? That functionality is quite important for me.

**Comment by ccseer** [comment]
Possibly not  as far as I know, MS Store takes part of every purchase, I doubt they would allow user to do it.

**Comment by Inatine** [comment]
I saw that Microsoft Store version has "slight differences" but they weren't listed, so it sounded like the differences were rather cosmetic.  Unfortunately if I knew that this particular functionality is missing and without ability to be added due to MS policies, I wouldn't buy MS version and would rather prefer Win32 version, as ability to preview files in file dialog is quite important to me, as I spend a lot of time there looking for files from Photoshop level.

Shouldn't things like that be listed on the page? I'm now most probably unable to return purchase on MS (they will say that they are not responsible for differences between software versions available on other distribution platforms, which is actually expected as I would say the same thing in their place) to buy it again through PayPal, so I'm left without file dialog preview unless I buy it twice :(

Isn't it possible for Microsoft to give some additional permissions for Seer outside their standard sandbox rules so it works through Microsoft Store too?

**Comment by ccseer** [comment]
I can offer a one-time license key for win32 edition.
Please email me if you are interested.
