### ISSUE TITLE
Cannot preview the EPS files

### ISSUE THREAD

**Issue by Inatine** [ccseer/Seer#386]
Hi again Dev!
I think I found a bug. 

I tried open EPS files (few, to ensure myself that it's repeatable), but it looked like this:
![EPS FILE WITH PLUGIN EPS2PNG](https://user-images.githubusercontent.com/73850030/211838386-c3964567-0db2-4b19-98a6-e41c0f56cc87.jpg)

I got confused, because I remembered that the plugin for this extension was installed. So I checked it and I was, actually, using plugin eps2png
![PLUGINS](https://user-images.githubusercontent.com/73850030/211838586-1c4c5d52-6f23-4485-83a5-b41e1049ae50.jpg)

Now I got confused even more, because I had vivid memory of this working before.
I restarted my computer and Seer also. It did nothing. So I added eps to OIT-1.2.0 and it worked:
![EPS WITH OIT PLUGIN](https://user-images.githubusercontent.com/73850030/211840043-8b3db04d-200e-456e-9b2b-1abfead3dfc0.jpg)

BUT with bigger EPS files it doesn't work. It's just loading over and over again, never actually showing up the proper image. 

Is it bug or some other issue? It behaves the same on MS version and Win32 version.

**Comment by ccseer** [comment]
sometime the plugin contains bugs as well. But I don’t have the code of these plugins, so nothing I can do.

**Comment by Inatine** [comment]
I checked on some old version and on 2.8.3.0 eps2png worked fine. Not the BEST, but decent. At least on those files I attached on screens above.

**Comment by ccseer** [comment]
I noticed that something changed in last release.

you can add a space in the argument
![image](https://user-images.githubusercontent.com/15963166/212786192-0891b8d1-6fb3-436d-bec8-906bbb2bfb15.png)

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/212789299-6472dd85-8853-4021-85c8-90e8d4a3067e.png)

**Comment by Inatine** [comment]
Yup, it works now. The result is not always the best, but in most cases it works okayge ![Okayge](https://user-images.githubusercontent.com/73850030/212857694-dea90ffe-4e87-4e29-b5be-db26edf6d5c6.png)


Here you have the example of "not the best" case
![obraz](https://user-images.githubusercontent.com/73850030/212857083-dc13e829-05ab-41a2-a0ea-6b283b99cc89.png)

**Comment by ccseer** [comment]
It shows you are using OIT plugin to preview eps. But I can't preview it on my laptop.
My solution was for eps2png.
