### ISSUE TITLE
Smoother scrolling when preview word docx files ?

### ISSUE THREAD

**Issue by jiewangjs** [ccseer/Seer#387]
Hi, great respect for such a nice product.
But as my title points out, right now the scrolling of docx files are relatively jumpy, not smooth at all.
Hope it can be improved to the scrolling smoothness level comparable to that of the pdf files.

**Comment by ccseer** [comment]
Currently, there isn't much that can be done within the Office plugin. In some time, the code for this plugin will be made available on GitHub.
