### ISSUE TITLE
Customizable display font

### ISSUE THREAD

**Issue by blunznjoe** [ccseer/Seer#39]
Hi,

First thing's first: Great job! I have been looking for a decent Windows based Quick Look application for quite some time.

Maybe I missed it, but is there a way to configure the display font for plain text files? Programming related files (.java, .xml, ...) seem to be displayed in a fixed-width font on my PC, but .txt files are displayed using a proportional font. It would be great if one could configure the font type and size for all plain text files.

As a second step, customizing the font type and size used for displaying binary file information would also be appreciated. Are there any plans to introduce font customization in future releases?

Installation:
* Windows 7 64bit
* Seer 0.8.0

Thanks,
Karl

**Comment by ccseer** [comment]
May provide a interface to customize font type, but not size.

**Comment by blunznjoe** [comment]
That would be great!

Cheers,
Karl

**Comment by ccseer** [comment]
added.

**Comment by ccseer** [comment]
I did some tests. 

Due to Seer's UI depends on font, and some fonts would make Seer unusable. So can't provide this feature for now.
I'm sorry.

But, text type and app will use the same font now.

**Comment by blunznjoe** [comment]
Thanks for the update!

BR,
Karl
