### ISSUE TITLE
Feature request: Enable text selection when previewing PDF

### ISSUE THREAD

**Issue by gemiware** [ccseer/Seer#396]
I've used the non-pro older version for a long time. Upgraded to the pro microsoft store version and I can't select text anymore from the PDF preview.

Can you implement this?

Kind regards,

Gemiware

**Comment by ccseer** [comment]
Sorry. no.
Will only allow to copy the whole page.

**Comment by ccseer** [comment]
The current implementation is designed to achieve the best balance between memory usage, speed, functionality, and code complexity.

**Comment by ccseer** [comment]
sorry about it
