### ISSUE TITLE
目前发现的关于0.6.0的bug

### ISSUE THREAD

**Issue by PaaandaChen** [ccseer/Seer#4]
* 当打开设置页面的时候，无法使用seer  
我本来是想一边看快捷键一边试的，结果seer用不了了。

* 在seer中按了s后（就是“用seer打开”的快捷键），其他快捷键貌似全部失效了。

**Comment by PaaandaChen** [comment]
系统是win10-64位

**Comment by ccseer** [comment]
第一个是这么设计的.. 

主要是 settings 里面有一些地方需要弹出  文件对话框   选择文件..如果不阻止的话就会在触发时崩溃..还没找到原因..

后来看了下，很多软件的设置基本都是个 模态对话框 ， 会阻塞后面的界面。

所以在设置窗口出现的时候就这样了。。

------
第二个，我明天去试试才知道。。

:+1:  :smile:

**Comment by PaaandaChen** [comment]
好吧，原来是个feature

**Comment by ccseer** [comment]
第二个问题是这样的。

显示pdf 的时候，pdf 的快捷键才有效果，显示 图片的时候，图片的快捷键有效果，显示文件夹的时候文件夹那一块的快捷键才有效。。

刚刚发现 目前显示文件夹内容的时候会出现 快捷键 和 字母键定位内容  冲突。

所以这个应该会在下个版本更正。 到时候大部分快捷键会加上一个修辞按键。

非常谢谢。
应该没啥问题了。我现在做安装包发布了。
