### ISSUE TITLE
AIFF-support

### ISSUE THREAD

**Issue by lehtiniemi** [ccseer/Seer#40]
Hi!

Would love to see AIFF-support in Seer. I work a lot with audio files and people cross-use WAV and AIFF in film stuff so I have lots of both.

Any chance for this in the future?

**Comment by ccseer** [comment]
added.

But here is the bad news.  http://1218.io/note.html

**Comment by lehtiniemi** [comment]
Ah you mean that it will cost? I can live with that. :)

**Comment by lehtiniemi** [comment]
Thanks!
