### ISSUE TITLE
许可证问题

### ISSUE THREAD

**Issue by summerlotus513** [ccseer/Seer#400]
目前看到是一个激活码可以激活10台设备？
但是对于我来说，可能会有重装系统的需求
那重装系统后重新激活还是需要占用一次激活的名额么~

**Comment by summerlotus513** [comment]
At present, one activation code can activate 10 devices?
But for me, there may be a need to reinstall the system
Then reactivate after reinstalling the system, do you still need to occupy the quota for one activation~

**Comment by ccseer** [comment]
是的
