### ISSUE TITLE
Seer as a External Viewer in Total Commander

### ISSUE THREAD

**Issue by Tridy** [ccseer/Seer#401]
Hi.
I have setup Seer as the "External Viewer" in Total Commander with F3.
Compared with other viewers, I think that Seer is trying to send the focus back to the host. So, in order to close the Seer I need to click on it first (focus it) and only then pressing Esc will work to close it. What i want:

1. select a file
2. press F3 to show it in Seer
3. press Esc to close it  

so for now I need to click/focus Seer between steps 2 and 3

so it would be nice to have a parameter to Seer.exe something like /keepfocus or similar.
or have I misunderstool how Seer works with the window focus?

Thanks!

P.S. By the way, it works if I use F3 again in step 3 (without the need to focus), but I would like to use Esc instead.

[![seer-in-tc.png](https://i.postimg.cc/0rJGvP6K/seer-in-tc.png)](https://postimg.cc/0rJGvP6K)

**Comment by ccseer** [comment]
In next release, there will be a new key, `enable_esc_key`, in User.ini, user can press `Esc` to close the window even when it does not have the input focus.
![image](https://user-images.githubusercontent.com/15963166/236829881-0ef5c5b7-7b11-4acc-8cfb-d923c5fc2904.png)
