### ISSUE TITLE
Seer does not work in open or save file dialog windows

### ISSUE THREAD

**Issue by RYJASM** [ccseer/Seer#406]
**Issue:** Open chrome or any app that can open a file dialog window. Navigate to a page/screen that opens a file select/upload dialog window. Notice that Seer does not respond as normal when selecting an image file in the explorer file select dialog window, and hitting the spacebar key.

**Expected outcome:** Seer would show a preview of a file selected in the open file dialog box.

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer/wiki/9.-Misc


Limitation of Microsoft Store edition
Unable to respond in Open/Save dialog due to the MS Sandbox
