### ISSUE TITLE
Preview .go file garbled

### ISSUE THREAD

**Issue by seedpower** [ccseer/Seer#407]
Windows version: Win11 Home Chinese edition
Seer version: 3.2.1+
Attachment: [main.go.zip](https://github.com/ccseer/Seer/files/12192487/main.go.zip)

![image](https://github.com/ccseer/Seer/assets/11022830/db3a4278-51fe-403b-8311-af73f01c18a4)

**Comment by ccseer** [comment]
？

**Comment by seedpower** [comment]
I already solved it because of encrypting software.
