### ISSUE TITLE
Delay showing of the progress indicator

### ISSUE THREAD

**Issue by mike-odom** [ccseer/Seer#408]
When I'm quickly moving through files, I'd prefer to not see the flicker of the progress indicator dots. In the case when the loading time is barely perceptible to my eye, the loading indicator is unnecessary and distracting.

https://github.com/ccseer/Seer/assets/5105729/fea427b2-4793-4a40-9333-555b1acf43d1

Something I've done in the past with web apps:

```
loadFile(imagePath, () => showFile());

setTimeout(() => if (fileNotLoaded) showLoadingIndicator(), 100);
```

It's nice to leave the previous preview image there, or at least start a fade on it. If not, there will be a flicker between the previous preview and then empty space, then the new preview.

**Comment by ccseer** [comment]
It's the same Object. Every file is previewed with a new Object. 
When loading a new file, the previous Object is deleted.

**Comment by ccseer** [comment]
fixed in next release
