### ISSUE TITLE
Directory Opus Not Previewing XLSX

### ISSUE THREAD

**Issue by plasticchinchilla** [ccseer/Seer#409]
This is a weird one.  Using File Manager (Windows 11 Pro) Seer works perfectly with the OIT plugin installed.

I use Directory Opus though and everything is working great there EXCEPT it refuses to preview XLSX files.

I see this thread on GitHub where Corey - you say "Looks like I have done everything I can to be compatible with Dopus." but it seemed the issue wasn't resolved.  

https://resource.dopus.com/t/seer-pro-is-not-working-on-windows-10/40705/25

I'm not a programmer so the conversation is beyond me but is there anything I can do to resolve this?

I have tried running DOpus with UAC mode, but that makes no difference.

Thanks

**Comment by ccseer** [comment]
if it's a single file format, I'm not sure what the problem could be,

**Comment by ccseer** [comment]
hi, it's not going to work if you  run DOpus as Administrator.
