### ISSUE TITLE
Crash on unknown video formats

### ISSUE THREAD

**Issue by Hubcube** [ccseer/Seer#41]
Hey there!
Being forced to use Windows at work after many years under OS X, your software is a blessing! Thanks a lot!

Here's my problem : I'm always rendering my videos in the Cineform codec in a Quicktime wrapper. Seer doesn't read them, which is normal, even VLC needs a plugin for that. But instead of displaying nothing or just telling me "I do not recognize the file type", it crashes (and displays nothing. No window with loading sign). I then need to kill the process and restart Seer.

Thanks again, I really appreciate your work!

**Comment by ccseer** [comment]
Send me a file for sample.

To avoid crash, please use the Mask plugin.

**Comment by Hubcube** [comment]
Thanks for the tip with the Mask plugin, but I need other .mov files to play.

I'm sending you a [Dropbox link](https://www.dropbox.com/s/mv8m5u4qxrfk7c1/seer_test_footage.zip?dl=0) with the zipped files (288mo). Including a DNxHR clip which also causes the crash. DNxHD plays correctly.

In case you need it, here is the [VLC plugin to read the Cineform codec.](http://www.kolor.com/cineform-vlc-plugin/)

**Comment by ccseer** [comment]
I just did some tests.
These two video type can be supported in the future update.

**Comment by Hubcube** [comment]
That would be awesome!

Best regards!

**Comment by ccseer** [comment]
![image](https://cloud.githubusercontent.com/assets/15963166/19210225/c8e3f0f8-8d4e-11e6-8d1a-8bb992095511.png)

**Comment by ccseer** [comment]
Done.
