### ISSUE TITLE
Where to download older versions of Seer?

### ISSUE THREAD

**Issue by Darthagnon** [ccseer/Seer#410]
I've noticed weird bugs since updating, e.g. previewing music shows a QR code that decodes to:
```
 Found 1 barcodes:
 1) QRCode, Confidence: 1.00, Page 1, Rectangle: [24; 22; 229; 229]
 Value: MDK SDK is outdated. Get a new free sdk from https://sourceforge.net/projects/mdk-sdk/files/nightly, or purchase a license.
paypal: https://www.paypal.me/ibingow/500
more: https://www.qtav.org/donate.html

  Decoding took: 0.184 seconds.
  Preparations: 0.038 seconds.
```
[#397](https://github.com/ccseer/Seer/issues/397)

Where can I download Seer-3.1.0.exe?

**Comment by ccseer** [comment]
what version are you using?
3.2.1 has fixed it

**Comment by Darthagnon** [comment]
I can confirm v3.2.1 fixes the issue, though is there anywhere I can download older versions? I like to keep older versions of software around in case of bugs.
