### ISSUE TITLE
Need To Try Seer Again Before Buying Please Help

### ISSUE THREAD

**Issue by allenbisconti** [ccseer/Seer#413]
Good Evening, I had tried Seer a few months ago but then tried Quicklook, Quickeye, Powertoys, and a few others so now I don't remember the look/feel of Seer.  From all the reviews, it seems that only Seer is going to be having continued support??  So if the owners of Seer could get back to me and give me another free trial even if its just for a day, I'd greatly appreciate it, I just need to try it again before buying.  Thank you.  PS:  For some reason Seer is still downloaded onto my Windows 10 Pro PC, but the trial ran out a few months ago so I can't try it again.. help...

**Comment by ccseer** [comment]
hi, 
I think the **free trial** is designed this  way.
sorry.

**Comment by allenbisconti** [comment]
Hi @ccseer   Are there any videos that show it in action?  I couldn't find anything on Youtube.

**Comment by ccseer** [comment]
https://sourceforge.net/projects/ccseer/files/

this is the free version, released 8 years ago.

**Comment by allenbisconti** [comment]
@ccseer  Thank you for getting back to me, appreciate it.  :-)   Does the free version have any plugins for viewing Office docs (Word, Excel, etc)?

**Comment by ccseer** [comment]
sorry no.

**Comment by allenbisconti** [comment]
So the paid version allows that plugin to be installed correct?  (The OIT plugin)

**Comment by ccseer** [comment]
yes. maybe you can try from MS Store first. 
not recommend buying without full experience

**Comment by allenbisconti** [comment]
Thank you for your help.. if you could, please delete this question/thread, it won't let me.  Have a great day.
