### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Olove521** [ccseer/Seer#414]
增加esc退出.
增加按下空格后自动选择第一项.
增加左右键进行返回上一级下一级.
希望可以适配更多，比如系统应用按下空格：按下空格回收站按下空格可以预览回收站文件；按下空格控制面板可以预览相关功能；等等

**Comment by ccseer** [comment]
修改 user.ini 里的 use_trigger_key_close 即可 esc 关闭预览

https://support.qq.com/products/366565/faqs-more?id=132153

**Comment by ccseer** [comment]
大部分操作都有快捷键
可在 设置 界面里找到

**Comment by Olove521** [comment]
> 修改 user.ini 里的 use_trigger_key_close 即可 esc 关闭预览
> 
我用的是微软商店版.


> 空格只能有 触发 功能

好吧i

> 大部分操作都有快捷键 可在 设置 界面里找到

看到了，但是前两条我说的意思是按下空格后它不会自动聚焦，就是空格打开后再按esc键没有反应，只有鼠标点一下聚焦后才有反应.👀
第三条那个左右键返回上下级这个功能也不会自动聚焦于当前打开的页面的选项上.
emmmm...还有这个话说什么时候可以自定义键？🤔

**Comment by ccseer** [comment]
不聚焦是为了让你在按下空格后 再按上下左右能切换文件

你要获取键盘输入焦点可以 在设置里找到一个获取焦点的全局快捷键。

没有焦点的时候同一个文件按两下就会关闭预览，或者修改 user.ini 可以全局关闭预览窗口。
