### ISSUE TITLE
Seer is not getting focus automatically upon preview.

### ISSUE THREAD

**Issue by Apocalypse612** [ccseer/Seer#415]
I presume this is supposed to be the intended behavior? I'm not quite sure what is going on here. I use this with Dopus primarily, but the same behavior occurs on regular file explorer.

Please assist.

**Comment by ccseer** [comment]
the input focus allows you to navigate files by pressing Arrow keys

**Comment by Apocalypse612** [comment]
I can understand the use of a manual get focus command, but why doesn't this happen automatically? For example, after previewing, I should be able to hit escape, without the need to manually regain focus.

**Comment by Apocalypse612** [comment]
Ah, brilliant! The user.ini worked change was exactly what I was looking for. Thanks so much. This should be in the GUI, and if it is, I totally missed it. Either way, best regards, and God bless (we have the same name 🍡).

**Comment by Apocalypse612** [comment]
Ah, brilliant! The user.ini worked change was exactly what I was looking for. Thanks so much. This should be in the GUI, and if it is, I totally missed it. Either way, best regards, and God bless (we have the same name 🍡).
