### ISSUE TITLE
uwp 3.2.1 Freezes, when playing multimedia files (video/audio)

### ISSUE THREAD

**Issue by littledarker** [ccseer/Seer#417]
Hi. 
When i use seer pro for playing multimedia on my laptop, this freezy (play, but not reaction on my actions, window is freeze - only killing via task manager to get stop this). For any other formats (docs, pictures and other) no problem. Reinstall from winstore dont help. 
Seer Pro from winstore (without plugins), version 3.2.1.0 U, win 11 23H2 (22631.3007)
![Снимок экрана 2024-01-21 105535](https://github.com/ccseer/Seer/assets/140228161/bd8fdd33-77c1-4df6-841e-417a76670786)

**Comment by ccseer** [comment]
all  multimedia files, or some specific files?

**Comment by ccseer** [comment]
https://github.com/ccseer/Seer/issues/374

**Comment by ccseer** [comment]
hi

need to modify the user.ini , to use a different decoder

**Comment by ccseer** [comment]
thanks for your report

**Comment by ccseer** [comment]
but, if you can play video, the audio should work fine

**Comment by ccseer** [comment]
let's use #374  for this issue.
