### ISSUE TITLE
mp4 smooth loop transition

### ISSUE THREAD

**Issue by LuisBurdallo** [ccseer/Seer#418]
Any chance this can be implemented? Just so it works like a gif does. I am working with perfect looping videos and it would be amazing if seer could prevent the break/freeze it does right when it replays back from the beginning.

**Comment by ccseer** [comment]
send a sample please

**Comment by LuisBurdallo** [comment]
[AD_00017.zip](https://github.com/ccseer/Seer/files/14023173/AD_00017.zip)

I've made the gif you'll find straight from the mp4. This video player can repeat forever seamlessly.

https://apps.microsoft.com/detail/9PD88QB3BGKN?hl=en-US&gl=US

**Comment by ccseer** [comment]
thx

**Comment by ccseer** [comment]
implemented in 3.2.2
