### ISSUE TITLE
Program Crashes opening some jpg files

### ISSUE THREAD

**Issue by 1111Al** [ccseer/Seer#421]
The app is awesome and useful, but unfortunately I have a big issue. After a few days from installation, especially after wake PC from sleep, the app keep crashing (it closes) repeteadly, opening any multimedia file, Images, video, audio.
Secondly, I've a starnge problem, I can install the app from the app store, if instead I download the exe file from official website, the installation after the admin privileges window, does not start, it gets stuck there.

**Comment by ccseer** [comment]
thx for your report

**Comment by ccseer** [comment]
what you end up using? the all app from MS Store?

**Comment by 1111Al** [comment]
I use apps from everywhere, especially programs outside the MS Store.

**Comment by 1111Al** [comment]
For now I unistalled and reinstalled it, then unlike the previous installation, I ticked the option to run as administator and I didn't install plugins. Now I'll check how it goes.

**Comment by ccseer** [comment]
thx.

**Comment by 1111Al** [comment]
Update, I found out the application crash opening some image jpg files edited with specific program.

**Comment by ccseer** [comment]
specific program?

**Comment by 1111Al** [comment]
First of all Exposure X7, but I also use Gimp and others.

**Comment by ccseer** [comment]
can I send you a win32 setup file to see if it's able to run?
I am not sure if i fixed it.

**Comment by 1111Al** [comment]
Ok, do I have to uninstall my current Seer installation to try this win32 setup?

**Comment by ccseer** [comment]
no need. you only need to quit your Windows store edition, and uninstall the old one you installed from the website.

**Comment by ccseer** [comment]
https://wetransfer.com/downloads/a4bed0c1d2638d65fbb6e511b4957bc620240610073900/d70f6f7cd5db891e6ad04a3782c1548620240610073921/4dde81?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid

**Comment by ccseer** [comment]
please let me know if you are able to run it

**Comment by ccseer** [comment]
I have released the new versioin 3.2.3

**Comment by 1111Al** [comment]
Ok. I wait for MS Store version, because as already mentioned, the setup exe files for this application mysteriously fail to install.

**Comment by ccseer** [comment]
Hi, the bug of win32 version is fixed, I think.

And the MS Store vesion has published

**Comment by 1111Al** [comment]
No way, same issue with the same files in new version. Lately I noticed that Seer crashes opening not edited jpgs too. By the way I tried with two other similar utilities, including the one from Powertoys, and no one crashes with those files, nor with any other files. If you want I can upload a jpg sample that cause crash with along with identical one that doesn't crash.
I installed the OIT plugin for documents, but some file like rtf or odt only open in light mode, with black text on white background, sometimes in light grey text on white, so they're unreadable.

**Comment by ccseer** [comment]
send me these files please

**Comment by 1111Al** [comment]
https://www.mediafire.com/file/tvlqjh54thig4d2/Nuova_cartella_%25282%2529.rar/file

**Comment by ccseer** [comment]
![img_v3_02bv_4cbb32bc-f812-4fc6-83e6-51f8e6c55e9g](https://github.com/ccseer/Seer/assets/15963166/9c28cbf6-7e65-4657-bfc5-9d4538b6a8a7)

**Comment by ccseer** [comment]
can you make it crash again, then send me the log file?
it's located at %TEMP%/Seer/Seer.log
