### ISSUE TITLE
Crash while viewing .CR3 files

### ISSUE THREAD

**Issue by yakinvasion** [ccseer/Seer#428]
Repeatable crash while viewing .CR3 file from Cannon R5 camera. Image initially opens, then hangs and is unresponsive. Attempts to close the preview window or refocus onto desktop result in a crash. Issue persisted through version update. Attempt to uninstall and reinstall version 3.2.3, issue persists. After uninstall and reinstall, license key no longer works. 

Seer Version: 3.2.3
Windows Version: 10.0.19045.4651
File Size: 41.3 MB
FIle Type: .CR3

**Comment by ccseer** [comment]
can you send me a sample file

**Comment by ccseer** [comment]
I just checked, seer doesn't support it yet, so it will show the file property.
