### ISSUE TITLE
Seer 1.0 cannot enter settings anymore

### ISSUE THREAD

**Issue by JoachimBarrum** [ccseer/Seer#43]
Hi, after I got the upgrade to Seer 1.0 I cannot enter settings or any of the system tray menus. They are all greyed out: http://prntscr.com/cn12sy

**Comment by JoachimBarrum** [comment]
Actually, Nothing worked for me. Space wasn't opening images anymore and since I couldn't enter settings I don't know if the keyboard shortcuts were changed or something. I tried re-installing and opening the program with Administrator Privileges, it didn't help, so I had to downgrade to 0.8.

**Comment by jameswolfe** [comment]
I believe that settings, help, and about are all disabled until you purchase the license for Seer 1.0. 

I'm having the same issue with Seer 1.0 not working at all.  I am currently using the 3 day trial, the program launches but pressing the spacebar no longer previews documents, songs, pictures, or videos.  I was excited to test out the new video playing and see if it ran smoother.

**Comment by JoachimBarrum** [comment]
ok, thats kinda strange. Whats the point of the 3 days trial then? I will not upgrade to 1.0 or purchase it unless I know it works for sure.

**Comment by jameswolfe** [comment]
Ya.  I was thinking that the program MIGHT work when I purchase the upgrade, but I am hesitant to spend money if there's a chance that it won't work.  I guess I'll have to stick to 0.8 until it gets fixed.

**Comment by ccseer** [comment]
It's a bug. I'm sorry. 

I will fix it as soon as I can.

**Comment by ccseer** [comment]
Fixed.

I will release v1.0.1 in three hours.

Sorry for this bug.

**Comment by ccseer** [comment]
It's done now.

new version is 1.0.1. www.1218.io

**Comment by JoachimBarrum** [comment]
thanks great, works nice now. 
Btw, in 0.8 when watching videos that had alpha you would actually see videos with the transparency in the previewer. But in 1.0.1 they are all opaque. Is this option still in the program somewhere? It was very useful when seeing through videoclips with alpha.

**Comment by ccseer** [comment]
OK.

v1.0.0 uses openGL for GPU rendering now. It does improved a lot.
Maybe the issue is a side effect.

**Comment by JoachimBarrum** [comment]
ok. I guess speed is preferred over alpha :)
