### ISSUE TITLE
Integration with Files app

### ISSUE THREAD

**Issue by Alinoe1** [ccseer/Seer#432]
Hi, i have lot of bugs with Files app (https://files.community/) on windows 11. When i click "space" preview of file bring on screen lot of times until close seer. when i have preview on screen any move of coursor closing preview window. but after that opening randomly fev times.

**Comment by ccseer** [comment]
I just did some tests, everything works fine.

**Comment by ccseer** [comment]
![image](https://github.com/user-attachments/assets/4e1e8f9f-8277-4ab8-96c9-5bdf55a9820d)

**Comment by ccseer** [comment]
![image](https://github.com/user-attachments/assets/5b0f21fd-1e71-4073-b96b-2e41c99228cb)
