### ISSUE TITLE
Windows defender detecting a (hopefully false positive) trojan in 3.3.0.

### ISSUE THREAD

**Issue by Arsoth** [ccseer/Seer#433]
![image](https://github.com/user-attachments/assets/c4b2669f-a481-46f3-be9b-2e0e16d4bff7)

Running windows 11.

It looks like it's a false positive based on these two virus total reports (for the 3.3.0 installer, and the exe itself):

https://www.virustotal.com/gui/file/d1a6b40c9d03d46f35f2d781e9edc72386f2fb2493c2104e92894684c4d3bb50/detection

https://www.virustotal.com/gui/file/cf293d0b25d9e7cbf6c3da21d4b85fc052672682974892594ec7e35b70f682a3/detection

**Comment by ccseer** [comment]
the exe from MS store edition has the MD5 value with the one from installer

**Comment by ccseer** [comment]
however, I am planning to release a different exe in the next release.

and there is nothing I can do to avoid the issue.
