### ISSUE TITLE
The order page does not open

### ISSUE THREAD

**Issue by shurarama** [ccseer/Seer#436]
![image](https://github.com/user-attachments/assets/6cacd598-f761-41d0-b97d-05e5773e936e)

**Comment by ccseer** [comment]
everything works on my side currently

**Comment by ccseer** [comment]
can you do a hard refresh in your browser please?

**Comment by ccseer** [comment]
- Hold down Ctrl and click the Reload button.
- Or Hold down Ctrl and press F5.
