### ISSUE TITLE
Shortcut (space bar) not lauching seer

### ISSUE THREAD

**Issue by Gudulon** [ccseer/Seer#437]
Been using Seer for a long time but since the last 2 days it does not launch with Space bar anymore, I have to clic on the task bar hidden icon for it to launch.  Then the space bar do not work to quit either (Esc / Ctrl+w works)

tried restart seer and PC , no changes.

i'm on windows 10 22H2 and seer 3.3.0 U

**Comment by ccseer** [comment]
hi

are you using a 3rd party explorer ?
have you changed the default trigger key in Settings?

**Comment by Gudulon** [comment]
hi, 

no 3rd party explorer.
I have not changed the default trigger Settings (but tried to to see if it would work with a ctrl or shift key added to space, but it did not work either)

**Comment by ccseer** [comment]
a known bug here: seer may fail to detect if it's running from MS Store, then failed to answer the input. 
so do you see a Register item in the menu?

**Comment by ccseer** [comment]
send me the log please
https://github.com/ccseer/Seer/wiki/9.-Misc#get-logs-and-crash-files

**Comment by ccseer** [comment]
have you tried uninstall & install again?

**Comment by Gudulon** [comment]
I did not

and now i have re-installed and it seems to work has intended again.
Thanks so much for your quick answers.
