### ISSUE TITLE
File types

### ISSUE THREAD

**Issue by Ramirezgs12g** [ccseer/Seer#444]
Can get 3mf to work oh and the email for seer@gmail doesn't work.
I pick up the app, it was on  sale but i was charged full price

**Comment by ccseer** [comment]
I assume you are purchasing for the  Store Version since the website version has no discount.
The purchase process is controlled by the Microsoft. nothing I can do about it. 

Also my email addr can be found in About Seer dialog

**Comment by ccseer** [comment]
please open a discussion here: https://github.com/ccseer/Seer/discussions/categories/file-formats
