### ISSUE TITLE
High CPU use at idle (1.0 + 0.8)

### ISSUE THREAD

**Issue by vrodionov** [ccseer/Seer#45]
Seer is constantly using the CPU on my system when it's running in the background.

Unfortunately, the amount of resources this consumes is far from trivial. I get it hovering somewhere around 0.5% on my fairly high-specced main system (a quad-core Skylake Xeon with 64GB RAM), and at a whopping 10-15% inside a single-CPU VMware VM running on the same hardware.

Another fun fact is that I easily get to 10% CPU load on my main system when Seer is running inside the VM.

The amount of CPU used is not related to tracking the selected files in Explorer. If Seer is running, it using a lot of the CPU time. I have tried this with both 0.8 and 1.0, and the result is exactly the same.

This looks like a failry serious bug that needs to be addressed. Rest assured I will be a paying customer once it does.

**Comment by ccseer** [comment]
0.7.5 works ok.

And I figured it out. 

Fixed. 
Will be included in next version, probably v1.0.2.
: )
