### ISSUE TITLE
PDF scrolling issues on trackpad

### ISSUE THREAD

**Issue by AndrewOCC** [ccseer/Seer#46]
I've been using Seer on a Surface Pro 4, and scrolling in the PDF preview has been unreliable. 

Fast scrolling (i.e. 1 or two pages at a time) works fine, with little latency unless a later page hasn't been loaded. However, it appears that when performing the scrolling gesture at slower speeds, the pdf preview will only move a single line and then stop, no matter the distance of the scrolling gesture. 

Fixing this to allow more reliable scrolling would greatly improve usability.

**Comment by ccseer** [comment]
just done some works to improve PDF, the improvement can be discovered in next version.

**Comment by ccseer** [comment]
Please let me know if  you have further questions.
: )
