### ISSUE TITLE
如何隐藏seer任务栏图标

### ISSUE THREAD

**Issue by chhsgithub** [ccseer/Seer#47]
找了设置没看到，如果能隐藏就更好了

**Comment by ccseer** [comment]
我想不到任何隐藏的理由啊.

以及其他 app 示例。

**Comment by ccseer** [comment]
隐藏了怎么改设置.

怎么退出.

怎么 激活License 

怎么 .....

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/623666/Seer.zip)


替换 Seer.exe,  在启动的时候加个命令行参数就可以了  **Seer.exe -i**

不过需要正式版才能用
