### ISSUE TITLE
Install-uninstall issue

### ISSUE THREAD

**Issue by feldrim** [ccseer/Seer#48]
1- After uninstall, there are still some things left in the regedit. Like:

```
- HKEY_CURRENT_USER/SOFTWARE/COREY and everything under that.
- HKEY_CURRENT_USER/SOFTWARE/Microsoft/Windows/CurrentVersion/Run/Seer
- HKEY_CURRENT_USER/SOFTWARE/Microsoft/WindowsNT/CurrentVersion/AppCompatFlags/CompatibilityAssistant/Store/Seer
- HKEY_LOCAL_MACHINE/SOFTWARE/Microsoft/CurrentVersion/AppPaths - 1syt.exe and 7za.exe
```

2- After uninstall thede folders remain:
- **Seer** folder under `Program Files`
- **Corey** folder under `AppData\Local`
- **Seer** folder under `AppData\Local\Temp`
- **Seer** folder under `AppData\Local\VirtualStore\Program Files`

**Comment by ccseer** [comment]
fixed in v1.4.0

**Comment by Xairoo** [comment]
Not fixed. Entries still exists after uninstall.

**Comment by ccseer** [comment]
which version are you using?
There is a checkbox to opt-in for remove the items in register

**Comment by Xairoo** [comment]
Ah... the free from sourceforge. That's the problem. Anyway, I changed back to QuickLook because I don't have to toggle the timeline for videos. But the free version should also remove the entries because of blocking QuickLook.

Btw. still no way to click the preview and use the keyboard arrows to change the files after clicking the preview? That's a big pain. macOS solved it so well.

**Comment by ccseer** [comment]
this was provided in very early version.
And the last free version was almost three years ago, a lot of things are
out of control.

Sorry.

**Comment by Xairoo** [comment]
> Btw. still no way to click the preview and use the keyboard arrows to change the files after clicking the preview? That's a big pain. macOS solved it so well.

Does that work in the paid version?

**Comment by ccseer** [comment]
no.
macOS solved it because the quicklook winodws in macOS is not a normal
windows it does not has input focus.
And Seer has a lot of shortcuts, so this will remain the same.
