### ISSUE TITLE
Unable to fix icons

### ISSUE THREAD

**Issue by vgarside** [ccseer/Seer#51]
Hi,

loved Seer then the icons got buggered.  I have since removed Seer and all traces of it and yet it still shows the blue question mark on all files in one folder.  I have deleted the iconcache file without success.  How can I fix these icons?

![snip_20161004142631](https://cloud.githubusercontent.com/assets/5473043/19093085/921f49cc-8a3e-11e6-8f32-509caeb9b0fb.png)

**Comment by ccseer** [comment]
I don't think the bug is caused by Seer. Because Seer does't  associate with file extensions, it just matches the extension when the file triggered.
