### ISSUE TITLE
Seer opens images randomly without hitting space

### ISSUE THREAD

**Issue by JoachimBarrum** [ccseer/Seer#52]
Im experiencing Seer opening images randomly by itself when I enter new folders. And some times it does it multiple times so I have to wait for it to finish before I can continue working. A bit frustrating

**Comment by ccseer** [comment]
It happens when you are trying to open PhotoShop.exe ??

**Comment by JoachimBarrum** [comment]
Yes you could be right about that!

**Comment by ccseer** [comment]
#23
