### ISSUE TITLE
Jpg images are not previewing

### ISSUE THREAD

**Issue by lukevision** [ccseer/Seer#53]
I can pretty much preview any file, especially after I installed some of the plugins (like autocad, jpg2png, eps-convertor) but most jpg files just show metadata and no image.

**Comment by ccseer** [comment]
> most jpg files just show metadata and no image

which version are you using?

if you installed plugin correctly, you would view them.  
http://1218.io/plug-in.html

**Comment by ccseer** [comment]
Hi~~

if the bug still exists, you can reopen this issue.
