### ISSUE TITLE
Files corrupt after preview

### ISSUE THREAD

**Issue by jonbaade** [ccseer/Seer#54]
Windows 10 reading off FAT32 CompactFlash memory cards. After previewing the file (.mov) the file in the directory shows up as 3K and all the data from the file is gone. I lost about a dozen shots from a video shoot today simply by previewing them before I figured out what was happening.

**Comment by ccseer** [comment]
which version are you using?

**Comment by ccseer** [comment]
Really sorry about this. 

I will fix this as soon as I can.

**Comment by ccseer** [comment]
Hi~~

would you please tell me which version you are using?

It's a serious bug.

**Comment by jonbaade** [comment]
I thought I had upgraded to 1. but it looks like it was still at .8

Just upgraded now.

Any way you can think of to try and get the files recovered?

**Comment by ccseer** [comment]
I am sorry.

Do you have a FileHistory?
I think this is the only way to recover.

This is a dumb bug. Too many changes committed in last version.
I just figured out why.

Really sorry about this.
All the files you lost were filled with text contents which are the plugin data. You can open them with text editor. 

I removed the file.  It will happen again.


Really sorry.

**Comment by ccseer** [comment]
Can I send you a free license for this?

**Comment by jonbaade** [comment]
Dang. Um...I guess but I'm scared to use this now. I can't afford to loose footage just by previewing.

**Comment by jonbaade** [comment]
It doesn't by any luck copy to a temp folder or anything? I'm just grasping at straws. And thanks for your quick response to this issue. I appreciate it.

**Comment by ccseer** [comment]
Sorry. It will not happen again from now.

The your file contents should filled with these text.
https://github.com/ccseer/Seer-plugins/blob/master/release/all_temp.json

It was my mistake. sorry.

**Comment by jonbaade** [comment]
Yeah...I just opened up the 3K file in a hex editor and saw that. I'm trying a file recovery software and crossing my fingers. Since the data for the video IS there...it's just a matter of digging it out. I'm not giving up yet. And yes, thank you for the offer. I'll take the license you offered.

**Comment by ccseer** [comment]
http://1218.io/order/order.html

Just skip the No.1.

**Comment by jonbaade** [comment]
Done. Thanks.

**Comment by ccseer** [comment]
Really sorry about this.

I will be more careful when I am trying to write a file.

**Comment by ccseer** [comment]
@jonbaade  Hi~ I have one more question to confirm. It was the v0.8.0 which made your files corrupt, right?
