### ISSUE TITLE
Version 1 doesn't work

### ISSUE THREAD

**Issue by Ale-zen** [ccseer/Seer#55]
Last working version is 0.8, when I upgrade to v 1, all menu list of the notify icon get dimmed, and space bar shorcut doesn't work anymore. I have also Listary and QuickAccessPopUp installed.
I also can't get preview for jpg and fonts (I have plugins installed). Photoshop and illustrator preview works (very slow), but the image is not fitted to the monitor dimension. It's as it was showed in real pixel (1:1) and so it is expanded beyond the monitor margins. :)

**Comment by coooooooooorey** [comment]
Hi~~

the lastest version  is 1.0.1. It should work.

Did you read the release note?
http://1218.io/app/last-relnotes.html

**Comment by ccseer** [comment]
Hi~~

the lastest version is 1.0.1. It should work.

Did you read the release note?
http://1218.io/app/last-relnotes.html

**Comment by ccseer** [comment]
When did you update to v1.0.0 ?

**Comment by Ale-zen** [comment]
I confirm that v 1.0.1 is working :)
No jpeg and font preview, also with plugins installed ...

Il 12/10/2016 02:51, Seer ha scritto:

Hi~~

the lastest version is 1.0.1. It should work.

Did you read the release note?
http://1218.io/app/last-relnotes.html

**Comment by ccseer** [comment]
Maybe you just didn't install it correctly.

**Comment by ccseer** [comment]
http://1218.io/plug-in.html

**Comment by Ale-zen** [comment]
It should be ok, they are listed in the plugins panel...


Il 12/10/2016 17:25, Seer ha scritto:

Maybe you just didn't install it correctly.
