### ISSUE TITLE
Plug-ins interface won't load

### ISSUE THREAD

**Issue by randall13** [ccseer/Seer#56]
I can see the local view just fine, I think. But the "available" isn't coming up. See copied screenshots below.

![image](https://cloud.githubusercontent.com/assets/22799038/19321687/9dd6027c-907b-11e6-8fac-b769626856bc.png)

![image](https://cloud.githubusercontent.com/assets/22799038/19321699/a791920e-907b-11e6-9e98-8930dff4e97e.png)

**Comment by ccseer** [comment]
Hi~~

there is a bug more important. So I changed the url which was used in Seer. 
It will be fixed in next version.

You can download these plugins manually : https://github.com/ccseer/Seer-plugins/tree/master/release

**Comment by ccseer** [comment]
All you need to do is download the *.zip file, and Seer does the same thing.

**Comment by ccseer** [comment]
Done.
Update to 1.1.0
