### ISSUE TITLE
MSOffice plugin not resolving load issues

### ISSUE THREAD

**Issue by randall13** [ccseer/Seer#57]
I believe I have the MSOffice plug-in loaded correctly (installed following instructions, selected json file, etc.), but I still can't preview PowerPoint files. After thinking about it for a while (first screenshot), it eventually just loads the file information (second screenshot). Loads Excel files, though.

![screenshot 678](https://cloud.githubusercontent.com/assets/22799038/19321823/2cfc12b6-907c-11e6-9614-4abcecee9c43.jpg)

![image](https://cloud.githubusercontent.com/assets/22799038/19321813/24e27796-907c-11e6-9a48-38f26510338e.png)

**Comment by ccseer** [comment]
#33
