### ISSUE TITLE
markdown预览不能自动换行

### ISSUE THREAD

**Issue by renyouguo** [ccseer/Seer#6]
0.6
win10 x64
除了自动换行，最好再加入大纲视图，不然真不知道大文件的结构。

**Comment by ccseer** [comment]
现在 Web 预览的那一块还有些问题，主要是框架的 bug，所以得等问题修复了才能改进 markdown 。
到时候会用 python 写一个插件然后直接看生成 html。

目前是这样计划的，所以在这之前不会继续改这一块。抱歉。

新年快乐。

**Comment by ccseer** [comment]
Hi， @renyouguo  

刚刚优化了markdown 的加载，但由于框架的bug，还是不能达到之前的预期。
所以，对于markdown 有其他要求的话，你可以自己用 python.markdown 或者别的方法写一个转换器。

然后替换调 plugins/md.exe .

默认的 md.exe 主要做的就是转换 markdown 成 html 字符串，然后标准输出控制台。
Seer 会自动接收控制台内容，然后加载。

如果以后 Webengine 的 bug 修复了，到时候会把它转成插件的模式，提供更好的支持。

:smile:

**Comment by ccseer** [comment]
fixed in 1.0.0
