### ISSUE TITLE
Seer will load but won't work. No access to menu items either

### ISSUE THREAD

**Issue by ChrisTrivedi** [ccseer/Seer#60]
Hi I am running Seer 1.0 on Windows 10 and am having issues with functionality. The program will load and sit in the notifications menu, but when clicked only gives me options to 'Register' or 'Quit', all others are greyed-out. Quitting and restarting doesn't seem to work either. This problem has been pretty consistent for me since the 1.0 upgrade.

Any help would be greatly appreciated! Thank you.

**Comment by ChrisTrivedi** [comment]
I realize now that 1.0 is the PAID version. Sorry about that, I was confused.

**Comment by ccseer** [comment]
Hi~

you can still use the free version v0.8.0.

Thanks
