### ISSUE TITLE
Seer 1.1: bug in the manifest. It is non-DPI-aware! (Win 10)

### ISSUE THREAD

**Issue by vrodionov** [ccseer/Seer#61]
This is a bug that manifests in the latest Seer 1.1 / Windows 10, and is likely related to the new windowing code. Seer is not DPI-aware, but does declare itself to Windows as such.
In my setup, I have a high-DPI laptop monitor (15' 3840x2160) and an older HD monitor (23' 1920x1080). When Seer window is moved to the second smaller HD screen, it becomes unusably large.

There is a workaround:
1. Enable external manifests
2. Create a manifest file for Seer that sets dpiAware to False (which is is). I have attached the manifest to the post below.

This is not an optimal solution, of course, as this has to be done manually.
It is best to either set the internal manifest value to False, or to update Seer code to be DPI-aware.

**Comment by vrodionov** [comment]
To add to the description of the manifest workaround: if a preview window is open on the second (smaller) screen, Seer menus on high-DPI screen are extremely small, and default to the center of the screen.
![seer dpi](https://cloud.githubusercontent.com/assets/1922226/19491250/fd64986c-957a-11e6-9677-f400680669a5.png)
[Seer.exe.manifest.txt](https://github.com/ccseer/Seer/files/537087/Seer.exe.manifest.txt)

**Comment by ccseer** [comment]
Hi~

I only have two ordinary monitors now.

I will look into it when I got a high DPI screen.

**Comment by ccseer** [comment]
I think I might buy a surface book to support high dpi and touching control when I got enough money. Not many people buy a license, so it may take a while.

But I think it will be fixed sooner or later. 
Thanks for your feedback.

**Comment by vrodionov** [comment]
My suggestion would be to simply change the dpiAware value in the built-in manifest to “False”.

You can use the external manifest that I provided as a starting point. I am attaching it here again.

Please test it on a regular/low-res computer. If this setting does not break anything (it should not!), it will be a very good fix for now.

All this does is it tells Windows to handle all the scaling issues for Seer. This is what Windows was doing anyway for 0.8 and below, and it worked just fine.

The issue of menu scaling can be fixed later, and I don’t think it’s critical.

But as far as dpiAware goes, not everyone is savvy enough to know how to turn on the external manifests!

Thanks for developing this – it’s a really valuable utility.

Cheers,

 

Valentin

**Comment by ccseer** [comment]
Hi~

I just realized there is a simple way to support high dpi.

I can build a new exe file to see if this was fixed. If you wanna help me test it.

**Comment by vrodionov** [comment]
Sure deal!

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/538596/Seer.zip)


Nothing changed.   Just add a line to try to support High dpi.

**Comment by ccseer** [comment]
move it to installation folder.  Make a  backup in case it becomes worse.

**Comment by ccseer** [comment]
please let me know if it works.
: )

**Comment by vrodionov** [comment]
No, it’s a no go, unfortunately.

The window layout is completely dead with this version. For example, .pdf files are not centered anymore, and I can’t see the window title.

This is true on both monitors. The sizing of the window also does not look right: it becomes bigger when moved to the lower-res screen.

In contrast, the “False” manifest workaround works fine.

 

To be specific, I removed my manifest as well, so I have been testing the bare .exe here.

**Comment by ccseer** [comment]
fixed in v1.5.0

**Comment by ccseer** [comment]
https://1drv.ms/u/s!AgtA1EcmfJYVhsJInyCXUC_PRZX31w

https://1drv.ms/u/s!AgtA1EcmfJYVjNx3WfKCtISXklPxSw


please download these two files, and move them to your Seer folder.
This version is DPI aware. And can work with Open/Save Dialog

**Comment by ccseer** [comment]
but currently, only white theme Is available.

**Comment by vrodionov** [comment]
Thanks! I will give it a try.

**Comment by ccseer** [comment]
I have released the new version~~

still remain a lot of things to be done.

next version will fix them

**Comment by ccseer** [comment]
thanks again.
