### ISSUE TITLE
1.1 seer, vidoes are laggy

### ISSUE THREAD

**Issue by mhalbouni** [ccseer/Seer#63]
hi,
i am using windows 10 64bit.
i have been using Seer 0.8 for a while t=now and it was working fine.
yesterday I Purchased 1.1 and registered it and since then whenever i run a video its getting laggy.
I am watching the same videos which i was watching before but they ran very smooth in 0.8 version now they are laggy.

**Comment by ccseer** [comment]
Hi~
In v0.8.0, video rendering costs a lot cpu using.

Video has improved a lot since v1.0.0, the limit is that it requires OpenGL, which means it needs graphics driver or something.

Please keep in touch, I need to know if the old rendering way, used in v0.8.0, works for you or not. If it does, I will add an option to choose rendering style in next version.

**Comment by mhalbouni** [comment]
0.8.0 was working fine. 
Btw I have a GTX nvidia 960 on my pc so I should have the OpenGL. But having an option to chose how to view the video in the next version seems a good feature.

**Comment by coooooooooorey** [comment]
Do you mind I send you a Seer-test.exe with old rendering way to test if it works?
Maybe Monday.

**Comment by ccseer** [comment]
Do you mind I send you a Seer-test.exe with old rendering way to test if it works?
Maybe Monday.

**Comment by mhalbouni** [comment]
Ok sure you can send it.  Not sure what do you mean as I mentioned it was working already in the old version.

**Comment by ccseer** [comment]
[Seer-video_rendering_test.zip](https://github.com/ccseer/Seer/files/547130/Seer-video_rendering_test.zip)

Move this exe to your installation folder. Quit the running Seer.exe. Run this one to see if it works fine to you.

Please let me know the result.

**Comment by mhalbouni** [comment]
hi,
i tested it.
its a bit better, but somehow it felt like the vdeo is shaky.
but its better i guess
