### ISSUE TITLE
1.1 seer, cant understand stay on top feature

### ISSUE THREAD

**Issue by mhalbouni** [ccseer/Seer#64]
hi,
i am using windows 10 64bit.
When i disable "stay on top" feature the video disappears.
even if i minimize everything and keep only the folder where the video is located and run the video i just dont appear.
i cant hear the audio of it but not the motion picture.

**Comment by ccseer** [comment]
Hi~

Thanks for your feedback, I need to look into on Monday.

All I can say now is that everytime "stay on top" changed it will close the preview window, it is how it's designed.

**Comment by ccseer** [comment]
No bug here.
You can find it by minimizing other windows.

**Comment by mhalbouni** [comment]
You are wrong, it is a bug. 
The point is when you disable stay on top you say you need to minimize other Windows and no way to see it without minimizing. So it means that everything should be minimized while you are using it which is wrong. 

It should be everything is up and including seer and you can change what windows you want on the screen but they are on top of each other. 

If you keep it working like now it's exactly like "stay on top" enabled which means one window opened and I can't change it.

**Comment by mhalbouni** [comment]
Seer should start in top and then the user change Windows if he wants. But the way it's working now seer is under all other apps so you need to minimize everything and you can't open any other Windows which another way to describe "stay on top" but on desktop

**Comment by ccseer** [comment]
FIXED
