### ISSUE TITLE
Monospaced font

### ISSUE THREAD

**Issue by st-so** [ccseer/Seer#65]
First of all: Thanks for your fantastic tool!

My question concerns the display of text files. How can I change to a **monospaced**, i.e. fixed-width font for a **defined set of file extensions**? This would be extremely useful for a variety of text files, such as .tex files or scripts.

Given that it already works for Python .py files, .html files etc., I have some hope this involves only minor tweaks.

Thanks a lot in advance!

**Comment by ccseer** [comment]
Will try to provide a font access for text view.

**Comment by st-so** [comment]
That sounds great! Looking forward.

**Comment by ccseer** [comment]
I was thinking about this feature. 

If you have bought a license, you should try to use the plugin code_highlight. It can help you convert the tex file to html. And you modify the view by editing css file.

**Comment by ccseer** [comment]
the **code_highlight** only works in Seer-1.1.0 and after.
