### ISSUE TITLE
TeX Syntax Highlighting

### ISSUE THREAD

**Issue by st-so** [ccseer/Seer#66]
Hi,

I am new to Seer and appreciate your work very much. Thanks!

I was wondering if you are planning to include .tex file support, i.e. monospaced font (see my other "Issue") and syntax highlighting?

That would be fantastic!

**Comment by ccseer** [comment]
You can try to use the plugin Code_highlight if you are using v1.1.0.

**Comment by ccseer** [comment]
![image](https://cloud.githubusercontent.com/assets/15963166/19632843/6b24bcfe-99dd-11e6-8850-38277f4a2b9c.png)

**Comment by ccseer** [comment]
It only works for v1.1.0.

**Comment by st-so** [comment]
Thanks for the info! I will give it a try.

**Comment by ccseer** [comment]
If you are using v1.1.0, try the plugin code-hight
