### ISSUE TITLE
Malfunction

### ISSUE THREAD

**Issue by YORANDOM** [ccseer/Seer#67]
I have to install seer about every 2 days, because it just doesn't want to open any files anymore. I can't use the setttings anymore (view picture).

I'm also annoyed by the "ctr+alt+s is already used by another application" notification (it opens HP Support information. Can I solve this?

![untitled](https://cloud.githubusercontent.com/assets/23025945/19637458/8230b636-99cf-11e6-880d-14be1fff96b7.png)

**Comment by ccseer** [comment]
Buy a license.

**Comment by ccseer** [comment]
1218.io/order/order.html

**Comment by ccseer** [comment]
or  use v0.8.1

**Comment by YORANDOM** [comment]
So if I buy a liscense, everything should work fine?

**Comment by ccseer** [comment]
yes.

**Comment by YORANDOM** [comment]
Ok, thanks

**Comment by ccseer** [comment]
![image](https://cloud.githubusercontent.com/assets/15963166/19638639/6aeaff08-9a07-11e6-9e57-4cf945207c0b.png)

delete/change  Focus  shortcut to avoid notification
