### ISSUE TITLE
Seer Open and closes repeatedly in Photoshop

### ISSUE THREAD

**Issue by JoachimBarrum** [ccseer/Seer#69]
I know this is an open issue, but I wanted to give some more information on how to reproduce. 

When I open Photoshop Seers often previews images or files in Explorer multiple times without me hitting any Keyboard key. 
But, when I use Photoshop Generate I'm experiencing Seer going completely bananas, openening and closing images for every image I export, which I believe is part of the same problem. 
So if you create a PSD file with multiple layers and give the layers a .png extension in the file name and then choose file>generate>Image Assets you might experience the same bug.

**Comment by ccseer** [comment]
Would you like to help me to test if this have fixed?

**Comment by ccseer** [comment]
I will send a new Seer.exe to see if the new code works.

**Comment by JoachimBarrum** [comment]
of course! just send it when you have it ready

**Comment by JoachimBarrum** [comment]
Let me know if you need my contact info? Or isn't the test version ready yet?

**Comment by ccseer** [comment]
Didn't get ready.
Too many work for employer. : (

**Comment by ccseer** [comment]
I will send you a new setup file here when it's ready.

**Comment by JoachimBarrum** [comment]
ok thanks :)

**Comment by ccseer** [comment]
Sorry. Didn't work it out.

Have to release a version with this bug now.

**Comment by ccseer** [comment]
Trying to implement this today, still failed.

I think I need to set priority of this bug a little lower, so I can move forward.

: (

**Comment by ccseer** [comment]
I just found that Spacebar is a shortcut for hand tool in PS.

Can you modify the  *Trigger Keys* in *Settings-Keyboard*?
For instance, add a *Control* Modifier key?

**Comment by JoachimBarrum** [comment]
Good suggestion, maybe that's all it takes. I switched now, will let you know if I notice any more problems then :)

**Comment by ccseer** [comment]
fixed in 1.6.0

**Comment by JoachimBarrum** [comment]
great! when will it be out? according to the website 1.4 is the current version.

**Comment by ccseer** [comment]
Because the license issue, I withdrew 1.5.0.

So all  the new features will be included in 1.6.0
