### ISSUE TITLE
不兼容doublecommander

### ISSUE THREAD

**Issue by ivysrono** [ccseer/Seer#7]
0.6
win10 x64
没有测试过TC等类似文件管理器，在DC上，我已经在 选项-Files Views 去掉了空格移动到下一文件的选项，但seer依然没有成功预览。

**Comment by ccseer** [comment]
我还第一次听说 doublecommander 。

估计是和一些第三方一样改写了视图显示，导致 Seer 获取不到信息。

我晚点看看。

**Comment by ccseer** [comment]
sorry
: (

**Comment by ivysrono** [comment]
关掉是因为我好久不用seer了，你不要浪费精力在支持DC上面。

**Comment by ccseer** [comment]
好吧。。
不知道你最后用的是哪个版本，免费版更到 0.8.1 了
收费版也到 1.4.0 了，比较完善了

这种第三方文件管理器一般可以通过  管理器 内部的快捷键配置去用命令行调用 Seer 就可以达到效果了

B.R.
