### ISSUE TITLE
I hope a application named Everything can be supported.

### ISSUE THREAD

**Issue by iamsunxing** [ccseer/Seer#71]
I hope a application named Everything can be supported.Everything is powerful but free,if Seer support it,there will be more perfect to using,I believe.

**Comment by ccseer** [comment]
I contacted the author of Everything last year.

I have to wait until the version of Everything come out.

Before that, there is an other way to solve this. Invoke Seer via Command
line from Everything

**Comment by epixcz** [comment]
How to invoke Seer from command line? And is it possible also in free version?

**Comment by ccseer** [comment]
I just tested it on Seer-1.6.1. It works fine.


![tim 20170930113541](https://user-images.githubusercontent.com/15963166/31042145-d4e6b626-a5d3-11e7-8f84-d75be7393946.png)



![tim 20170930113625](https://user-images.githubusercontent.com/15963166/31042146-d896bc6c-a5d3-11e7-96cb-1d0b98745af5.png)




![snipaste20170930_113653](https://user-images.githubusercontent.com/15963166/31042147-db0c1c80-a5d3-11e7-99a3-93a74b1b7392.png)

**Comment by ccseer** [comment]
if Seer is installed in C:\Program Files (x86)\Seer\Seer.exe
the `(` and `)` should be transferred to `$(` and `$)`
e.g.:
$exec("C:\Program Files $(x86$)\Seer\Seer.exe" "%1")

**Comment by ccseer** [comment]
*This is provided by Thomas Gessl*


how to combine TotalCommander with Seer.
I picked it up again and made a solution with AutoHotKey.

My script looks like this:
```
#InstallKeybdHook
#Persistent
#HotkeyInterval,100
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#SingleInstance force
SetTitleMatchMode, 2 ; Makes matching the titles easier
;--------------------------------------------------------------------------------
; Win+Space im TotalCommander: Öffne Seer
#IfWinActive, Total Commander (x64) 9.20 - Thomas Gessl
#Space::
	PostMessage 1075, 2018, 0, , ahk_class TTOTAL_CMD ; Copy names with full path to clipboard
	Sleep, 100
	Run, "C:\Program Files (x86)\Seer\Seer.exe" "%clipboard%"
	Sleep, 200
	SplitPath clipboard, fname
	WinActivate, %fname%
return
```

I'm running unMacLike on Windows + Space, but it works. Seer comes to the fore and by Space alone it closes again.
Of course you could also open by Space alone.

**Comment by ccseer** [comment]
Supported in Seer-2.5.3.

If Everything is running as Administrator, Seer needs the same authorization.

**Comment by ccseer** [comment]
![image](https://user-images.githubusercontent.com/15963166/167043519-1fef3fe8-11c3-4318-a054-9d93211c9d2a.png)

The `+` means Seer is running as Adminstrator.

**Comment by Darthagnon** [comment]
How do I use Seer in conjunction with Everything? Do we need to set a custom verb?

**Comment by ccseer** [comment]
Make sure your first column is `Name`, and the second column is `Path`

![image](https://github.com/ccseer/Seer/assets/15963166/cb7d5979-2285-4e5a-b6bc-a55a3c7b5ac1)

**Comment by ccseer** [comment]
> Make sure your first column is `Name`, and the second column is `Path`
> 
> ![image](https://github.com/ccseer/Seer/assets/15963166/cb7d5979-2285-4e5a-b6bc-a55a3c7b5ac1)

it's not required if Seer-4.0.3 + Everything-1.5a
