### ISSUE TITLE
When previewing video or audio file problem moving to next file.

### ISSUE THREAD

**Issue by wailjdii** [ccseer/Seer#72]
I often use Seer to find the right file. Open up with space and just click arrow keys on keyboard. If I open a video or audio file and click on the timeline bar to check what's in the middle of file, arrow keys on keyboard no more get me to the next file. Then I have to press spacebar to exit Seer and then move to next and again press space. Quicklook on Mac did let me move to next file also after scrubbing. I'd be super happy to have this functionality in next version, because I work a lot with video / audio files. Other than that Seer is fantastic.

**Comment by ccseer** [comment]
On mac, quick look view has no focus, you can't select the file text, or do other things. 
That's the difference between Seer and the original one.

I will try to remember the play record for the last 20 media type file, so next time you open it, Seer will seek to the old position.

**Comment by ccseer** [comment]
Is that will solve your problem?

I think I will implement this in v1.3.0

**Comment by wailjdii** [comment]
I think You didn`t understand correctly my problem.  I made a screencapture to demonstrate the problem, there are comments on the bottom to describe what`s happening. https://youtu.be/FCexOCSwOi8

**Comment by ccseer** [comment]
Got you.

Like what I said. There is a difference here between Seer and the original one. The quick look on mac has no focus at all, which means it can't respond to your shortcut or something when you clicked on the preview window.

What I am trying to do is to make the situation you mentioned a little better. If Seer automatically seeks to the position where last time you saw it, I think it would be a little bit more convenient.

**Comment by ccseer** [comment]
[Seer.zip](https://github.com/ccseer/Seer/files/599393/Seer.zip)

You can replace the exe file in your installation folder.
