### ISSUE TITLE
Seer cannot go to the next picture after rotating / tapping the picture

### ISSUE THREAD

**Issue by kelvinhalim** [ccseer/Seer#74]
So I have been using the "preview" app on mac mainly to preview photos and videos

Some of the photos are **Vertical** but Seer seem to be opening those type of photos on a **Horizontal** mode which means it got rotated 90 degrees. Thus, I tried to use the rotate button on the bottom right corner.

After taping on the picture (_or rotating the picture_), it seems to be entering this "edit mode" (_there is a slight difference on the shadow of the border_) where you can rotate or change the zoom or do many other things. **Downside is**, I don't really know how to proceed to the next picture other than closing seer by pressing the trigger button then open the next picture by pressing the trigger button once again.

What I think might be the solution of this problem is to make it able to open Vertical pictures in Vertical mode by default and make it able to escape that "edit mode" _**without having to close the preview**_ and press the trigger button again on the next picture. 

Or is there actually any button that I'm missing out?

Thankyou very much though for bringing this app to live 👍 
Appreciate all your hardworks!

Regards,
Kelvin

**Comment by ccseer** [comment]
Which version are you using?

v1.2.0 has fix the image rotation bug.

Seer doesn't have the button yet, I'm considering to add it in the future.

**Comment by kelvinhalim** [comment]
It is on 0.8.1 I believe. Got it from https://sourceforge.net/projects/ccseer/

I've tried to update it just now but it tells me that it is up to date

Do you mind telling me how to upgrade it? Or is there a link where I can download the upgrade?

I tried to download the Seer master but I don't think that is the correct thing to download

**Comment by ccseer** [comment]
0.8.1 is the last free version now.

v1.2.0 is a paid version. 
http://www.1218.io

**Comment by kelvinhalim** [comment]
Alright bought it just now :)

I tried the trial version before and found a bug where the preview goes total gray (_can't see anything_) on every picture I went through, however it fixes itself after I restarted the app. So probably there's just something wrong with my laptop

Anyway will be waiting for the next update on the button! (**to make it able to exit that "edit mode"** probably escape button will do)

Thankyou very much

**Comment by ccseer** [comment]
http://1218.io/sub/release-note.html

next version is almost done.
Sorry, I can't add this in next version.

Maybe later.

**Comment by kelvinhalim** [comment]
Ahh, okay

Btw, I found it (the gray preview) again when I tried to open a video file:
![untitled](https://cloud.githubusercontent.com/assets/24406732/20920504/c604a884-bbd2-11e6-9764-36d04d9605ed.png)

After restarting the app, I tried to open a photo file and this happen:
![untitled 2](https://cloud.githubusercontent.com/assets/24406732/20920631/4a4c17da-bbd3-11e6-90a1-a301020a6804.png)

I don't really know what triggers this to happen

**Comment by ccseer** [comment]
?????????

which graphics card are you using?  NVIDIA?
How about the graphics driver?

**Comment by kelvinhalim** [comment]
NVIDIA GeForce GTX 950m

Yeah, could be the driver. Still on the November 28th update. So this might be the problem.

I'll inform you if this keeps happening after the driver update

**Comment by ccseer** [comment]
I add a shortcut to switch window focus back. 

This may help after you tapping the preview window.
