### ISSUE TITLE
Network-Speed / File-Transfer Speed 

### ISSUE THREAD

**Issue by kll4k** [ccseer/Seer#76]
When using seer the Network-Speed / File-Transfer Speed staggers massivley. As soon as i quit Seer everything works fine. I got almost crazy until i found seer responsible for this issue.

![image](https://cloud.githubusercontent.com/assets/24684404/21365140/40d4f416-c6f4-11e6-91a5-dbba39303628.png)

I'm using Seer 1.3, in previous versions the problem already existed

Would be awesome if there is a solution for this Problem

best regards
kll4k

**Comment by ccseer** [comment]
There are a few things that need a network.

- Every time Seer started, Seer will check for update and new plugins.
- Every time you triggered a markdown/html file, and there is a remote content.

**Comment by ccseer** [comment]
the File-Transfer issue
are you trying to preview a file?

**Comment by kll4k** [comment]
no, it happens when i download a file from my nas, when i download files from the Internet and it happens when i transfer a file to a USB Stick.

I was looking for a solution for hours until i found out that the problem is resolved when i quit seer.
I'm using a Surface book / Windows 10.

**Comment by ccseer** [comment]
I really don't think it's a bug about Seer.

Seer can work perfectly without network. 
And if you didn't try to preview a file, it doesn't do anything but monitor the keyboard to see if user tapped the Spacebar.

**Comment by kll4k** [comment]
Here you can see the described effect:
https://www.dropbox.com/s/6jsjxow9cxwcz2n/20161221_091011.mp4?dl=0

I'll delete it after a day

**Comment by ccseer** [comment]
Fixed in 1.9.0
