### ISSUE TITLE
Seer Doesn't Preview in Connected Servers

### ISSUE THREAD

**Issue by darecinema** [ccseer/Seer#78]
I'm using Windows 10 Pro with Seer 1.3.0 and I have two Synology servers. When trying to preview files on servers with spacebar, it's not working. Any known fixes?

**Comment by ccseer** [comment]
Currently there is no way to achieve this. Will try to implement this in
future release.

**Comment by itnAAnti** [comment]
I second this request!

**Comment by ccseer** [comment]
Is there anyone like to borrow me a server to test?

**Comment by j-m-larsen** [comment]
Seer does not work on mapped network drives like "net use w: \\computer\sharedfolder" and then w:-drive in explorer.
However Seer DO work if you access the shared folder directly via the UNC-path in explorer.

**Comment by itnAAnti** [comment]
I just rebooted, and now Seer is working property with my mapped drives. (On a Synology NAS, mounted using the SMB protocol) so I'm not sure what was going wrong before.

@ccseer I was going to test to see if I could replicate the issue by sharing a folder on my local PC, then mounting it through "net use" as @j-m-larsen mentioned, (If that successfully replicated the issue, no server would be needed for your testing.)

Now I'm unable to replicate the issue at all, everything is working perfectly. I will keep testing and post an update if I am able to figure out how to reliably reproduce the issue.

**Comment by j-m-larsen** [comment]
I just did a reboot, and now Seer works on my mapped network drives too. Apparantly you have to do a reboot after installing Seer to make it work properly.

**Comment by ccseer** [comment]
@darecinema

**Comment by ccseer** [comment]
Let me know if you guys have further questions. 
: )
