### ISSUE TITLE
Tables in .md file cannot be displayed

### ISSUE THREAD

**Issue by VeryLazyBoy** [ccseer/Seer#79]
It seems that seer cannot handle tables in a md file.

Seer | Cannot | Show | Tables
-------- | :-------- | :--------- | :-----------
A|B|C|D

**Comment by ccseer** [comment]
Which version are you using?

Have you try to change the stylesheet file for markdown?

**Comment by VeryLazyBoy** [comment]
I am using the latest v1.3.0. I have changed the stylesheets but the problem still remains.

**Comment by ccseer** [comment]
OK

I might try to write a plugin to solve this in next version.

**Comment by ccseer** [comment]
or you can do it yourself, it's simple

**Comment by VeryLazyBoy** [comment]
Is it okay to write a plugin using JavaScript?

**Comment by ccseer** [comment]
You can write plugin in any language. 

Check the plugins already exist.
https://github.com/ccseer/Seer-plugins/tree/master/rename

Rename is only a *cmd* file.

Currently the plugins are written by python( font/MSOffice ), c++( CodeHighlight)..
https://github.com/ccseer/Seer-plugins

**Comment by ccseer** [comment]
http://1218.io/sub/plug-in.html

**Comment by VeryLazyBoy** [comment]
Besides tables, the lists with more than two levels cannot be displayed correctly either:

+ List1
  + List2
     + List3

In seer, lists look like:
+ List1
  + List2
  + List3

**Comment by ccseer** [comment]
I'm writing a new software recently. Seer-1.4.0 might be released in April.

Would you please attach a sample file?

I will try to make a plugin 2morrow, this time the Markdown will be parsed by JavaScript.

**Comment by VeryLazyBoy** [comment]
What kind of sample files should I attach?

**Comment by ccseer** [comment]
A file with all the formats Seer can't display properly.

And a screenshot the Markdown file should look like.

**Comment by VeryLazyBoy** [comment]
I just found two more formats which seer cannot display properly. Here is the sample file:
[Sample.zip](https://github.com/ccseer/Seer/files/814386/Sample.zip)

**Comment by ccseer** [comment]
OK. 好了

md2html plugin

**Comment by ccseer** [comment]
![image](https://cloud.githubusercontent.com/assets/15963166/23538260/fcd0c798-000c-11e7-8983-eb7bc39975c6.png)

**Comment by ccseer** [comment]
And, you can change the html code yourself.

All exe done is to copy `css` and `js` to the output folder.

```html
<!DOCTYPE html><html><head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="stylesheet" href="md_style.css">
  <script src="marked.js"></script>

  <script type="text/javascript">
    function load() {
      var placeholder = document.getElementById('placeholder');
      placeholder.innerHTML = marked(placeholder.innerHTML);
    }
  </script>
</head>

<body onload="load()">
  <div id="placeholder"><p>#Markdown_Pleaceholder#</p>
</div>

</body></html>
```
