### ISSUE TITLE
using the esc key makes previews show as a grey window

### ISSUE THREAD

**Issue by davebrny** [ccseer/Seer#80]
if the `esc` key is used to close an image preview, then the next time that seer is used, the preview shows up as a grey window. it only seems to be happening with image files. previewing a txt file and then using `esc` doesnt cause any problems, but once the grey window shows for an image preview it will then start showing txt files and any other previews in the same way.

if the X in the top right corner is used to close the image preview then this problem doesnt happen at all.

windows 10 pro (version 1607 build 14393.693)

**Comment by ccseer** [comment]
Yeah.

I have met the same bug. It will be fixed in next release.

Thank you.

dave <notifications@github.com>于2017年2月18日周六 下午7:16写道：

**Comment by ccseer** [comment]
fixed.

**Comment by ccseer** [comment]
will release new version soon
