### ISSUE TITLE
Everything opened on a 4K display is pixelated. Seer is not "Retina" ready.

### ISSUE THREAD

**Issue by readytechgo** [ccseer/Seer#83]
It doesn't look like Seer is ready for 4K displays because everything I open is pixelated. Nice idea but not being ready for 4K (or higher) displays seems like a huge oversight.

**Comment by ccseer** [comment]
Are you using Seer in multi-monitors which have different resolution ratio?

**Comment by readytechgo** [comment]
Yes. I have two 4K displays and one 1080p display.

**Comment by ccseer** [comment]
#61

**Comment by ccseer** [comment]
Seer is using  resolution ratio of the primary monitor currently.

It will be fixed in future release. ( I don't have a high resolution device now.
