### ISSUE TITLE
Make the licence not bound with the machine

### ISSUE THREAD

**Issue by yodahuang** [ccseer/Seer#84]
Seer is a great software, but one thing that I find particularly frustrating is that it's bound to the machine. I lost my laptop with Seer, and then I get a new one I lost Seer license. What's worse, after I go to Microsoft Store to get a replacement for my Surface Book, I lost the license one more time. It would be good if the license could be unbounded from machine, just like idm or Listary.

**Comment by ccseer** [comment]
what is your old machine id, the one you have activated before.

**Comment by yodahuang** [comment]
Sadly I've lost the id. This is just a suggestion since I'm a little afraid after I purchase the license my laptop will need a replacement for some other small hardware issues again...

**Comment by ccseer** [comment]
What is your email addr?

Yanda Huang <notifications@github.com>于2017年3月13日周一 上午10:25写道：

**Comment by yodahuang** [comment]
It's yord.huang@gmail.com

**Comment by ccseer** [comment]
The license is lifetime.
If your license doesn't work anymore, you can just email me, tell me what
happened, then I will send you a new license.
