### ISSUE TITLE
中文出现乱码

### ISSUE THREAD

**Issue by OnlyEasyDay** [ccseer/Seer#86]
gb2312编码的文件会出现部分字符显示为方块，而utf8编码的中文则是完全的乱码

**Comment by ccseer** [comment]
软件版本？

**Comment by OnlyEasyDay** [comment]
![image](https://cloud.githubusercontent.com/assets/26744581/24413184/b0da76f4-13a8-11e7-8923-d0f4c56d0c92.png)
软件是0.8.1，Windows10周年更新专业版
![image](https://cloud.githubusercontent.com/assets/26744581/24413225/d07c932a-13a8-11e7-8608-fa4fbeb818f6.png)
![image](https://cloud.githubusercontent.com/assets/26744581/24413335/22da8e74-13a9-11e7-8d5f-a84098a7ee21.png)

**Comment by OnlyEasyDay** [comment]
好吧是Mactype的问题，关了Mactype就好了……抱歉打扰了
