### ISSUE TITLE
JPG very slow in 17-6900K work station

### ISSUE THREAD

**Issue by lukevision** [ccseer/Seer#87]
It takes several seconds to load medium to large JPG images (I guess it converts them to PNG in the background?) - since 80% of the things I want to preview are JPG this makes SEER much less useful.  Can this be improved?  

FYI - the Win 10 photos up opens them instantly.

**Comment by ccseer** [comment]
which version?

**Comment by lukevision** [comment]
1.3.0

**Comment by ccseer** [comment]
how big is that file?

Send me the file. I will do some tests.

**Comment by lukevision** [comment]
It's not a particular file - any JPG over 1MB in size starts to takes about 1-2 seconds.  And if they are in the 5-8MB size they take about 7-8 seconds.  This is consistent with all jpg images.  A very fast system that opens the same images in Photoshop or other programs instantly.

**Comment by ccseer** [comment]
Send me your Settings - Plugin page please.

**Comment by lukevision** [comment]
![2017-03-29 10_37_25-settings - seer](https://cloud.githubusercontent.com/assets/22641960/24460324/fa621386-146b-11e7-950f-7a42c4d40873.png)
![2017-03-29 10_37_42-settings - seer](https://cloud.githubusercontent.com/assets/22641960/24460325/fa65565e-146b-11e7-9aed-56c6f2de32a2.png)

**Comment by ccseer** [comment]
<img width="703" alt="qq20170329-0 2x" src="https://cloud.githubusercontent.com/assets/15963166/24460464/ee532840-14d0-11e7-8f71-238eb9ceddd3.png">



please remove  NO.2, 
then go `Settings - Advanced`, click the `folder` icon to open a explorer, remove all the temp files.

Click `OK` to close `Settings`.

: )

**Comment by ccseer** [comment]
Please let me know if it works

**Comment by ccseer** [comment]
There is no need to install the plugin `jpg2png` anymore actually.

**Comment by lukevision** [comment]
Ah, ok - yes that fixed it!  But for anyone else coming along - it did not work until I rebooted the machine.  After that it is fast again.  Thanks for the help.
