### ISSUE TITLE
Possible Feature

### ISSUE THREAD

**Issue by HiImAndy** [ccseer/Seer#88]
Is it possible to have seer preview the file only when I'm holding down on the space bar? I don't really like the idea of having to repeatedly hit my keyboard; seer is a previewer, so it makes sense to only have it open for a short period of time.

Might it also be possible to get seer to preview the last/current **hovered** file (and have it do nothing if the current file isn't in the current directory?)

**Comment by ccseer** [comment]
Sorry, I can't implement your the first feature request. It's not good to use, I had tried it.

I will implement a new feature which can solve your second problem in Seer-1.5.0.
