### ISSUE TITLE
Word files do not preview.

### ISSUE THREAD

**Issue by markjulmar** [ccseer/Seer#91]
Latest version of seer (updated this week). I get the standard file/exe preview with file details like size, date, etc. This is for both .doc and .docx.

![image](https://cloud.githubusercontent.com/assets/5099741/25252175/a168da12-25e1-11e7-8af4-1dd0d928af66.png)

Settings indicates that the Office previewer is present.

**Comment by ccseer** [comment]
You need to add the plugin.

http://1218.io/seer/plug-in.html

The office plugin is slow. I'm trying to implement a new way to solve this.
