### ISSUE TITLE
Does not bring focus to Seer window

### ISSUE THREAD

**Issue by johngraybosch** [ccseer/Seer#92]
On my Windows 7 machine, when I press the Space key, the Seer window appears with the selected file, but it does not focus, so the focus remains on the Explorer window. What that means is that scrolling and the escape key don't work until I click on the Seer window to select it.

**Comment by ccseer** [comment]
you need to set the global shortcut (focus).

**Comment by ccseer** [comment]
And use shortcut to switch focus
