### ISSUE TITLE
Duplicate background process and notification bar icons on Windows 10.

### ISSUE THREAD

**Issue by LongerPro** [ccseer/Seer#93]
When Seer(version 0.8.1) running, click shortcut to start Seer, duplicate background process and notification bar icons appear on Windows 10.

**Comment by ccseer** [comment]
第一次运行的时候偶发会这样。

几率很小的。

**Comment by ccseer** [comment]
一般都是装机后第一次运行，偶尔会发生。

影响不大啊

**Comment by ccseer** [comment]
诶。这个问题好像在后期改过。

1.4.0 应该是没了

**Comment by LongerPro** [comment]
应该是只有第一次时间会这样，重启了之后没这个问题了。
