### ISSUE TITLE
Huge PING!!

### ISSUE THREAD

**Issue by trosnyak** [ccseer/Seer#95]
Dear Sir,
Your app monstrously affects ping of my internet.
When, for example. playing online games it spikes upto 3500ms, which makes it impossible for me to play games.
Why is it affecting internet connection that badly?! Is information being uploaded somewhere?!
As soon as I force your app to close, it restores to normal 5-20ms range. I prefer to uninstall your software and would recommended anyone to do the same until you solve this issue.
Best Regards,
DT

**Comment by ccseer** [comment]
Which version?

**Comment by ccseer** [comment]
which version of Seer are you using?

In the meantime, you can submit Seer to any secure company or website to see if it's OK to use.
Because I'm know it's safe.

B.R.

**Comment by ccseer** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=4865

**Comment by trosnyak** [comment]
Version 1.4
Your latest build from your website I downloaded 2 days ago. 
Still it makes no sense for software of your nature to affect Ping. 
Why so?
Best Regards,
DT

Отправлено с iPhone

> 28 апр. 2017 г., в 4:04, Seer <notifications@github.com> написал(а):
> 
> Which version?

**Comment by ccseer** [comment]
I don't know currently.
I will check it carefully next Monday.

But I am pretty sure it has nothing to do with Seer, I wrote codes all by myself.

**Comment by trosnyak** [comment]
Its Seer 100%.
Checked and double checked.
In Russia we have a good school for coding and IT in general. I have no
doubts, so please check. I am quite an advanced user.
Best Regards,
DT

28 апр. 2017 г. 15:53 пользователь "Seer" <notifications@github.com>
написал:

**Comment by coooooooooorey** [comment]
OK。

I am the developer, and I am also a user. I work with Seer everyday. 

I will look into it and get back to you ASAP.

**Comment by ccseer** [comment]
OK。

I am the developer, and I am also a user. I work with Seer everyday.

I will look into it and get back to you ASAP.

corey <notifications@github.com>于2017年4月28日周五 下午10:36写道：

**Comment by trosnyak** [comment]
To make your life a tad easier, please download WOT Pinger.
Run test with Seer open and then with Seer closed/shut.
You will see a difference.
DT

28 апр. 2017 г. 16:36 пользователь "corey" <notifications@github.com>
написал:

**Comment by ccseer** [comment]
![f66fedf6e510aac1669a6dc5a4bc6282](https://cloud.githubusercontent.com/assets/15963166/25614914/c8c84c9e-2f66-11e7-8ff5-677e0784f443.png)

**Comment by trosnyak** [comment]
That is upload through-output (DL or UL).
I said your software creates problem with PING (not permanent, but
occasional, every 5 seconds or so).
Regards,
Denis

**Comment by ccseer** [comment]
Sorry.

It's a bug.

**Comment by ccseer** [comment]
fixed in 1.9.0
