### ISSUE TITLE
md.exe 0xc000007b error when peeking md file after system start

### ISSUE THREAD

**Issue by JimAmuro** [ccseer/Seer#96]
![image](https://cloud.githubusercontent.com/assets/11274691/25772896/3639d17a-3242-11e7-9f1a-59e900b5b9cb.png)
I set Seer to run at Windows start. After the system starts, when I want to peek a .md file, it gives me this error. However, if I close Seer afterwards then open it again, it doesn't throw that error and runs properly, which is weird. 
I found that md.exe in plugin folder, double click on md.exe also shows that error.

OS: Windows 10 Creator Update
Seer: 0.8.1

Is there any way to deal with the bug? If not, is there anyway to peek .md like normal text file (bypass md.exe)? Thank you very much!

**Comment by coooooooooorey** [comment]
这个好像是随安装包一起发布的。
实在不行，要不 重装一下 Seer 看看？？？

新版本是有 新的插件可以看 markdown的。

**Comment by ccseer** [comment]
这个好像是随安装包一起发布的。
实在不行，要不 重装一下 Seer 看看？？？

新版本是有 新的插件可以看 markdown的。

**Comment by JimAmuro** [comment]
@ccseer 卸载重装过了 貌似没用 试过md2html的插件 也是这个error

**Comment by ccseer** [comment]
同样的error ??

三十二位的系统 还是六十四位？

**Comment by JimAmuro** [comment]
@ccseer 64位的系统

**Comment by ccseer** [comment]
周一我再编译一个给你试下。
第一次遇到这个情况

Md2html 旧版本是用不了的。这个插件需要显示网页，1.2.0才内嵌浏览器。

等工作日我再试试吧

**Comment by JimAmuro** [comment]
@ccseer OK 谢谢！
其实最奇怪的是它如果随着开机启动就不行，如果手动启动就可以，这我实在没什么头绪。

**Comment by ccseer** [comment]
Seer 也是用命令行调用执行文件。
如果你要直接看内容的话，看你能不能写代码了。

写个插件，把 文件复制一下就可以了。插件里面有个rename ，但是旧版用不了。你可以下载看看那个插件，就一行 批处理

**Comment by ccseer** [comment]
[markdown_test.pdf](https://github.com/ccseer/Seer/files/988568/markdown_test.pdf)


把文件下载下来

**Comment by ccseer** [comment]
改个后缀名为exe 就可以了
再试试

**Comment by JimAmuro** [comment]
请问是下载下来改成exe 双击运行吗？这个是做什么的？补丁？

**Comment by ccseer** [comment]
下载改后缀为exe

替换原来的 md.exe 
就可以了

**Comment by ccseer** [comment]
能不能用?

**Comment by JimAmuro** [comment]
不好意思 有点事忘了
我改名成 md.exe 然后换了原来那个 结果还是同样的错误。。算了就这样吧 我md用的也不多

**Comment by JimAmuro** [comment]
试了下rename 把后缀设为md就能用了 挺好的 谢谢！
请问能不能多设几个后缀 比如 mdown markdown md 这些都 rename ？我试了试 逗号 和 分号 貌似不行。。

**Comment by ccseer** [comment]
要改json ，或者在插件设置那里改

**Comment by ccseer** [comment]
要改json ，然后删除原来的设置重新添加。

或者直接在插件配置里 把后缀加上去。

我记得那个rename 老版本用不了的吧

**Comment by JimAmuro** [comment]
![image](https://cloud.githubusercontent.com/assets/11274691/26030366/8a583818-381f-11e7-9e3b-d4f82c9fa24b.png)

能用的 我就这样设置的 但是只能写一个后缀名 不知道怎么多设

**Comment by ccseer** [comment]
第一行第二个。 md 那一栏。空格分割

**Comment by ccseer** [comment]
![655795a6-0a0b-406f-9cdb-d3dffb526151](https://cloud.githubusercontent.com/assets/15963166/26031335/d097faac-38a1-11e7-9426-e33f1c9995f0.png)





先关闭了。
有问题再说吧。

**Comment by JimAmuro** [comment]
哦原来是空格。。我试了逗号分号 忘了这
总之谢谢了！
