### ISSUE TITLE
能否加入命令行参数或者单实例运行

### ISSUE THREAD

**Issue by xin2014** [ccseer/Seer#97]
平时使用 Totalcmd, 按 F3 可以查看文件
如果把查看器配置成 seer.exe, seer 没运行的时候, 第一个文件可以正常查看
但是第二个文件就不正常了, 有时候正常查看, 有时候 seer 通知 seer 已经运行, 不能查看
Totalcmd 实际上是调用了 Seer.exe filepath

我想能否在 seer 已经运行的时候, 调用 seer.exe filepath 直接查看文件, 或者加入命令行参数直接查看文件?
这样不但能在 Totalcmd 使用, 也能在 evertything 等一大批软件使用

**Comment by ccseer** [comment]
目前可以啊

**Comment by ccseer** [comment]
Seer.exe file_path

**Comment by ccseer** [comment]
什么版本

**Comment by xin2014** [comment]
1.4 版本, 我想更多的是一个 bug
经常跳出 "seer 已经运行", 出发规律很难捉摸

**Comment by ccseer** [comment]
![image](https://cloud.githubusercontent.com/assets/15963166/25880799/1be8c5ba-356c-11e7-8d44-0ab3a7308089.png)

**Comment by ccseer** [comment]
你把 Seer 关了 再用用 Seer.exe -?

**Comment by ccseer** [comment]
除了安装后第一次运行 点击多次的话, 可能导致 重复运行. 

后面基本都不会触发..

你再试试看看?

**Comment by ccseer** [comment]
诶..好像确实有个 bug..

**Comment by xin2014** [comment]
我退出了 seer 重新运行还是经常会出现, 有时多次好的, 突然就跳出提示, 有时多次跳出提示, 又突然好了, 实在没有什么规律
你找一下代码里什么情况下会系统通知 "Seer 已经运行。"

另外 -? 这个参数不常见, 一般都是 -h /? --help, 我应该试过以为没有命令行参数

**Comment by ccseer** [comment]
我下个版本把这里修了.

**Comment by ccseer** [comment]
你什么系统?

记得之前这块是好的.

**Comment by xin2014** [comment]
Windows 版本 1703 (OS 内部版本 15063.138)

**Comment by ccseer** [comment]
ok...

大概六月中旬以前 发布新版本

**Comment by ccseer** [comment]
1.5 修复了。 这次没问题了。
