### ISSUE TITLE
Not flashing to 3 blue dots when using arrow key to see next image

### ISSUE THREAD

**Issue by jonathankey** [ccseer/Seer#98]
Hey Mate

As a graphic designer + artist, I flick through images pretty regularly.
I just switched over from Mac and love seer but getting that flash each time is quite distracting when you're in the zone visually.

Is it possible to just have the option to not have that loading image (the 3 blue dots)
My PC is spec'd out, so really for fast PCs the 3 dot isn't necessary

Thanks man love it.

**Comment by ccseer** [comment]
Every time you try to preview a file, Seer has to calculate the md5&sha1,
file size and image size and a lot of things. So I think it's important to
let user know that Seer is working.

jonathankey <notifications@github.com>于2017年5月12日周五 上午1:01写道：

**Comment by ccseer** [comment]
fixed in next release
